<li class="dropdown">
    <a href="#" class="dropdown-toggle" data-toggle="dropdown">Documentation<b class="caret"></b></a>
    <ul class="dropdown-menu">
        <li>
            <a href="{genUrl controller="static" action="configuration-hints"}">Configuration Hints</a>
            <a href="http://www.lonap.net/routeservers.shtml">Route Servers</a>
            <a href="http://www.lonap.net/ipv6.shtml">IPv6 Info</a>
            <a href="http://www.lonap.net/cgi-bin/mrlg.cgi">Looking Glass</a>
        </li>
        {* PLEASE LEAVE THIS SOMEWHERE! IT'S ONLY FAIR INEX GETS SOME CREDIT :D *}
        <li class="divider"></li>
        <li>
            <a href="{genUrl controller="index" action="about"}">About</a>
        </li>
    </ul>
</li>
