<?php

namespace Repositories;

use Doctrine\ORM\EntityRepository;

/**
 * Cabinet
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Cabinet extends EntityRepository
{
    /**
     * Return an array of all cabinets names where the array key is the cabinet id.
     * @author Yann Robin
     * @return array An array of all cabinets names with the cabinet id as the key.
     */
    public function getForArray(): array {
        foreach(self::findAll() as $cabinet){
            $listCabinet[$cabinet->getId()] = $cabinet->getName();
        }
         return $listCabinet;
    }
}
