<?php

namespace Repositories;

use Doctrine\ORM\EntityRepository;

/**
 * ConsoleServer
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ConsoleServer extends EntityRepository
{
    /**
     * Get all console server (or a particular one) for listing on the frontend CRUD
     *
     * @see \IXP\Http\Controllers\Doctrine2Frontend
     *
     *
     * @param \stdClass $feParams
     * @param int|null $id
     * @return array Array of console server (as associated arrays) (or single element if `$id` passed)
     */
    public function getAllForFeList( \stdClass $feParams, int $id = null )
    {
        $dql = "SELECT  cs.id AS id,
                cs.name AS name,
                cs.model AS model,
                cs.active AS active, 
                cs.notes AS notes,
                cs.hostname AS hostname,
                cs.serial_number AS serialNumber,
                v.id AS vendorid, 
                v.name AS vendor, 
                c.id AS cabinetid, 
                c.name AS cabinet
                
                FROM Entities\\ConsoleServer cs
                LEFT JOIN cs.cabinet c
                LEFT JOIN cs.vendor v
                
                WHERE 1 = 1";

        if( $id ) {
            $dql .= " AND cs.id = " . (int)$id;
        }

        if( isset( $feParams->listOrderBy ) ) {
            $dql .= " ORDER BY " . $feParams->listOrderBy . ' ';
            $dql .= isset( $feParams->listOrderByDir ) ? $feParams->listOrderByDir : 'ASC';
        }


        $query = $this->getEntityManager()->createQuery( $dql );

        return $query->getArrayResult();
    }
}
