<?php

namespace Repositories;

use Doctrine\ORM\EntityRepository;

/**
 * IrrdbPrefix
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class IrrdbPrefix extends EntityRepository
{
    /**
     * Utility function to get the prefixes a customer has for a given protocol
     *
     * @param \Entities\Customer $cust The customer entity
     * @param int $protocol The IP protocol (4/6)
     * @return int The number of prefixes found
     */
    public function getForCustomerAndProtocol( $cust, $protocol )
    {
        return $this->getEntityManager()->createQuery(
                    "SELECT p.prefix FROM \\Entities\\IrrdbPrefix p
                        WHERE p.Customer = :cust AND p.protocol = :protocol
                        ORDER BY p.prefix ASC, p.id ASC"
                )
                ->setParameter( 'cust', $cust )
                ->setParameter( 'protocol', $protocol )
                ->getScalarResult();
    }

    /**
     * Utility function to get the number of prefixes a customer has for a given protocol
     *
     * @param \Entities\Customer $cust The customer entity
     * @param int $protocol The IP protocol (4/6)
     * @return int The number of prefixes found
     */
    public function getCountForCustomerAndProtocol( $cust, $protocol )
    {
        return $this->getEntityManager()->createQuery(
                    "SELECT COUNT(p.id) FROM \\Entities\\IrrdbPrefix p
                        WHERE p.Customer = :cust AND p.protocol = :protocol"
                )
                ->setParameter( 'cust', $cust )
                ->setParameter( 'protocol', $protocol )
                ->getSingleScalarResult();
    }
}
