<?php

namespace Repositories;

use Doctrine\ORM\EntityRepository;

/**
 * Layer2Address
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Layer2Address extends EntityRepository
{
    /**
     * Check if a mac address already exist for a vlan
     *
     * @param  string $mac The MAC address to search for
     * @param  int $vli The VlanInterface ID to search
     * @return bool true if the result is greater than 0 false if it is 0
     */
    public function isMacExisting(string $mac, int $vli ): bool {
        $dql = "SELECT count(l2a.id)
                    FROM Entities\\Layer2Address l2a
                    WHERE l2a.mac = ?1 
                    AND l2a.vlanInterface = ?2";

        $query = $this->getEntityManager()->createQuery( $dql );
        $query->setParameter( 1, $mac );
        $query->setParameter( 2, $vli );

        return ( $query->getSingleScalarResult() > 0 ) ? true : false;
    }
}