<?php

namespace Repositories;

use Doctrine\ORM\EntityRepository;

/**
 * SecEvent
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SecEvent extends EntityRepository
{
}
