<?php

/*
 * Copyright (C) 2009 - 2019 Internet Neutral Exchange Association Company Limited By Guarantee.
 * All Rights Reserved.
 *
 * This file is part of IXP Manager.
 *
 * IXP Manager is free software: you can redistribute it and/or modify it
 * under the terms of the GNU General Public License as published by the Free
 * Software Foundation, version v2.0 of the License.
 *
 * IXP Manager is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
 * FITNESS FOR A PARTICULAR PURPOSE.  See the GpNU General Public License for
 * more details.
 *
 * You should have received a copy of the GNU General Public License v2.0
 * along with IXP Manager.  If not, see:
 *
 * http://www.gnu.org/licenses/gpl-2.0.html
 */

namespace Repositories;

use Illuminate\Support\Facades\Session as SessionFacade;

use Doctrine\ORM\EntityRepository;

/**
 * RSPrefix
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Session extends EntityRepository
{
    /**
     * Delete all the active session for the user
     *
     * @param int   $userid
     * @param bool  $deleteCurrentsession Do we need to delete the current session
     *
     * @return void
     */
    public function deleteByUser( int $userid, bool $deleteCurrentsession = false )
    {
        $dql = "DELETE FROM Entities\\Session s 
                WHERE s.user_id = ?1";

        if( !$deleteCurrentsession ){
            $dql .= " AND s.id != '" . SessionFacade::getId() . "'";
        }
        return $this->getEntityManager()->createQuery( $dql )->setParameter(1, $userid )->execute();
    }
}

