
{* NB - USED FOR BOTH ADMIN AND CUSTOMER VIEW - BEWARE OF SECURITY *}

<div class="row-fluid">

    <div class="span6">

    <h3>
        Connection {counter name=numconnections}

        {assign var='vlanints' value=$vi->getVlanInterfaces()}

        {if count( $vlanints ) }
            {assign var='vlanint' value=$vlanints.0}
        {else}
            {assign var='vlanint' value=0}
        {/if}

        <small>
            {assign var=physInts value=$vi->getPhysicalInterfaces()}
            {if $vi->getType() eq SWITCHPORT::TYPE_PEERING and  count( $physInts )}
                &nbsp;&nbsp;&nbsp;&nbsp;{$physInts[0]->getSwitchPort()->getSwitcher()->getInfrastructure()->getName()}
            {elseif $vi->getType() eq SWITCHPORT::TYPE_FANOUT}
                &nbsp;&nbsp;&nbsp;&nbsp;Reseller Fanout

                {if count( $physInts ) and $physInts[0]->getRelatedInterface()}
                    for <a

                    {if $user->getPrivs() eq USER::AUTH_SUPERUSER}
                        href="{genUrl controller="customer" action="overview" id=$physInts[0]->getRelatedInterface()->getVirtualInterface()->getCustomer()->getId()}"
                    {else}
                        href="{genUrl controller="customer" action="detail" id=$physInts[0]->getRelatedInterface()->getVirtualInterface()->getCustomer()->getId()}"
                    {/if}

                    >{$physInts[0]->getRelatedInterface()->getVirtualInterface()->getCustomer()->getAbbreviatedName()}</a>
                {else}
                    <em>(unassigned)</em>
                {/if}

            {elseif $vi->getType() eq SWITCHPORT::TYPE_RESELLER}
                &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Resller Uplink
            {/if}

            {if $vi->getPhysicalInterfaces()|@count > 1}
                {assign var='isLAG' value=1}
                &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;LAG Port
            {else}
                {tmplinclude file='customer/overview-tabs/ports/physintstatus.phtml' pi=$physInts[0]}
                {assign var='isLAG' value=0}
            {/if}
        </small>

        {if $user->getPrivs() eq USER::AUTH_SUPERUSER}
            <div class="btn-group" style="padding-left: 20px;">
                <a class="btn btn-mini have-tooltip-below" href="{genUrl controller='virtual-interface' action='edit' id=$vi->getId()}" title="Edit"><i class="icon-pencil"></i></a>
            </div>
        {/if}

    </h3>

    {counter name=numphysports print=0 start=0}
    {foreach $vi->getPhysicalInterfaces() as $pi}

        {if $isLAG}
            <h5>
                Port {counter name=numphysports} of {$vi->getPhysicalInterfaces()|@count} in LAG
                {tmplinclude file='customer/overview-tabs/ports/physintstatus.phtml'}
            </h5>
        {/if}

        <table id="myDetailsTable">
            {if $multiIXP}
                <tr>
                    <td width="200"><strong>IXP:</strong></td>
                    <td width="200" id="value">
                        {$pi->getSwitchPort()->getSwitcher()->getInfrastructure()->getIXP()->getName()}
                    </td>
                    <td width="40"></td>
                    <td width="200"></td>
                    <td width="200" id="value"></td>
                </tr>
            {/if}
            <tr>
                <td width="200"><strong>Switch:</strong></td>
                <td width="200" id="value">{$pi->getSwitchPort()->getSwitcher()->getName()}</td>
                <td width="40"></td>
                <td width="200"><strong>Switch Port:</strong></td>
                <td width="200" id="value">{$pi->getSwitchPort()->getName()}</td>
            </tr>
            <tr>
                <td><strong>Speed:</strong></td>
                <td id="value">
                    {$pi->getSpeed()} Mbps {if $pi->getDuplex() neq 'full'}(HD){/if}
                </td>
                <td></td>
                {if $pi->getSwitchPort()->getSwitcher()->getMauSupported()}
                    <td><strong>Media:</strong></td>
                    <td id="value">{$pi->getSwitchPort()->getMauType()}</td>
                {else}
                    <td><strong>Duplex:</strong></td>
                    <td id="value">{$pi->getDuplex()}</td>
                {/if}
            </tr>
            {if $pi->getSwitchPort()->getSwitcher()->getCabinet()}
            <tr>
                <td><strong>Location:</strong></td>
                <td id="value">{$pi->getSwitchPort()->getSwitcher()->getCabinet()->getLocation()->getName()}</td>
                <td></td>
                <td><strong>Colo Cabinet ID:</strong></td>
                <td id="value">{$pi->getSwitchPort()->getSwitcher()->getCabinet()->getName()}</td>
            </tr>
            {/if}
            <tr>
                <td></td><td></td><td></td><td></td><td></td>
            </tr>
        </table>
    {foreachelse}
        <p>
            No physical interfaces defined.
            {if $user->getPrivs() eq USER::AUTH_SUPERUSER}
                <a href="{genUrl controller="physical-interface" action="add" vintid=$vi->getId()}">Add one...</a>
            {/if}
        </p>
    {/foreach}

    <br /><br />

    {foreach $vi->getVlanInterfaces() as $vli}
        {assign var='vlanid' value=$vli->getVlan()->getId()}

        {if $vli->getVlan()->getPrivate()}

            {if !isset( $pvlans )}
                {$pvlans = $cust->getPrivateVlanDetails()}
            {/if}

            <h4>
                &nbsp;&nbsp;&nbsp;Private VLAN Service
                <small>{$options.identity.orgname} Reference: #{$vli->getVlan()->getId()}</small>
            </h4>

            <table id="myDetailsTable">

            <tr>
                <td width="40"></td>
                <td width="80"><strong>Name</strong></td>
                <td width="150" id="value">{$vli->getVlan()->getName()}</td>
                {if $multiIXP}
                    <td width="20"></td>
                    <td width="60"><strong>IXP</strong></td>
                    <td width="150" id="value">{$vli->getVlan()->getInfrastructure()->getIXP()->getName()}</td>
                {/if}
                <td width="20"></td>
                <td width="80"><strong>Tag</strong></td>
                <td width="80" id="value">{$vli->getVlan()->getNumber()}</td>
                <td width="20"></td>
                <td width="150"><strong>Other Members:</strong></td>
                <td width="400" id="value">
                    {if count( $pvlans[ $vli->getVlan()->getId() ].members ) == 1}
                        <em>None - single member</em>
                    {else}
                        {foreach $pvlans[ $vli->getVlan()->getId() ].members as $m}
                            {$m->getAbbreviatedName()}<br />
                        {/foreach}
                    {/if}
                </td>
            </tr>

            </table>
            <br /><br />

        {else}
            <h4>&nbsp;&nbsp;&nbsp;{$vli->getVlan()->getName()}:</h4>

            <table id="myDetailsTable">

            <tr>
                <td width="40"></td>
                <td width="200"><strong>IPv6 Address:</strong></td>
                <td width="200" id="value">
                    {if $vli->getIpv6enabled() and $vli->getIpv6address()}
                        {$vli->getIPv6Address()->getAddress()}{if isset( $netinfo.$vlanid) }/{$netinfo.$vlanid.6.masklen}{/if}
                    {else}
                        IPv6 not enabled.
                    {/if}
                </td>
                <td width="40"></td>
                <td width="200"><strong>IPv4 Address:</strong></td>
                <td width="200" id="value">
                    {if $vli->getIpv4enabled() and $vli->getIpv4address()}
                        {$vli->getIPv4Address()->getAddress()}{if isset( $netinfo.$vlanid) }/{$netinfo.$vlanid.4.masklen}{/if}
                    {else}
                        IPv4 not enabled.
                    {/if}
                </td>
            </tr>

            <tr>
                <td></td><td></td><td></td><td></td><td></td><td></td>
            </tr>

            <tr>
                <td></td>
                <td><strong>Multicast Enabled:</strong></td>
                <td id="value">{if $vli->getMcastenabled()}Yes{else}No{/if}</td>
                <td></td>
                <td><strong></strong></td>
                <td id="value"></td>
            </tr>

            <tr>
                <td></td><td></td><td></td><td></td><td></td><td></td>
            </tr>

            <tr>
                <td></td>
                <td><strong>Route Server Client:</strong></td>
                <td id="value">{if $vli->getRsclient()}Yes{else}No{/if}</td>
                <td></td>
                {if $as112UiActive}
                    <td><strong>AS112 Client:</strong></td>
                    <td id="value">{if $vli->getAs112client()}Yes{else}No{/if}</td>
                {else}
                    <td></td>
                    <td></td>
                {/if}
            </tr>

            </table>

        {/if} {* end private VLAN? *}

    {foreachelse}
        {if $vi->getType() eq SWITCHPORT::TYPE_PEERING}
            <p>
                No VLAN interfaces defined.
                {if $user->getPrivs() eq USER::AUTH_SUPERUSER}
                    <a href="{genUrl controller="vlan-interface" action="add" vintid=$vi->getId()}">Add one...</a>
                {/if}
            </p>
        {/if}
    {/foreach}

    <br /><br />

    </div>
    <div class="span6">

        {if $isLAG}
            <br /><br />
            <div class="well">
                <h4>Aggregate Day Graph for LAG</h4>
                <br />
                <a href="{genUrl controller="statistics" action="member-drilldown" shortname=$cust->getShortname() category='bits' monitorindex="lag-viid-`$vi->getId()`"}">
                    {$pi = $vi->getPhysicalInterfaces()}
                    {$pi = $pi.0}
                    {genMrtgImgUrlTag ixp=$pi->getSwitchPort()->getSwitcher()->getInfrastructure()->getIXP()->getId() shortname=$cust->getShortname() monitorindex="lag-viid-`$vi->getId()`"}
                </a>
            </div>
        {/if}

        {foreach $vi->getPhysicalInterfaces() as $pi}
            <br /><br />
            <div class="well">
                <h4>Day Graph for {$pi->getSwitchPort()->getSwitcher()->getName()} / {$pi->getSwitchPort()->getName()}</h4>
                <br />
                <a href="{genUrl controller="statistics" action="member-drilldown" shortname=$cust->getShortname() category='bits' monitorindex=$pi->getMonitorindex()}">
                    {genMrtgImgUrlTag ixp=$pi->getSwitchPort()->getSwitcher()->getInfrastructure()->getIXP()->getId() shortname=$cust->getShortname() monitorindex=$pi->getMonitorindex()}
                </a>
            </div>
        {/foreach}
    </div>
</div>
