{tmplinclude file="header.phtml"}

{if $user->getPrivs() eq 3}
    <ul class="breadcrumb">
        <li>
            <a href="{genUrl}">Home</a> <span class="divider">/</span>
        </li>
        <li class="active">
            <a href="{genUrl controller=$controller action=$action}">My Profile</a>
        </li>
    </ul>
{else}
    <div class="page-content">
        <div class="page-header">
            <h1>User Profile</h1>
        </div>
{/if}

{OSS_Message}

<p>
This is your IXP Manager user profile where you can change your contact preferences and password.
</p>

<div class="row-fluid">
    <div class="span6">
        
        <h3>Change Your Password</h3>
        <br />
        {$passwordForm}
        
        {if isset( $customerNotesForm ) }
            <h3>Customer Notes</h3>
            <br />
            {$customerNotesForm}
        {else}
            {tmplinclude file="profile/mailing-list.phtml"}
        {/if}
        
    </div>
    <div class="span6">
     
        <h3>Change Your Profile</h3>
        <br />
        {$profileForm}
        
        {if isset( $customerNotesForm ) }
            {tmplinclude file="profile/mailing-list.phtml"}
        {/if}
        
    </div>
</div>

{if not isset( $user ) or $user->getPrivs() neq 3}
    </div>
{/if}

{tmplinclude file="footer.phtml"}
