{tmplinclude file="header.phtml"}

{if $user->getPrivs() eq 3}
    <ul class="breadcrumb">
        <li>
            <a href="{genUrl}">Home</a> <span class="divider">/</span>
        </li>
        <li class="active">
            <a href="{genUrl controller=$controller action=$action}">My Profile</a>
        </li>
    </ul>
{else}
    <div class="page-content">
        <div class="page-header">
            <h1>User Profile</h1>
        </div>
{/if}

{OSS_Message}

<p>
This is your IXP Manager user profile where you can change you contact preferences and password.
</p>

<div class="row-fluid">
    <div class="span6">
        
        <h3>Change Your Password</h3>
        <br />
        {$passwordForm}
        
        {if isset( $options.mailinglist.enabled ) and $options.mailinglist.enabled}
            <h3>Your Mailing List Subscriptions</h3>
            <p>
                <br />
                {$options.identity.orgname} operates the below mailing lists to help us interact with our
                members and for our members to interact with each other.
            </p>
            <p>
                There are also links below to the list archives - for which your username is
                {$user->getEmail()} and your password is the same as your IXP Manager password.
            </p>
            <p>
                The below are your subscriptions for <strong>{$user->getEmail()}</strong>.
            </p>
            <br />
            <form action="{genUrl controller="profile" action="update-mailing-lists"}" method="post" class="form">
            <fieldset>

                {foreach $options.mailinglists as $name => $ml}

	            {if $user->getCustomer()->getType() neq CUSTOMER::TYPE_ASSOCIATE or ( isset( $ml.associates ) and $ml.associates )}

                        <div class="control-group">
                            <label class="checkbox">
                                <input type="checkbox" name="ml_{$name}" value="1" {if $mlsubs.$name}checked="checked"{/if}>
                                    <strong>{$ml.name}</strong> - {$ml.desc}
                                    ({if $ml.email}{mailto address=$ml.email} - {/if}<a href="{$ml.archive}">archives</a>)
                            </label>
                        </div>
                    {/if}

                {/foreach}
            
                <div class="form-actions">
                    <input type="submit" class="btn btn-primary" value="Update My Subscriptions" id="submit" name="submit">
                </div>
            
            </fieldset>
            </form>
        {/if}
        
    </div>
    <div class="span6">
     
        <h3>Change Your Profile</h3>
        <br />
        {$profileForm}
        
    </div>
</div>

{if not isset( $user ) or $user->getPrivs() neq 3}
    </div>
{/if}

{tmplinclude file="footer.phtml"}
