
{if count( $cust->getContacts() )}

    <table class="table">
        <thead>
            <th>Name</th>
            <th>Email</th>
            <th>Phone</th>
            <th>Mobile</th>
            <th><a class="btn btn-mini" href="{genUrl controller='contact' action="add" custid=$cust->getId()}"><i class="icon-plus"></i> Add new...</a></th>        </thead>
        <tbody>
            {foreach $cust->getContacts() as $c}
                <tr>
                    <td>{$c->getName()}</td>
                    <td>{$c->getEmail()}</td>
                    <td>{$c->getPhone()}</td>
                    <td>{$c->getMobile()}</td>
                    <td>
                        <div class="btn-group">
                            <a class="btn btn-mini" href="{genUrl controller='contact' action="edit" id=$c->getId()}"><i class="icon-pencil"></i></a>
                            <a class="btn btn-mini" id="cont-list-delete-{$c->getId()}" href="{genUrl controller='contact' action="delete" id=$c->getId()}"><i class="icon-trash"></i></a>
                        </div>
                    </td>
                </tr>
            {/foreach}
        </tbody>
    </table>
    <script type="text/javascript">
        $(document).ready(function() {

            $( 'a[id|="cont-list-delete"]' ).off('click').on( 'click', function( event ){

                event.preventDefault();
                url = $(this).attr("href");

                bootbox.dialog( "Are you sure you want to delete this contact? Related user also will be deleted.", [{
                    "label": "Cancel",
                    "class": "btn-primary"
                },
                {
                    "label": "Delete",
                    "class": "btn-danger",
                    "callback": function() { document.location.href = url; }
                }]);

            });
        });
    </script>

{else}

    <p style="padding-left: 40px;">
        No contacts found.
        <a href="{genUrl controller='contact' action="add" custid=$cust->getId()}">Add a new contact...</a>
    </p>

{/if}

