
{if count( $cust->getContacts() )}

    <table class="table">
        <thead>
            <th>Name</th>
            <th>Email</th>
            <th>Phone</th>
            <th>Role(s)</th>
            <th><a class="btn btn-mini" href="{genUrl controller='contact' action="add" custid=$cust->getId() cid=$cust->getId()}"><i class="icon-plus"></i> Add new...</a></th>        </thead>
        <tbody>
            {foreach $cust->getContacts() as $c}
                <tr>
                    <td>{$c->getName()}</td>
                    <td>{$c->getEmail()}</td>
                    <td>{$c->getPhone()}{if $c->getPhone() and $c->getMobile()} / {/if}{$c->getMobile()}</td>
                    <td>
                        {foreach $c->getGroups() as $group}
                            {if $group->getType() eq 'ROLE'}
                                <span class="label label-info">{$group->getName()}</span>
                            {/if}
                        {/foreach}
                    </td>
                    <td>
                        <div class="btn-group">
                            <a class="btn btn-mini" href="{genUrl controller='contact' action="edit" id=$c->getId() cid=$cust->getId()}"><i class="icon-pencil"></i></a>
                            <a class="btn btn-mini" id="cont-list-delete-{$c->getId()}" data-hasuser="{if $c->getUser()}1{else}0{/if}"
                                    href="{genUrl controller='contact' action="delete" id=$c->getId()}">
                                <i class="icon-trash"></i>
                            </a>
                            {if $c->getUser()}
                                <a class="btn btn-mini"
                                    {if $c->getUser()->getDisabled()}disabled="disabled" onclick="return( false );"{/if}
                                    href="{genUrl controller='auth' action="switch-user" id=$c->getUser()->getId()}" rel="tooltip" title="Log in as this user...">
                                        <i class="icon-user"></i>
                                </a>
                            {/if}
                        </div>
                    </td>
                </tr>
            {/foreach}
        </tbody>
    </table>
    <script>{tmplinclude file="customer/js/overview/contacts.js"}</script>
{else}

    <p style="padding-left: 40px;">
        No contacts found.
        <a href="{genUrl controller='contact' action="add" custid=$cust->getId()}">Add a new contact...</a>
    </p>

{/if}

