
{if count( $cust->getContacts() )}

    <table class="table">
        <thead>
            <th>Name</th>
            <th>Email</th>
            <th>Phone</th>
            <th>Mobile</th>
            <th><a class="btn btn-mini" href="{genUrl controller='contact' action="add" custid=$cust->getId()}"><i class="icon-plus"></i> Add new...</a></th>        </thead>
        <tbody>
            {foreach $cust->getContacts() as $c}
                <tr>
                    <td>{$c->getName()}</td>
                    <td>{$c->getEmail()}</td>
                    <td>{$c->getPhone()}</td>
                    <td>{$c->getMobile()}</td>
                    <td>
                        <div class="btn-group">
                            <a class="btn btn-mini" href="{genUrl controller='contact' action="edit" id=$c->getId()}"><i class="icon-pencil"></i></a>
                            <a class="btn btn-mini" onclick="return confirm( 'Are you sure you want to delete this user?' );" href="{genUrl controller='contact' action="delete" id=$c->getId()}"><i class="icon-trash"></i></a>
                        </div>
                    </td>
                </tr>
            {/foreach}
        </tbody>
    </table>


{else}

    <p style="padding-left: 40px;">
        No contacts found.
        <a href="{genUrl controller='contact' action="add" custid=$cust->getId()}">Add a new contact...</a>
    </p>

{/if}
