<table class="table">
    <thead>
        <th>Name</th>
        <th>Patch Panel</th>
        <th>State</th>
    </thead>
    <tbody>
        {foreach $crossConnects as $patchPanelPort}
        <tr>
            <td>
                {$patchPanelPort->getName()}
            </td>
            <td>
                <a href="{genUrl controller='patchPanel' action="view" id=$patchPanelPort->getPatchPanel()->getId()}">
                    {$patchPanelPort->getPatchPanel()->getId()} {$patchPanelPort->getPatchPanel()->getName()}
                </a>
            </td>
            <td>
                {$patchPanelPort->resolveStates()}
            </td>
        </tr>
        {/foreach}
    </tbody>
</table>