
<table class="table">
    <thead>
        <th>Prefix</th>
        <th>Protocol</th>
        <th>Timestamp</th>
        <th>In IRRDB?</th>
        <th>Origin AS</th>
    </thead>
    <tbody>
        {foreach $cust->getRSPrefixes() as $p}
            <tr>
                <td>{$p->getPrefix()}</td>
                <td>IPv{$p->getProtocol()}</td>
                <td>{$p->getTimestamp()->format( 'Y-m-d H:i:s' )}</td>
                <td>{if $p->getIrrdb()}Yes{else}No{/if}</td>
                <td>{$p->getRsOrigin()|asnumber}</td>
            </tr>
        {/foreach}
    </tbody>
</table>
