
{if count( $cust->getUsers() )}

    <table class="table">
        <thead>
            <th>Username</th>
            <th>Email</th>
            <th>Last Login</th>
            <th>Last Login From</th>
            <th>
            </th>
        </thead>
        <tbody>
            {foreach $cust->getUsers() as $u}
                <tr>
                    <td>
                        <a href="{genUrl controller="contact" action="edit" id=$u->getContact()->getId() cid=$u->getCustomer()->getId()}">
                            {$u->getUsername()}
                        </a>
                    </td>
                    <td>{$u->getEmail()}</td>
                    <td>
                        {if $u->getPreference( 'auth.last_login_at' )}
                            {$u->getPreference( 'auth.last_login_at' )|date_format:"%Y-%m-%d %H:%M:%S"}
                            <a class="btn btn-mini have-tooltip" title="History" href="{genUrl controller='login-history' action="list" uid=$u->getId() limit=1}">
                                <i class="icon-time"></i>
                            </a>
                        {else}
                            <em>Never</em>
                        {/if}
                    </td>
                    <td>
                        {if $u->getPreference( 'auth.last_login_from' )}
                            {$u->getPreference( 'auth.last_login_from' )}
                        {/if}
                    </td>
                    <td>
                        {if count( $u->getLastLogins() ) > 0}
                            <div class="btn-group">
                                <a class="btn btn-mini have-tooltip" title="History" href="{genUrl controller='login-history' action="list" uid=$u->getId()}"><i class="icon-time"></i></a>
                            </div>
                        {/if}
                    </td>
                </tr>
            {/foreach}
        </tbody>
    </table>
    <script>{tmplinclude file="customer/js/overview/users.js"}</script>
{else}

    <p style="padding-left: 40px;">
        No users found.<br><br>
        Users can be added by creating / editing contacts and giving the contact login privileges.
    </p>

{/if}
