
<table class="table {if not count( $custNotes )}hide{/if}" id="co-notes-table">
    <thead>
        <th>Title</th>
        {if $user->getPrivs() eq USER::AUTH_SUPERUSER}
            <th>Visibility</th>
        {/if}
        <th>Updated</th>
        <th>
            <div class="btn-group">
                {if $user->getPrivs() eq USER::AUTH_SUPERUSER}
                    <button id="co-notes-add-btn" class="btn btn-small"><i class="icon-plus"></i></button>
                    <button id="co-cust-notify-{$cust->getId()}"  class="btn btn-small {if isset( $co_notify_all ) && $co_notify_all}active{/if}"><i class="icon-eye-open"></i></button>
                {/if}
            </div>
        </th>
    </thead>
    <tbody id="co-notes-table-tbody">
        {foreach $custNotes as $n}
            {if $user->getPrivs() eq USER::AUTH_SUPERUSER or not $n->getPrivate()}
                <tr id="co-notes-table-row-{$n->getId()}">
                    <td id="co-notes-table-row-title-{$n->getId()}">
                        {if ( not $notesLastRead or $n->getUpdated()->format( 'U' ) > $notesLastRead )
                                and ( not $notesReadUpto or $n->getUpdated()->format( 'U' ) > $notesReadUpto )}
                            <span class="label label-success">
                                {if $n->getUpdated() eq $n->getCreated()}
                                    NEW
                                {else}
                                    UPDATED
                                {/if}
                            </span>
                        {/if}
                        {$n->getTitle()}
                    </td>
    
                    {if $user->getPrivs() eq USER::AUTH_SUPERUSER}
                        <td id="co-notes-table-row-public-{$n->getId()}">
                            <span class="label label-{if not $n->getPrivate()}success">PUBLIC{else}important">PRIVATE{/if}</span>
                        </td>
                    {/if}
                    <td id="co-notes-table-row-updated-{$n->getId()}">
                        {$n->getUpdated()->format( 'Y-m-d H:i' ) }
                    </td>
                    <td>
                        <div class="btn-group">
                            {if $user->getPrivs() eq USER::AUTH_SUPERUSER}
                                <button id="co-notes-notify-{$n->getId()}"  class="btn btn-small {if isset( $co_notify[$n->getId()] ) && $co_notify[$n->getId()]}active{/if}"><i class="icon-eye-open"></i></button>
                            {/if}
                            <button id="co-notes-view-{$n->getId()}"  class="btn btn-small"><i class="icon-zoom-in"></i></button>
                            {if $user->getPrivs() eq USER::AUTH_SUPERUSER}
                                <button id="co-notes-edit-{$n->getId()}"  class="btn btn-small"><i class="icon-pencil"></i></button>
                                <button id="co-notes-trash-{$n->getId()}" class="btn btn-small"><i class="icon-trash"></i></button>
                            {/if}
                        </div>
                    </td>
                </tr>
            {/if}
        {/foreach}
    </tbody>
</table>

{if not count( $custNotes )}
    <p id="co-notes-no-notes-msg">
        There are no notes for this customer. <a href="#" id="co-notes-add-link">Add one...</a>
    </p>
{/if}
    
<script>{tmplinclude file="customer/js/overview/notes.js"}</script>

{if $user->getPrivs() eq USER::AUTH_SUPERUSER}

<div class="modal hide" id="co-notes-dialog">
    <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h3><span id="co-notes-dialog-title-action">Add a</span> Note for {$cust->getName()}</h3>
    </div>
    <div class="modal-body">
        <div class="alert hide" id="co-notes-warning">
            <strong>Warning!</strong> Your customer will be able to read this note!
        </div>
        <form class="form" id="co-notes-form">
            <input type="text" placeholder="Title" class="span12" name="title" id="co-notes-ftitle" />
            <br />
            <textarea rows="6" class="span12" name="note" id="co-notes-fnote"></textarea>
            <br />
            <label class="checkbox">
                <input type="checkbox" name="public" id="co-notes-fpublic" value="makePublic" />
                Make note visible to customer
            </label>
            <input type="hidden" name="custid" value="{$cust->getId()}" />
            <input type="hidden" id="notes-dialog-noteid" name="noteid" value="0" />
        </form>
    </div>
    <div class="modal-footer">
        <span class="pull-left"  id="co-notes-dialog-date"></span>
        <a href="#" data-dismiss="modal" class="btn">Cancel</a>
        <a href="#" id="co-notes-fadd" class="btn btn-primary">Add</a>
    </div>
</div>

{/if}

<div class="modal hide" data-keyboard="true" id="co-notes-view-dialog">
    <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h3><span id="co-notes-view-dialog-title"></span></h3>
    </div>
    <div class="modal-body">
        <div id="co-notes-view-dialog-note"></div>
    </div>
    <div class="modal-footer">
        <span class="pull-left"  id="co-notes-view-dialog-date"></span>
        <a href="#" data-dismiss="modal" class="btn">Close</a>
    </div>
</div>
