
{if $hasAggregateGraph}
    <div class="row-fluid">

        <div class="well">
             <h3>Aggregate Traffic Statistics</h3>

             <p>
                 <br />
                 <a href="{genUrl controller='statistics' action='member-drilldown' monitorindex='aggregate' category='bits' shortname=$cust->getShortname()}">
                     {genMrtgImgUrlTag shortname=$cust->getShortname() category='bits' monitorindex='aggregate'}
                 </a>
             </p>
         </div>

     </div>
{/if}


<table class="table">
    <tbody>

        <tr>
            <td><strong>Corporate Site</strong></td>
            <td><a href="{$cust->getCorpwww()}">{$cust->getCorpwww()}</a></td>
            <td><strong>Peering Email</strong></td>
            <td>{if $cust->getpeeringemail()}{mailto address=$cust->getpeeringemail()}{/if}</td>
        </tr>
        <tr>
            <td><strong>Status</strong></td>
            <td>{CUSTOMER::$CUST_STATUS_TEXT[$cust->getStatus()]}</td>
            <td><strong>Joined</strong></td>
            <td>{$cust->getDatejoin()->format( 'Y-m-d' )}</td>
        </tr>
        <tr>
            <td><strong>Type</strong></td>
            <td>{CUSTOMER::$CUST_TYPES_TEXT[$cust->getType()]}</td>
            <td><strong>Left</strong></td>
            <td>{if $cust->hasLeft()}{$cust->getDateleave()->format( 'Y-m-d' )}{/if}</td>
        </tr>
        {if $cust->getType() neq CUSTOMER::TYPE_ASSOCIATE}
            <tr>
                <td><strong>Peering Policy</strong></td>
                <td>{$cust->getPeeringpolicy()}</td>
                <td><strong>ASN</strong></td>
                <td>{$cust->getAutsys()|asnumber}</td>
            </tr>
            <tr>
                <td><strong>PeeringDB</strong></td>
                <td>
                    {if $cust->getPeeringDb()}
                        <em>
                            <a onclick="$.fn.colorbox({ldelim}href:&quot;{$options.peeringdb.url|replace:'%ID%':$cust->getPeeringDb()}&quot;, iframe: true, width: &quot;75%&quot;, height: &quot;75%&quot;{rdelim});return false;">Click to view...</a>
                        </em>
                    {/if}
                </td>
                <td><strong>AS-SET</strong></td>
                <td>{$cust->getPeeringmacro()}</td>
            </tr>
            <tr>
                <td><strong>IRRDB</strong></td>
                <td>{if $cust->getIRRDB()}{$cust->getIRRDB()->getSource()}{/if}</td>
                <td><strong>Max Prefixes</strong></td>
                <td>
                    {$cust->getMaxprefixes()}
                    {if $cust->getVirtualInterfaces()|@count}
                        ({foreach $cust->getVirtualInterfaces() as $vi}
                            {foreach $vi->getVlanInterfaces() as $vli}
                                {$vli->getMaxbgpprefix()}{if not ( $vi@last and $vli@last )}, {/if}
                            {/foreach}
                        {/foreach})
                    {/if}
                </td>
            </tr>
        {/if}
        <tr>
            <td>{if $cust->getType() neq CUSTOMER::TYPE_ASSOCIATE}<strong>NOC Details</strong>{/if}</td>
            <td>
                {if $cust->getType() neq CUSTOMER::TYPE_ASSOCIATE}
                    {if $cust->getNochours()}    {$cust->getNochours()}<br />    {/if}
                    {if $cust->getNocemail()}    {mailto address=$cust->getNocemail()}<br />{/if}
                    {if $cust->getNocwww()}      {$cust->getNocwww()}<br />      {/if}
                    {if $cust->getNocphone()}    {$cust->getNocphone()}<br />    {/if}
                    {if $cust->getNoc24hphone()} {$cust->getNoc24hphone()} (24h) {/if}
                {/if}
            </td>
            <td></td>
            <td>
            </td>
        </tr>

    </tbody>
</table>


