
{if $cust->getType() neq CUSTOMER::TYPE_ASSOCIATE and not $cust->hasLeft()}

    <div class="row-fluid">

        <div class="well">
             <h3>Aggregate Traffic Statistics</h3>

             <p>
                 <br />
                 <a href="{genUrl controller='statistics' action='member-drilldown' monitorindex='aggregate' category='bits' shortname=$cust->getShortname()}">
                     {genMrtgImgUrlTag shortname=$cust->getShortname() category='bits' monitorindex='aggregate'}
                 </a>
             </p>
         </div>

     </div>
{/if}


<table class="table">
    <tbody>

        <tr>
            <td><strong>Corportate Site</strong></td>
            <td><a href="{$cust->getCorpwww()}">{$cust->getCorpwww()}</a></td>
            <td><strong>Peering Email</strong></td>
            <td>{mailto address=$cust->getpeeringemail()}</td>
        </tr>
        <tr>
            <td><strong>Status</strong></td>
            <td>{CUSTOMER::$CUST_STATUS_TEXT[$cust->getStatus()]}</td>
            <td><strong>Joined</strong></td>
            <td>{$cust->getDatejoin()->format( 'Y-m-d' )}</td>
        </tr>
        <tr>
            <td><strong>Type</strong></td>
            <td>{CUSTOMER::$CUST_TYPES_TEXT[$cust->getType()]}</td>
            <td><strong>Left</strong></td>
            <td>{if $cust->hasLeft()}{$cust->getDateleave()->format( 'Y-m-d' )}{/if}</td>
        </tr>
        {if $cust->getType() neq CUSTOMER::TYPE_ASSOCIATE}
            <tr>
                <td><strong>Peering Policy</strong></td>
                <td>{$cust->getPeeringpolicy()}</td>
                <td><strong>ASN</strong></td>
                <td>{$cust->getAutsys()|asnumber} {if $cust->getPeeringmacro()}({$cust->getPeeringmacro()}){else}<em>(no AS-SET)</em>{/if}</td>
            </tr>
            <tr>
                <td><strong>IRRDB</strong></td>
                <td>{$cust->getIRRDB()->getSource()}</td>
                <td><strong>Max Prefixes</strong></td>
                <td>
                    {$cust->getMaxprefixes()}
                    {if $cust->getVirtualInterfaces()|@count}
                        ({foreach $cust->getVirtualInterfaces() as $vi}
                            {foreach $vi->getVlanInterfaces() as $vli}
                                {$vli->getMaxbgpprefix()}{if not ( $vi@last and $vli@last )}, {/if}
                            {/foreach}
                        {/foreach})
                    {/if}
                </td>
            </tr>
        {/if}
        <tr>
            <td>{if $cust->getType() neq CUSTOMER::TYPE_ASSOCIATE}<strong>NOC Details</strong>{/if}</td>
            <td>
                {if $cust->getType() neq CUSTOMER::TYPE_ASSOCIATE}
                    {if $cust->getNochours()}    {$cust->getNochours()}<br />    {/if}
                    {if $cust->getNocemail()}    {mailto address=$cust->getNocemail()}<br />{/if}
                    {if $cust->getNocwww()}      {$cust->getNocwww()}<br />      {/if}
                    {if $cust->getNocphone()}    {$cust->getNocphone()}<br />    {/if}
                    {if $cust->getNoc24hphone()} {$cust->getNoc24hphone()} (24h) {/if}
                {/if}
            </td>
            <td><strong>Billing Details</strong></td>
            <td>
                {if $cust->getBillingContact()}    {$cust->getBillingContact()}<br />     {/if}
                {if $cust->getBillingAddress1()}   {$cust->getBillingAddress1()}<br />    {/if}
                {if $cust->getBillingAddress2()}   {$cust->getBillingAddress2()}<br />    {/if}
                {if $cust->getBillingCity()}       {$cust->getBillingCity()}<br />        {/if}
                {if $cust->getBillingCountry()}    {$cust->getBillingCountry()}<br />     {/if}
            </td>
        </tr>

    </tbody>
</table>


