
{if $hasAggregateGraph and not $multiIXP}
    <div class="row-fluid">

        <div class="well">
             <h3>Aggregate Traffic Statistics</h3>

             <p>
                 <br />
                 <a href="{genUrl controller='statistics' action='member-drilldown' monitorindex='aggregate' category='bits' shortname=$cust->getShortname()}">
                     {genMrtgImgUrlTag shortname=$cust->getShortname() category='bits' monitorindex='aggregate'}
                 </a>
             </p>
         </div>

     </div>
{/if}


<table class="table">
    <tbody>
        <tr>
            <td><strong>Abbreviated Name</strong></td>
            <td>{$cust->getAbbreviatedName()}</td>
            <td colspan="2">
                {if not $cust->isTypeAssociate()}
                    <span class="label label-{if $rsclient}success{else}important{/if}">RS Client</span>
                    {if $as112UiActive}
                        &nbsp;&nbsp;&nbsp;
                        <span class="label label-{if $as112client}success{else}important{/if}">AS112</span>
                    {/if}
                {/if}
            </td>
        </tr>
        <tr>
            <td><strong>Corporate Site</strong></td>
            <td><a href="{$cust->getCorpwww()}">{$cust->getCorpwww()}</a></td>
            {if $cust->isTypeAssociate()}
                <td colspan="2"></td>
            {else}
                <td><strong>Peering Email</strong></td>
                <td>{if $cust->getpeeringemail()}{mailto address=$cust->getpeeringemail()}{/if}</td>
            {/if}
        </tr>
        <tr>
            <td><strong>Status</strong></td>
            <td>{CUSTOMER::$CUST_STATUS_TEXT[$cust->getStatus()]}</td>
            <td><strong>Joined</strong></td>
            <td>{if $cust->getDatejoin()}{$cust->getDatejoin()->format( 'Y-m-d' )}{/if}</td>
        </tr>
        <tr>
            <td><strong>Type</strong></td>
            <td>{CUSTOMER::$CUST_TYPES_TEXT[$cust->getType()]}</td>
            <td><strong>Left</strong></td>
            <td>{if $cust->hasLeft()}{$cust->getDateleave()->format( 'Y-m-d' )}{/if}</td>
        </tr>
        {if not $cust->isTypeAssociate()}
            <tr>
                <td><strong>Peering Policy</strong></td>
                <td>{$cust->getPeeringpolicy()}</td>
                <td><strong>ASN</strong></td>
                <td>{$cust->getAutsys()|asnumber}</td>
            </tr>
            <tr>
                <td><strong>PeeringDB</strong></td>
                <td>
                    {if $cust->getPeeringDb()}
                        <em>
                            <a onclick="$.colorbox({ldelim}href:&quot;{$options.peeringdb.url|replace:'%ID%':$cust->getPeeringDb()|replace:'%ASN%':$cust->getAutsys()}&quot;, iframe: true, width: &quot;75%&quot;, height: &quot;75%&quot;{rdelim});return false;">Click to view...</a>
                        </em>
                    {/if}
                </td>
                <td><strong>IPv4 AS-SET</strong></td>
                <td>{$cust->getPeeringmacro()}</td>
            </tr>
            <tr>
                <td><strong>IRRDB</strong></td>
                <td>{if $cust->getIRRDB()}{$cust->getIRRDB()->getSource()}{/if}</td>
                <td><strong>IPv6 AS-SET</strong></td>
                <td>{$cust->getPeeringmacrov6()}</td>
            </tr>
        {/if}
        <tr>
            <td>{if not $cust->isTypeAssociate()}<strong>NOC Details</strong>{/if}</td>
            <td>
                {if not $cust->isTypeAssociate()}
                    {if $cust->getNochours()}    {$cust->getNochours()}<br />    {/if}
                    {if $cust->getNocemail()}    {mailto address=$cust->getNocemail()}<br />{/if}
                    {if $cust->getNocwww()}      <a href="{$cust->getNocwww()}">{$cust->getNocwww()}</a><br />      {/if}
                    {if $cust->getNocphone()}    {$cust->getNocphone()}<br />    {/if}
                    {if $cust->getNoc24hphone()} {$cust->getNoc24hphone()} (24h) {/if}
                {/if}
            </td>
            <td><strong>Max Prefixes</strong></td>
            <td>
                {$cust->getMaxprefixes()}
                {if $cust->getVirtualInterfaces()|@count}
                    ({foreach $cust->getVirtualInterfaces() as $vi}
                        {foreach $vi->getVlanInterfaces() as $vli}
                            {$vli->getMaxbgpprefix()}{if not ( $vi@last and $vli@last )}, {/if}
                        {/foreach}
                    {/foreach})
                {/if}
            </td>
        </tr>

    </tbody>
</table>
