
<table class="table">
    <thead>
        <th>VLAN</th>
        <th>Tag</th>
        <th>Location</th>
        <th>Switch</th>
        <th>Port</th>
        <th>Speed</th>
        <th>Other Members</th>
    </thead>
    <tbody>

    {if !isset( $pvlans )}
        {$pvlans = $cust->getPrivateVlanDetails()}
    {/if}

        {foreach $pvlans as $vlanid => $pv}
            {foreach $pv.vlis as $vli}
            <tr>
                <td>{$vli->getVlan()->getName()}</td>
                <td>{$vli->getVlan()->getNumber()}</td>
                {$pis = $vli->getVirtualInterface()->getPhysicalInterfaces()}
                <td>{$pis.0->getSwitchPort()->getSwitcher()->getCabinet()->getLocation()->getName()}</td>
                <td>{$pis.0->getSwitchPort()->getSwitcher()->getName()}</td>
                {foreach $vli->getVirtualInterface()->getPhysicalInterfaces() as $p}
                    <td>{$p->getSwitchPort()->getName()}<br /></td>
                    <td>{$p->getSpeed()}/{$p->getDuplex()}<br /></td>
                {/foreach}
                <td>
                    {$others = 0}
                    {foreach $pv.members as $m}
                        {if $m->getId() neq $cust->getId()}
                            <a href="{genUrl controller="customer" action="overview" id=$m->getId()}">{$m->getAbbreviatedName()}</a><br />
                            {$others = 1}
                        {/if}
                    {/foreach}
                    {if not $others}
                        <em>None - single member</em>
                    {/if}
                </td>
            </tr>
            {/foreach}
        {/foreach}
    </tbody>
</table>

