<div class="row-fluid">
    <div class="span12 tabbable">
        <ul class="nav nav-pills">
            <li class="active">
                <a href="#peering" data-toggle="tab">Peering Ports</a>
            </li>
            <li>
                <a href="#reseller" data-toggle="tab">Reseller Uplink Ports</a>
            </li>
            <li>
                <a href="#fanout" data-toggle="tab">Fanout Ports</a>
            </li>
        </ul>

        <div class="tab-content">
            <div class="tab-pane active" id="peering">
                {tmplinclude file="customer/overview-tabs/ports/peering.phtml"}
            </div>

            <div class="tab-pane" id="reseller">
                {tmplinclude file="customer/overview-tabs/ports/reseller.phtml"}
            </div>

            <div class="tab-pane" id="fanout">
                {tmplinclude file="customer/overview-tabs/ports/fanout.phtml"}
            </div>
        </div>

    </div>
</div>
