
{if count( $cust->getUsers() )}

    <table class="table">
        <thead>
            <th>Username</th>
            <th>Type</th>
            <th>Email</th>
            <th>Mobile</th>
            <th><a class="btn btn-mini" href="{genUrl controller='user' action="add" custid=$cust->getId()}"><i class="icon-plus"></i> Add new...</a></th>
        </thead>
        <tbody>
            {foreach $cust->getUsers() as $u}
                <tr>
                    <td>{$u->getUsername()}</td>
                    <td>{USER::$PRIVILEGES[$u->getPrivs()]}</td>
                    <td>{$u->getEmail()}</td>
                    <td>{$u->getAuthorisedMobile()}</td>
                    <td>
                        <div class="btn-group">
                            <a class="btn btn-mini" href="{genUrl controller='user' action="edit" id=$u->getId()}"><i class="icon-pencil"></i></a>
                            <a class="btn btn-mini" onclick="return confirm( 'Are you sure you want to delete this user?' );" href="{genUrl controller='user' action="delete" id=$u->getId()}"><i class="icon-trash"></i></a>
                            <a class="btn btn-mini" href="{genUrl controller='auth' action="switch-user" id=$u->getId()}" rel="tooltip" title="Log in as this user..."><i class="icon-user"></i></a>
                        </div>
                    </td>
                </tr>
            {/foreach}
        </tbody>
    </table>

{else}

    <p style="padding-left: 40px;">
        No users found.
        <a href="{genUrl controller='user' action="add" custid=$cust->getId()}">Add a new user...</a>
    </p>

{/if}
