
{if count( $cust->getUsers() )}

    <table class="table">
        <thead>
            <th>Username</th>
            <th>Type</th>
            <th>Email</th>
            <th>Last Login</th>
            <th>
                {*
                    The correct way of doing this is via contacts. Leaving it here may be confusing...
                    <a class="btn btn-mini" href="{genUrl controller='contact' action="add" user=1 custid=$cust->getId() cid=$cust->getId()}"><i class="icon-plus"></i> Add new...</a>
                *}
            </th>
        </thead>
        <tbody>
            {foreach $cust->getUsers() as $u}
                <tr>
                    <td>{$u->getUsername()}</td>
                    <td>{USER::$PRIVILEGES[$u->getPrivs()]}</td>
                    <td>{$u->getEmail()}</td>
                    <td>
                        {if $u->getPreference( 'auth.last_login_at' )}
                            {$u->getPreference( 'auth.last_login_at' )|date_format:"%Y-%m-%d %H:%M:%S"}
                        {else}
                            <em>Never</em>
                        {/if}
                    </td>
                    <td>
                        <div class="btn-group">
                            <a class="btn btn-mini" href="{genUrl controller='contact' action="edit" uid=$u->getId() cid=$cust->getId()}"><i class="icon-pencil"></i></a>
                            <a class="btn btn-mini" id="usr-list-delete-{$u->getId()}"
                                    href="{genUrl controller='contact' action="delete" id=$u->getContact()->getId()}">
                                <i class="icon-trash"></i>
                            </a>
                            <a class="btn btn-mini"
                                {if $u->getDisabled()}disabled="disabled" onclick="return( false );"{/if}
                                href="{genUrl controller='auth' action="switch-user" id=$u->getId()}" rel="tooltip" title="Log in as this user...">
                                    <i class="icon-user"></i>
                            </a>
                        </div>
                    </td>
                </tr>
            {/foreach}
        </tbody>
    </table>
    <script>{tmplinclude file="customer/js/overview/users.js"}</script>
{else}

    <p style="padding-left: 40px;">
        No users found.<br><br>
        Users can be added by creating / editing contacts and giving the contact login privileges.
    </p>

{/if}
