<li class="dropdown">
    <a href="#" class="dropdown-toggle" data-toggle="dropdown">Documentation<b class="caret"></b></a>
    <ul class="dropdown-menu">
        <li>
            <a href="{genUrl controller="static" action="fees"}">Fees and Charges</a>
        </li>
        <li>
            <a href="{genUrl controller="static" action="housing"}">Equipment Housing</a>
        </li>
        <li>
            <a href="{genUrl controller="static" action="misc-benefits"}">Miscellaneous Benefits</a>
        </li>
        <li>
            <a href="{genUrl controller="static" action="switches"}">Connecting Switches</a>
        </li>
        <li>
            <a href="{genUrl controller="static" action="port-security"}">Port Security Policies</a>
        </li>
        <li>
            <a href="{genUrl controller="static" action="as112"}">AS112 Service</a>
        </li>
        <li>
            <a href="{genUrl controller="static" action="route-servers"}">Route Servers</a>
        </li>
        
        <li class="divider"></li>
        <li>
            <a href="{genUrl controller="index" action="about"}">About IXP Manager</a>
        </li>
    </ul>
</li>

