<li class="dropdown">
    <a href="#" class="dropdown-toggle" data-toggle="dropdown">Documentation<b class="caret"></b></a>
    <ul class="dropdown-menu">
        <li>
            <a href="https://www.inex.ie/meetings/">Members' Meetings</a>
        </li>
        <li>
            <a href="https://www.inex.ie/become-a-member/inex-price-list/">Fees and Charges</a>
        </li>
        <li>
            <a href="{route( 'content', [ 'priv' => 1, 'page' => 'misc-benefits' ] )}">Miscellaneous Benefits</a>
        </li>

        <li class="divider"></li>

        <li>
            <a href="{route( 'content', [ 'priv' => 1, 'page' => 'switches' ] )}">Connecting Switches</a>
        </li>
        <li>
            <a href="{route( 'content', [ 'priv' => 1, 'page' => 'port-security' ] )}">Port Security Policies</a>
        </li>
        <li>
            <a href="https://www.inex.ie/technical/as112-service/" target="_blank">AS112 Service</a>
        </li>
        <li>
            <a href="https://www.inex.ie/technical/route-servers/" target="_blank">Route Servers</a>
        </li>
        
        <li class="divider"></li>
        <li>
            <a href="http://www.ixpmanager.org/" target="_blank">About</a>
        </li>
    </ul>
</li>
