{* Override this file (via skinning) to add customer staff links for ADMINs *}

<li class="dropdown">
    <a href="#" class="dropdown-toggle" data-toggle="dropdown">Staff Links<b class="caret"></b></a>
                                
    <ul class="dropdown-menu">
        <li> <a href="https://www.inex.ie/cacti/">Cacti</a> </li>
        <li> <a href="https://www.inex.ie/cvsweb/">CVSweb / RANCID</a> </li>
        <li> <a href="{genUrl controller="auth" action="cms-login"}">Drupal</a> </li>
        <li> <a href="https://www.inex.ie/flyspray/">Flyspray</a> </li>
        <li> <a href="https://www.inex.ie/ipplan/">IP Plan</a> </li>
        <li> <a href="https://www.inex.ie/lg/">Looking Glass</a> </li>
        <li> <a href="https://www.inex.ie/nagios/">Nagios</a> </li>
        <li> <a href="https://www.inex.ie/members/smokeping/smokeping.cgi/">Smokeping</a> </li>
        <li> <a href="https://www.inex.ie/sugarcrm/">Sugar CRM</a> </li>
        <li> <a href="https://www.inex.ie/trac/">Trac Documentation</a> </li>
        <li> <a href="https://www.inex.ie/webmail/">Webmail</a> </li>
    </ul>
</li>

