{tmplinclude file="header.phtml"}

<ul class="breadcrumb">
    <li>
        <a href="{genUrl}">Home</a> <span class="divider">/</span>
    </li>
    <li>
        <a href="{genUrl controller="meeting"}">Meetings</a> <span class="divider">/</span>
    </li>
    <li class="active">
        Compose Email Notification
    </li>
</ul>

{OSS_Message}

<h3>Composing Email for Members' Meeting of {$meeting->getDate()->format( 'Y-m-d H:i' )}</h3>

<p>
The form below allows you to enter some <strong>pre-amble</strong> to the email detailing
the members' meeting. If you are unsure of how this works, enter some text and send the mail
which, by default, only sends it to yourself.
</p>

<p>
When you're happy with the result, you can send it to <code>members@inex.ie</code>.
</p>

<div id="email_dialog">

<form method="post" action="{genUrl controller="meeting" action='compose' id=$meeting->getId()}">

<table border="0">

<tr>
	<td align="right">
	    <strong>From:</strong>&nbsp;&nbsp;
	</td>
	<td>
	    <input id="from" type="text" name="from"
	        value="{if isset( $from )}{$from}{else}{$user->getEmail()}{/if}" maxlength="254" size="60"
	    />
	</td>
</tr>

<tr>
    <td align="right">
        <strong>To:</strong>&nbsp;&nbsp;
    </td>
    <td>
        <input id="to" type="text" name="to"
            value="{if isset( $to )}{$to}{else}{$user->getEmail()}{/if}" maxlength="254" size="60"
        />
    </td>
</tr>

<tr>
    <td align="right">
        <strong>BCC:</strong>&nbsp;&nbsp;
    </td>
    <td>
        <input id="bcc" type="text" name="bcc"
            value="{if isset( $bcc )}{$bcc}{else}{$user->getEmail()}{/if}" maxlength="254" size="60"
        />
    </td>
</tr>

<tr>
    <td align="right">
        <strong>Subject:</strong>&nbsp;&nbsp;
    </td>
    <td>
        <input id="subject" type="text" name="subject"
            value="{if isset( $subject )}{$subject}{else}INEX Members' Meeting - {$meeting->getDate()->format( 'Y-m-d H:i' )}{/if}"
            maxlength="254" size="60"
        />
    </td>
</tr>

<tr>
    <td align="center" colspan="2">
        <textarea id="message" name="body" cols="78" rows="15" class="span9 offset3">{if isset( $body )}{$body}{/if}</textarea>
    </td>
</tr>

<tr>
    <td align="right" colspan="2">
        <input type="submit" name="submit" value="Send" class="btn btn-success" />
    </td>
</tr>

</table>

<input type="hidden" name="send" value="1" />

</form>

</div>

<link rel="stylesheet" href="{genUrl}/js/jwysiwyg/jquery.wysiwyg.css" type="text/css" />
<script type="text/javascript" src="{genUrl}/js/jwysiwyg/jquery.wysiwyg.js"></script>

<script type="text/javascript">
    $(function()
    {ldelim}
        $( '#message' ).wysiwyg();
    {rdelim});
</script>



{tmplinclude file="footer.phtml"}
