
<div class="meetings">

    {foreach from=$entries item=e}
    
    <a name="{$e->getId()}"></a>
    <div class="meeting">
    
        <div class="meeting title">
            <h1>{$e->getTitle()} &ndash; {$e->getDate()->format( 'l, F jS, Y' )}</h1>
            <h4>
                In {if $e->getVenueUrl() neq ''}<a href="{$e->getVenueUrl()}">{$e->getVenue()}</a>{else}{$e->getVenue()}{/if} at {$e->getTime()->format( 'H:i' )}
                {if not $simple and $e->getVenueUrl() neq ''}
                    &nbsp;&nbsp;<a href="{$e->getVenueUrl()}" target="_blank">
                        <img width="16" height="16" border="0" alt="[LINK]"
                            title="Visit venue site" src="{genUrl}/images/joomla-admin/menu/globe1.png" />
                    </a>
                {/if}
            </h4>
        </div>
    
        <div class="meeting content">{$e->getBeforeText()}</div>
    
        <div class="meetingitem">
    
            <dl>
            
                {assign var='inOtherContent' value=0}
            
                {foreach $e->getMeetingItems() as $id => $mi}
            
                {if $mi->getOtherContent() and not $inOtherContent}
                    </dl>
            
                    <p>
                    Other meeting content also includes:
                    </p>
            
                    <dl>
            
                    {assign var='inOtherContent' value=1}
                {/if}
            
                <dt>
            
            		<div class="meetingitem title">
            
            		    <div class="meetingitem title icons">
            		    {if not $simple}
                            {if $mi->getPresentation() neq ''}
                                <a href="{genUrl controller='meeting-item' action='get-presentation' id=$mi->getId()}">
                                    <img src="{genUrl}/images/22x22/presentation.png" width="22" height="22"
                                            alt="[VIDEO]" class="meetingitem title icons" />
                                </a>
                            {/if}
                            {if $mi->getVideoUrl() neq ''}
                                <a href="{$mi->getVideoUrl()}">
                                    <img src="{genUrl}/images/22x22/video.png" width="22" height="22"
                                            alt="[VIDEO]" class="meetingitem title icons" />
                                </a>
                            {/if}
                        {/if}
            		    </div>
            
            		    <h1>
            		        {$mi->getTitle()} &ndash;
            
            		        {if not $simple and $mi->getEmail() neq ''}
            		            {mailto address=$mi->getEmail() encode='javascript' text=$mi->getName()}
            		        {else}
            		            {$mi->getName()}
            		        {/if}
            		    </h1>
            
            		    <h4>
            		        {if $mi->getRole() neq ''}{$mi->getRole()}, {/if}
            		        {if $mi->getCompanyUrl() neq ''}
            		            <a href="{$mi->getCompanyUrl()}">{$mi->getCompany()}</a>
            		        {else}
                		        {$mi->getCompany()}
                		    {/if}
            		    </h4>
            		</div>
            
                </dt>
            
                <dd>
                    {$mi->getSummary()}
                </dd>
            
                {/foreach}
            
            </dl>
    
        </div>
    
        <div class="meeting content">{$e->getAfterText()}</div>

	{if not $simple and $smarty.now < $e->getDate()->format( 'U' ) and $user->getPrivs() eq 1}
        <p class="alert alert-info">
            <strong>
		Please RSVP for this meeting: 
                <a href="mailto:{$options.meeting.rsvp_to_email}">{$options.meeting.rsvp_to_email}</a>
            </strong>
        </p>
        {/if}    
        {* if not $simple and $smarty.now < $e->getDate()->format( 'U' ) and $user->getPrivs() eq 1}
            <div class="meeting buttons" id="rsvp_div_{$e->getId()}">
        
                {if $user->getPreference( 'meeting.attending.'|cat:$e->getId() ) eq 'ATTENDING'
                        or $user->getPreference( 'meeting.attending.'|cat:$e->getId() ) eq 'NOT_ATTENDING'}
                    <p>
                    You have already RSVP'd for this meeting and told us that you will
                    {if $user->getPreference( 'meeting.attending.'|cat:$e->getId() ) eq 'NOT_ATTENDING'}not{/if}
                    be attending. Please email
                    {mailto text=$config.meeting.rsvp_to_name address=$config.meeting.rsvp_to_email}
                    directly to change this.
                    </p>
                {else}
                    <p>
                	    Please RSVP for this meeting:
            	        <button id="rsvp_attending_{$e->getId()}"     name="Attending" value="Attending" type="button">Attending</button>
            	        <button id="rsvp_not_attending_{$e->getId()}" name="Not Attending" value="Not Attending" type="button">Not Attending</button>
        	        </p>
        	    {/if}
            </div>
        
            <script type="text/javascript">{tmplinclude file="meeting/js/core.js"}</script>
            
        {/if *}

    </div>
        
    {/foreach}

</div>
