<div class="btn-group">
    <a class="btn btn-mini have-tooltip-below" href="{genUrl controller=$controller action='view' id=$row.id}" title="Preview"><i class="icon-eye-open"></i></a>
    <a class="btn btn-mini have-tooltip-below" href="{genUrl controller=$controller action='edit' id=$row.id}" title="Edit"><i class="icon-pencil"></i></a>
    <a class="btn btn-mini have-tooltip-below" id='list-delete-{$row.id}' href="{genUrl controller=$controller action='delete' id=$row.id}" title="Delete"><i class="icon-trash"></i></a>
    <a class="btn btn-mini dropdown-toggle" data-toggle="dropdown" href="#">
        More...
        <span class="caret"></span>
    </a>
    <ul class="dropdown-menu">
        <li>
            <a href="{genUrl controller='meeting-item' action='list' mid=$row.id}">See Presentations...</a>
        </li>
        <li>
            <a href="{genUrl controller='meeting' action='compose' id=$row.id}">Compose Email...</a>
        </li>
    </ul>
</div>
