{tmplinclude file="header.phtml"}

{if $user->getPrivs() eq USER::AUTH_SUPERUSER}
    <ul class="breadcrumb">
        <li>
            <a href="{genUrl}">Home</a> <span class="divider">/</span>
        </li>
        <li>
            <a href="{genUrl controller='meeting' action='list'}">Meetings</a> <span class="divider">/</span>
        </li>
        <li class="active">
            Member View
        </li>
    </ul>
{else}
    <div class="page-content">
    
        <div class="page-header">
            <h1>Meetings</h1>
        </div>
{/if}

{OSS_Message}

<div class="meetings_index">
    <p>
        <form name="meeting_jumpto" class="form">
            <strong>Jump to:</strong>&nbsp;
        
            <select
                name="meetings_index"
                onChange="window.location.href=meeting_jumpto.meetings_index.options[selectedIndex].value">
            >
        
                <option></option>
                {foreach from=$entries item=e}
                    <option value="#{$e->getId()}">{$e->getDate()->format( "Y-m-d" )}</option>
                {/foreach}
        
            </select>
        </form>
    </p>
</div>



{tmplinclude file='meeting/core.phtml'}


{if $user->getPrivs() neq USER::AUTH_SUPERUSER}
</div>
{/if}

{tmplinclude file="footer.phtml"}
