<form action="{$element->getAction()}" method="{$element->getMethod()}"
    enctype="{$element->getAttrib('enctype')}"
   id="{$element->getId()}" {if $element->getName() != ''}name="{$element->getName()}"{/if}
   {if $element->getAttrib('target')}target="{$element->getAttrib('target')}"{/if}
   class="form">

{$element->switchid}
{$element->deftype}
{$element->numfirst}
{$element->numports}

<div class="control-group">
    <label class="control-label required" for="prefix"><tt>printf</tt> Format:</label>

    <div class="controls">
        <input name="prefix" id="prefix" type="text" maxlength="30" class="span3" style="display: inline-block;" />
        <span id="popover_prefix" rel="popover" class="label"
            data-content="<p>A sequence of ports will be created based on a standard <tt>printf</tt> format.</p>
                    <p><br />For example.</p>
                    <p><br />&nbsp;&nbsp;<code>GigabitEthernet%02d</code></p>"
            data-original-title="<tt>printf</tt> Format"
        >?</span>
    </div>
</div>

<div class="control-group">
    <label class="control-label" for="genbutton"></label>
    <div class="controls">
        <button class="btn btn-primary" id="genbutton">Generate</button>
    </div>
</div>

<div class="hide" id="gendiv"></div>

<div class="hide" id="div-spansubmit">
    <div class="form-actions">
        {$element->submit}
        {$element->cancel}
    </div>
</div>

</form>

<script type="text/javascript">

$( "#spansubmit" ).hide();

$( "#genbutton" ).click( function( event ) {

    event.preventDefault();

    $( "#gendiv" ).hide();
    $( "#div-spansubmit" ).hide();
    $( "#gendiv" ).html( "" );

    var numports = parseInt( $( "#numports" ).val() );
    var numfirst = parseInt( $( "#numfirst" ).val() );

    if( isNaN( numports ) || numports <= 0 )
    {
        bootbox.alert( "Invalid number of ports!" );
        return false;
    }

    if( isNaN( numfirst ) || numfirst < 0 )
    {
        bootbox.alert( "Invalid number for first port!" );
        return false;
    }

    var c = "<h3>The following ports will be created:</h3>\n\n<table>\n";

    for( var i = numfirst; i < ( numfirst + numports ); i++ )
    {
        c += "<tr>\n    <td><strong>Name:</strong>&nbsp;<input name=\"np_name"
            + ( i - numfirst ) + "\" value=\""
            + sprintf( trim( $( "#prefix" ).val() ), i ) + "\" /></td>\n"
            + "\n    <td>&nbsp;&nbsp;&nbsp;&nbsp;<strong>Type:</strong>&nbsp;"
            + "<select id=\"np_type"+ ( i - numfirst ) + "\" name=\"np_type"
            + ( i - numfirst ) + "\"></select>"
            + "</td>\n</tr>\n";
    }

    c += "</table>\n";

    $( "#gendiv" ).html( c );
    $( "#gendiv" ).show();
    $( "#div-spansubmit" ).show();

    for( var i = 0; i < numports; i++ )
    {
        selid = 'np_type' + i;
        document.getElementById( selid ).innerHTML = document.getElementById( 'deftype' ).innerHTML;

        $( '#' + selid ).val( $( '#deftype' ).val() );
    }
});

</script>







