{tmplinclude file="header.phtml" pageTitle="IXP Manager :: Member Dashboard"}

<ul class="breadcrumb">
    <li>
        <a href="{genUrl}">Home</a> <span class="divider">/</span>
    </li>
    <li>
        <a href="{genUrl controller=$controller action="list"}">{$feParams->pagetitle}</a> <span class="divider">/</span>
    </li>
    <li class="active">
        Last Logins
    </li>
</ul>
        
<table id="ixpDataTable" cellpadding="0" cellspacing="0" border="0" class="table table-striped table-bordered" style="display: none;">
    <thead>
    <tr>
        <th>Username</th>
        <th>Email</th>
        <th>Customer</th>
        <th>Last Login</th>
    </tr>
    </thead>

    <tbody>

    {foreach from=$last item=l}
    <tr>
        <td>
            {$l.username}
        </td>
        <td>
            {$l.email}
        </td>
        <td>
            <a href="{genUrl controller="customer" action="overview" id=$l.cust_id}">
                {$l.cust_name}
            </a>
        </td>
        <td>
            {$l.lastlogin|date_format:"%Y-%m-%d %H:%M:%S"}
            <a class="btn btn-mini have-tooltip" title="History" href="{genUrl controller='login-history' action="list" uid=$l.user_id limit=1}"><i class="icon-time"></i></a>
        </td>
    </tr>
    {/foreach}
    </tbody>
</table>

<script type="text/javascript">
	oTable = $('#ixpDataTable').dataTable({
		"aaSorting": [[ 3, 'desc' ]],
		"sDom": "<'row-fluid'<'span6'l><'span6'f>r>t<'row-fluid'<'span6'i><'span6'p>>",
		"sPaginationType": "bootstrap",
		"iDisplayLength": 12,
		"aoColumns": [
            { "sType": "string" },
            { "sType": "string" },
            { "sType": "html" },
            { "sType": "string" }
        ]
	});

	$('#ixpDataTable').show();
</script>


{tmplinclude file="footer.phtml"}
