<div class="btn-group">
    <a class="btn btn-mini have-tooltip-below" href="{genUrl module=$module controller=$controller action='view' id=$row.id}" title="Preview"><i class="icon-eye-open"></i></a>
    <a class="btn btn-mini have-tooltip-below" href="{genUrl module=$module controller='contact' action='edit' uid=$row.id}" title="Edit"><i class="icon-pencil"></i></a>
    <a class="btn btn-mini have-tooltip-below" id='list-delete-{$row.id}' href="{genUrl controller='contact' action='delete' id=$row.contactid}" title="Delete"><i class="icon-trash"></i></a>
    <a class="btn btn-mini dropdown-toggle" data-toggle="dropdown" href="#"><span class="caret"></span></a>
    <ul class="dropdown-menu">
        <li> <a href="{genUrl module=$module controller=$controller action='welcome-email' id=$row.id}">Resend welcome email</a> </li>
        <li> <a href="{genUrl controller='login-history' action="list" uid=$row.id limit=1}">Login History</a> </li>
        {if $user->getPrivs() eq 3}<li> <a href="{genUrl controller="auth" action="switch-user" id=$row.id}">Switch to...</a> </li>{/if}
    </ul>
</div>
