<html>
<head>
    <title>Welcome to {$options.identity.sitename}</title>
</head>
<body>
<h2>{$options.identity.sitename} - Your Access Details</h2>

<p>
To whom it may concern,
</p>

{if isset( $resend ) and $resend}
    <p>
        <strong>This email is being sent to you because either you requested a reminder of
        your account details or an administrator thought it appropriate to send you a
        reminder.</strong>
    </p>
{else}
    <p>
    A new user account has been created for you on the {$options.identity.sitename}.
    </p>
{/if}
    
<p>
You can login to your account using the following details:
</p>

<table border="0">
<tr>
    <td width="50"></td>
    <td align="right"><strong>URL:</strong></td>
    <td width="20"></td>
    <td align="left"><a href="{$options.identity.url}">{$options.identity.url}</a></td>
</tr>
<tr>
    <td></td>
    <td align="right"><strong>Username:</strong></td>
    <td></td>
    <td align="left"><code>{$newuser->getUsername()}</code></td>
</tr>
<tr>
    <td></td>
    <td align="right"><strong>Password:</strong></td>
    <td></td>
    <td align="left"><em>(see below)</em></td>
</tr>
</table>

<p>
Once logged in, you will have access to a number of features including:
</p>

<ul>
    <li> ---- COMPLETE YOURSELF VIA SKIN ---- </li>
</ul>

<p>
If you require any assistance, please contact {$options.identity.name} on
<a href="mailto:{$options.identity.email}">{$options.identity.email}</a>.
</p>


<h2>Getting Your Password</h2>

<p>
To get your new password (or reset it), please use the <em>lost password</em> procedure by visiting
the following link and entering your username as above:
</p>

<blockquote>
    <a href="{genUrl controller="auth" action="lost-password"}">{genUrl controller="auth" action="lost-password"}</a>
</blockquote>



<p>
Thanks and kind regards,
</p>

<p>
{$options.identity.name}<br />
<a href="mailto:{$options.identity.email}">{$options.identity.email}</a>
</p>


</body>
</html>
