<html>
<head>
    <title>Welcome to {$options.identity.sitename}</title>
</head>
<body>
<h2>{$options.identity.sitename} - Your Access Details</h2>

<p>
To whom it may concern,
</p>

<p>
A new user account has been created for you on the {$options.identity.sitename}.
</p>

<p>
You can login to it using the following details:
</p>

<table border="0">
<tr>
    <td width="50"></td>
    <td align="right"><strong>URL:</strong></td>
    <td width="20"></td>
    <td align="left"><a href="{$optoins.identity.url}">{$options.identity.url}</a></td>
</tr>
<tr>
    <td></td>
    <td align="right"><strong>Username:</strong></td>
    <td></td>
    <td align="left"><code>{$newuser->getUsername()}</code></td>
</tr>
<tr>
    <td></td>
    <td align="right"><strong>Password:</strong></td>
    <td></td>
    <td align="left"><em>(see below)</em></td>
</tr>
</table>

<p>
Once logged in, you will have access to a number of features including:
</p>

<ul>
    <li> list of IXP members and peering contact details; </li>
    <li> the peering manager tool; </li>
    <li> your port and member to member traffic graphs; </li>
    <li> ability to view and edit your company details; </li>
    <li> your port configuration details; </li>
    <li> the peering matrix; </li>
    <li> route server, AS112 and other service information. </li>
</ul>

<p>
If you require any assistance, please contact {$options.identity.name} on
<a href="mailto:{$options.identity.email}">{$options.identity.email}</a>.
</p>


<h2>Getting Your Password</h2>

<p>
To get your new password, please use the <em>lost password</em> procedure by visiting
the following link and entering your username as above:
</p>

<blockquote>
    <a href="{genUrl controller="auth" action="lost-password"}">{genUrl controller="auth" action="lost-password"}</a>
</blockquote>



<p>
Thanks and kind regards,
</p>

<p>
{$options.identity.name}<br />
<a href="mailto:{$options.identity.email}">{$options.identity.email}</a>
</p>


</body>
</html>
