
<footer>

    <p>
        IXP Manager V{$smarty.const.APPLICATION_VERSION}
        &nbsp;&nbsp;|&nbsp;&nbsp;
        Copyright &copy; 2010 - {$smarty.now|date_format:'%Y'} Internet Neutral Exchange Association Company Limited By Guarantee. - <a href="http://www.inex.ie/">http://www.inex.ie/</a>
        &nbsp;|&nbsp;
        {mailto address=$options.identity.email encode='javascript' text="Contact Us"}
    </p>

    <p>
        Licensed under GPL v2.0.
        &nbsp;|&nbsp;
        This Program is provided AS IS, without warranty.
        &nbsp;|&nbsp;
        {assign var="ENDTIME" value=microtime(1)}
        {assign var="RUNNINGTIME" value="`$ENDTIME-$smarty.const.APPLICATION_STARTTIME`"}
        Generated in {$RUNNINGTIME|string_format:"%0.3f"} seconds
    </p>
    
    <p>
        Keep up with
        <span class="label label-info">
            <a class="aplain" href="http://www.inex.ie/">INEX</a>
        </span>
        &nbsp;|&nbsp;
        Get the source at
        <span class="label label-info">
            <a class="aplain" href="https://github.com/inex/IXP-Manager">GitHub</a>
        </span>
        &nbsp;|&nbsp;
        We're
        <span class="label label-info">
            <a class="aplain" href="http://www.ipv6ready.ie/">IPv6 Ready</a>
        </span>
        &nbsp;Are you?
        &nbsp;|&nbsp;
        Join the
        <span class="label label-info">
            <a class="aplain" href="http://www.linkedin.com/groups?gid=1853398">LinkedIn Group</a>
        </span>
    </p>
</footer>