<li class="dropdown">
    <a href="#" class="dropdown-toggle" data-toggle="dropdown">Documentation<b class="caret"></b></a>
    <ul class="dropdown-menu">
        <li>
            <a href="{genUrl controller="static" action="as112"}">AS112 Service</a>
        </li>

        {* PLEASE LEAVE THIS SOMEWHERE!  IT'S ONLY FAIR INEX GETS SOME CREDIT :D *}
        <li class="divider"></li>
        <li>
            <a href="{genUrl controller="index" action="about"}">About</a>
        </li>
    </ul>
</li>
