
{foreach $locations as $name => $switches}

define hostgroup {
        hostgroup_name          INEX-Switches-{$name}
        alias                   INEX Switches at {$name}
        members                 {$switches}

}

{/foreach}


define hostgroup {
        hostgroup_name          INEX-Production-Switches
        alias                   INEX Production Switches (all)
        members                 {$all}

}


define hostgroup {
        hostgroup_name          INEX-Switches-Brocade
        alias                   INEX Brocade Switches
        members                 {$vendor_brocade}

}


#define hostgroup {
#        hostgroup_name          INEX-Switches-Cisco
#        alias                   INEX Cisco Switches
#        members                 {$vendor_cisco}
#
#}


define hostgroup {
        hostgroup_name          INEX-Switches-MRV
        alias                   INEX MRV Switches
        members                 {$vendor_mrv}

}



define service{ldelim}
        use                             inex-production-switch-service
        hostgroup_name                  INEX-Switches-Brocade
        service_description             Chassis
        check_command                   check_foundry_chassis!fjvrGzHqr
{rdelim}

#define service  {ldelim}
#        use                             inex-production-switch-service
#        service_description             Temperature
#        hostgroup_name                  INEX-Switches-Cisco
#        check_command                   check_cisco_temperature!fjvrGzHqr!32!38
#{rdelim}



define service{ldelim}
        use                             inex-production-switch-service
        hostgroup_name                  INEX-Production-Switches
        service_description             ping - IPv4
        check_command                   check_ping_ipv4!10!100.0,10%!200.0,20%
{rdelim}

define service  {ldelim}
        use                             inex-production-switch-service
        service_description             SSH
        hostgroup_name                  INEX-Production-Switches
        check_command                   check_ssh
{rdelim}

