<li class="pull-right" style="margin-top: -6px;"> 
<div class="btn-toolbar" style="display: inline;">

    <div class="btn-group" id="vlan-btn-group">
        <a class="btn btn-mini dropdown-toggle" data-toggle="dropdown" id="meeting-dd">
            <span id="meeting-dd-text">{if isset( $mid ) and $mid}{$meetings.$mid}{else}Limit to meeting...{/if}</span>
            <span class="caret"></span>
        </a>
        <ul id="meeting-dd-ul" class="dropdown-menu pull-right">
            {foreach $meetings as $mid => $mname}
                <li> <a id="meeting-{$mid}" href="{genUrl controller='meeting-item' action='list' mid=$mid}">{$mname}</a> </li>
            {/foreach}
        </ul>
    </div>

    <div class="btn-group">
        <a class="btn btn-mini pull-right" href="{genUrl controller=$controller action="add"}"><i class="icon-plus"></i></a>
    </div>
</div>
</li>

