<li class="pull-right"> 
    <div class="btn-group">
        <a class="btn btn-mini dropdown-toggle" data-toggle="dropdown" href="#"><i class="icon-plus"></i>&nbsp;<span class="caret"></span></a>
        <ul class="dropdown-menu pull-right">
            {foreach $options.netinfo.property as $name => $data}
                <li>
                    <a href="{genUrl controller=$controller action='add'}" id="add-info-{$name}" data-name="{$name}">Add {$data.name}</a>
                </li>
            {/foreach}
        </ul>
    </div>
</li>

