
<div class="btn-group">
    {if !isset( $feParams->readonly ) or !$feParams->readonly}
        <a class="btn btn-mini have-tooltip-below" href="{genUrl module=$module controller=$controller action='edit' id=$row.id vlid=$Vlan->getId()}" title="Edit"><i class="icon-pencil"></i></a>
        <a class="btn btn-mini have-tooltip-below" id='list-delete-{$row.id}' href="{genUrl module=$module controller=$controller action='delete' id=$row.id vlid=$Vlan->getId()}" title="Delete"><i class="icon-trash"></i></a>
    {/if}
</div>