<div id="add-property" class="modal hide fade">
    <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h3>Add New Porperty <span id="property-name"></span></h3>
    </div>
    <div class="modal-body" id="add-mbody">
        <div id="add-mbody-inner" style="z-index: 100; position: fixed;">
            <form id="form-add-property" method="post" action="{genUrl controller=$controller action=add vlid=$Vlan->getId()}" class="form-horizontal">
                <div class="control-group">
                    <label class="control-label" for="protocol">Protocol</label>
                    <div class="controls">
                        <select name="protocol" class="chzn-select" chzn-fix-width="1">
                            {foreach $Protocols as $idx => $protocol}
                                <option value="{$idx}">{$protocol}</option>
                            {/foreach}
                        </select>
                    </div>
                </div>
                <div id="property-fields">
                </div>
            </form>
        </div>
    </div>
    <div class="modal-footer">
        <span id="add_dialog_cancel" class="btn">Cancel</span>
        <span id="add_dialog_save" class="btn btn-primary">Add</span>
    </div>
</div>


<script type="text/javascript">

    var dialog = null;

    $( document ).ready( function(){
        $( 'a[id|="add-info"]' ).on("click", openAddDialog );
    });

    function openAddDialog( event ){
        event.preventDefault();
        var name = $( event.target ).attr( 'data-name' );

        $( "#property-name" ).html( getPropertyName( name ) );
        $( "#property-fields" ).html( getPropertyFields( name ) );

        $(".chzn-select").each( function( index ){
            $( this ).chosen();
            ossChosenFixWidth( $( this ) );
        });

        $( '#add_dialog_save' ).off( 'click' ).on( 'click', function(){
            $( '#form-add-property' ).trigger( 'submit' );
        });

        $( '#add_dialog_cancel' ).off( 'click' ).on( 'click', function(){
            dialog.modal('hide');
        });

        ossCloseOssMessages();
        $( '#add-mbody' ).height( 200 );
        $( '#add-property' ).off( "shown").on( "shown", function(){
            var add = 0;
            if( isSingleton( name ) )
            {
                ossAddMessage( "If this is exists for this protocol it will be overwritten", "info", true );
                add = 25;
            }
            $( '#add-mbody' ).height( $( '#add-mbody-inner' ).height() + add );
        });

        dialog = $( '#add-property' ).modal( {
                backdrop: true,
                keyboard: true,
                show: true
        });

        
    };

    function isSingleton( id )
    {
        return getFieldsData()[id]['singleton'];
    }

    function getPropertyName( id )
    {
        return getFieldsData()[id]['name'];
    }

    function getPropertyFields( id )
    {
        return getFieldsData()[id]['fields'];
    }

    function getFieldsData(){
        return {
        {foreach $options.netinfo.property as $name => $data}
            {$name} : {
            name: '{$data.name}',
            singleton: {if !isset( $data.singleton ) || $data.singleton }true{else}false{/if},
            fields: '{if isset( $data.properties)}\
                {foreach $data.properties as $property => $propData }\
                    {if is_array( $propData ) }\
                        <div class="control-group">\
                            <label class="control-label" for="{$name}_{$property}">{$propData.name}</label>\
                            <div class="controls">\
                                <select id="{$name}_{$property}" name="{$name}%dot%{$property}" class="chzn-select" chzn-fix-width="1">\
                                    {foreach $propData.values as $propVal}\
                                        <option value="{$propVal}">{$propVal}</option>\
                                    {/foreach}\
                                </select>\
                            </div>\
                        </div>\
                    {else}\
                        <div class="control-group">\
                            <label class="control-label" for="{$name}_{$property}">{$propData}</label>\
                            <div class="controls">\
                                <input type="text" name="{$name}%dot%{$property}" id="{$name}_{$property}">\
                            </div>\
                        </div>\
                    {/if}\
                {/foreach}\
            {else}\
                <div class="control-group">\
                    <label class="control-label" for="{$name}">{$data.name}</label>\
                    <div class="controls">\
                        <input type="text" name="{$name}" id="{$name}">\
                    </div>\
                </div>\
            {/if}\
            '},
        {/foreach}
        }
    };
</script>