
<footer>

    <p>
        IXP Manager V{$smarty.const.APPLICATION_VERSION}
        &nbsp;&nbsp;|&nbsp;&nbsp;
        Copyright &copy; 2010 - {$smarty.now|date_format:'%Y'} Internet Neutral Exchange Association Company Limited By Guarantee. - <a href="http://www.inex.ie/">http://www.inex.ie/</a>
        &nbsp;|&nbsp;
        <a href="{genUrl controller="static" action="support"}">Contact Us</a>
    </p>

    <p>
        Licensed under GPL v2.0.
        &nbsp;|&nbsp;
        This Program is provided AS IS, without warranty.
        &nbsp;|&nbsp;
        {assign var="ENDTIME" value=microtime(1)}
        {assign var="RUNNINGTIME" value="`$ENDTIME-$smarty.const.APPLICATION_STARTTIME`"}
        Generated in {$RUNNINGTIME|string_format:"%0.3f"} seconds
    </p>
    

    {if $smarty.const.APPLICATION_ENV != 'production' and ( not isset( $hasIdentity ) or !$hasIdentity)}
        <p>
            <strong>
                THE IXP IS RUNNING IN NON-PRODUCTION MODE AND INFORMATION CAN BE LEAKED VIA DEBUGGING
                UTILITIES. ENSURE HTACCESS IS IN PLACE.
            </strong>
        </p>
    {/if}

</footer>
