
{if isset( $hasIdentity ) and $hasIdentity and isset( $user ) and $user->getPrivs() eq 3}

        </div><!--/span-->
    </div><!--/row-->
{/if}

{if $smarty.const.MAINTENANCE_MODE}
    <div class="alert alert-info" style="text-align: center;">
        <strong>*** MAINTENANCE MODE ENABLED ***</strong>
    </div>
{/if}

{tmplinclude file='footer-content.phtml'}

{if !isset( $mode ) or $mode neq 'fluid'}
    
    </div> <!-- </div class="container"> -->

{/if}

{if isset( $hasIdentity ) and $hasIdentity}
<script>
    $( ".chzn-select" ).chosen();

    {if isset( $user ) and $user->getPrivs() eq 3}
        $( "#menu-select-customer" ).chosen().change( function(){
            document.location.href = '{genUrl controller="customer" action="overview"}/id/' + $( "#menu-select-customer" ).val();
        });

        {if isset( $acust )}
            $( "#menu-select-customer" ).val( {$acust.id} );
            $( "#menu-select-customer" ).trigger( "liszt:updated" );
        {/if}
    {/if}
</script>
{/if}

</body>
</html>
