{if isset( $config.use_minified_js ) and $config.use_minified_js}
    <script type="text/javascript" src="{genUrl}/js/min.bundle-v26.js"></script>
{else}
    <script type="text/javascript" src="{genUrl}/js/200-jquery-1.8.1.js"></script>
    <script type="text/javascript" src="{genUrl}/js/210-jquery-ui-1.8.23.custom.js"></script>
    <script type="text/javascript" src="{genUrl}/js/220-jquery.dataTables-1.9.3.js"></script>
    <script type="text/javascript" src="{genUrl}/js/230-jquery-ui-position-1.8.13.js"></script>
    <script type="text/javascript" src="{genUrl}/js/231-jquery.contextMenu-1.5.24.js"></script>
    <script type="text/javascript" src="{genUrl}/js/240-jquery.json-2.3.js"></script>
    <script type="text/javascript" src="{genUrl}/js/245-jquery-cookie.js"></script>
    <script type="text/javascript" src="{genUrl}/js/250-jquery-colorbox-1.3.20.js"></script>
    <script type="text/javascript" src="{genUrl}/js/300-chosen.jquery.js"></script>
    <script type="text/javascript" src="{genUrl}/js/310-throbber.js"></script>
    <script type="text/javascript" src="{genUrl}/js/700-php.js"></script>
    <script type="text/javascript" src="{genUrl}/js/800-bootstrap-2.3.2.js"></script>
    <script type="text/javascript" src="{genUrl}/js/830-bootstrap-wysihtml5.js"></script>
    <script type="text/javascript" src="{genUrl}/js/890-bootbox.js"></script>
    <script type="text/javascript" src="{genUrl}/js/900-oss-framework.js"></script>
    <script type="text/javascript" src="{genUrl}/js/999-ixpmanager.js"></script>
{/if}
