{tmplinclude file="header-base.phtml"}

<div class="navbar navbar-inverse navbar-fixed-top">
    <div class="navbar-inner">
        <div class="{if isset( $hasIdentity ) and $hasIdentity and $user->getPrivs() eq 3}container-fluid{else}container{/if}">
             <a id="collapsed_menu" class="btn btn-navbar" data-target=".nav-collapse" data-toggle="collapse">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </a>
            <a class="brand" href="{genUrl}">
                {$options.identity.sitename}
            </a>
            {if isset( $hasIdentity ) and $hasIdentity}
                <div class="nav-collapse">
                     <ul class="nav">
                        {if $user->getPrivs() eq 1}
                            <li {if $controller eq "dashboard"}class="active"{/if}>
                                <a href="{genUrl}">Home</a>
                            </li>
                        {/if}
                        {if $user->getPrivs() neq 2}
                            <li class="dropdown {if $action eq 'switch-configuration' or $action eq 'members-details-list'}active{/if}">
                                <a href="#" class="dropdown-toggle" data-toggle="dropdown">Member Information <b class="caret"></b></a>
                                <ul class="dropdown-menu">
                                    <li>
                                        <a href="{route( 'customer@details')}">Member Details</a>
                                    </li>
                                    <li>
                                        <a href="{route( 'customer@associates')}">Associate Members</a>
                                    </li>
                                    <li>
                                        <a href="{route('switch@configuration')}">Switch Configuration</a>
                                    </li>
                                </ul>
                            </li>
                            <li class="dropdown {if $controller eq 'peering-manager' or $controller eq 'peering-matrix'}active{/if}">
                                <a href="#" class="dropdown-toggle" data-toggle="dropdown">Peering<b class="caret"></b></a>
                                <ul class="dropdown-menu">
                                    {if $user->getPrivs() eq 1 and $user->getCustomer()->getType() neq CUSTOMER::TYPE_ASSOCIATE}
                                        {if ixp_min_auth( config( 'ixp.peering-matrix.min-auth' ) ) and !config( 'ixp_fe.frontend.disabled.peering-manager' )}
                                            <li><a href="{genUrl controller="peering-manager"}">Peering Manager</a></li>
                                        {/if}
                                        {if !config( 'ixp_fe.frontend.disabled.rs-prefixes', false )}
                                            {if $user->getCustomer()->isRouteServerClient()}
                                                <li><a href="{route( 'rs-prefixes@view', [ 'cid' => $user->getCustomer()->getId() ] )}">Route Server Prefixes</a></li>
                                            {/if}
                                        {/if}
                                    {/if}
                                    {if not config('ixp_fe.frontend.disabled.lg' )}
                                        <li>
                                            <a href="{genUrl}/lg">Looking Glass</a>
                                        </li>
                                    {/if}
                                    {if !config( 'ixp_fe.frontend.disabled.peering-matrix' )}
                                        <li><a href="{route('peering-matrix@index')}">Peering Matrix</a></li>
                                    {/if}
                                </ul>
                            </li>

                            {* STATIC DOCUMENTATION LINKS - SPECIFIC TO INDIVIDUAL IXPS *}
                            {* Add a skinned file in views/_skins/xxx/header-documentation.phtml for your IXP to override the sample *}
                            {tmplinclude file="header-documentation.phtml"}

                            <li class="dropdown
                                    {if $controller eq 'statistics' or substr( $action, 0, 9 ) eq 'statistic' or $action eq 'traffic-stats' or $action eq 'trunk-graphs' or $action eq 'switch-graphs' or $controller eq 'weather-map'}active{/if}
                                     <?= !request()->is( 'statistics/*', 'weather-map/*' ) ?: 'active' ?>
                                ">
                                <a href="#" class="dropdown-toggle" data-toggle="dropdown">Statistics<b class="caret"></b></a>
                                <ul class="dropdown-menu">
                                    {if $user->getPrivs() eq USER::AUTH_CUSTUSER and not $user->getCustomer()->isTypeAssociate()}
                                        <li>
                                            <a href="{route( "statistics@member", ['id' => $user->getCustomer()->getId()] )}">My Statistics</a>
                                        </li>

                                        {if config('grapher.backends.sflow.enabled')}
                                            <li>
                                                <a href="{route( "statistics@p2p", ['cid' => $user->getCustomer()->getId()] )}">My Peer to Peer Traffic</a>
                                            </li>
                                        {/if}

                                        <li class="divider"></li>
                                    {/if}
                                    
                                    <li>
                                        <a href="{route( 'statistics/ixp' )}">Overall Peering Graphs</a>
                                    </li>
                                    <li>
                                        <a href="{route( 'statistics/infrastructure' )}">Infrastructure Graphs</a>
                                    </li>
                                    <li>
                                        <a href="{route( 'statistics/vlan' )}">VLAN / Per-Protocol Graphs</a>
                                    </li>
                                    <li>
                                        <a href="{route( 'statistics/trunk' )}">Inter-Switch / PoP Graphs</a>
                                    </li>
                                    <li>
                                        <a href="{route( 'statistics/switch' )}">Switch Aggregate Graphs</a>
                                    </li>
                                    {if is_array( config( 'ixp_tools.weathermap', false ) )}
                                        <li class="divider"></li>
                                        {foreach from=config( 'ixp_tools.weathermap' ) key=k item=w}
                                            <li>
                                                <a href="{route( 'weathermap', ['id' => {$k} ] ) }">{$w.menu}</a>
                                            </li>
                                        {/foreach}
                                    {/if}
                                </ul>
                            </li>
                        {/if}
                        <li>
                            <a href="{route( 'public-content', [ 'page' => 'support' ] )}">Support</a>
                        </li>
                        {if $user->getPrivs() eq USER::AUTH_SUPERUSER}
                            {tmplinclude file="staff-links.phtml"}
                        {/if}

                        {if $user->getPrivs() neq 3}
                            <li class="dropdown">
                                <a href="#" class="dropdown-toggle" data-toggle="dropdown">My Account<b class="caret"></b></a>
                                <ul class="dropdown-menu">
                                    <li>
                                        <a href="{route( 'profile@edit' )}">Profile</a>
                                    </li>
                                    {if $user->getPrivs() neq 3}
                                        <li>
                                            <a href="{route('api-key@list' )}">API Keys</a>
                                        </li>
                                    {/if}
                                    <li class="divider"></li>
                                    <li>
                                        <a href="{genUrl controller="auth" action="logout"}">Logout</a>
                                    </li>
                                </ul>
                            </li>
                        {/if}

                    </ul>
                    <ul class="nav pull-right">
                        {if $user->getPrivs() eq 3}
                            <form class="navbar-search pull-left">
                                <select data-placeholder="View a Customer..." id="menu-select-customer" type="select" name="id" class="chzn-select">
                                    <option></option>
                                    {foreach from=$customers key=k item=i}
                                        <option value="{$k}">{$i}</option>
                                    {/foreach}
                                </select>
                            </form>
                        {/if}

                        {if isset( $session->switched_user_from ) and $session->switched_user_from}
                            <li><a href="{genUrl controller="auth" action="switch-user-back"}">Switch Back</a></li>
                        {elseif $user->getPrivs() eq 3}
                            <li class="dropdown">
                                <a href="#" class="dropdown-toggle" data-toggle="dropdown">My Account<b class="caret"></b></a>
                                <ul class="dropdown-menu">
                                    <li>
                                        <a href="{genUrl controller="profile"}">Profile</a>
                                    </li>
                                    <li>
                                        <a href="{route('api-key@list' )}">API Keys</a>
                                    </li>
                                    <li class="divider"></li>
                                    <li>
                                        <a href="{route('customerNotes@unreadNotes')}">Unread Notes</a>
                                    </li>
                                    <li class="divider"></li>
                                    <li>
                                        <a href="{genUrl controller="auth" action="logout"}">Logout</a>
                                    </li>
                                </ul>
                            </li>
                        {else}
                            <li><a href="{genUrl controller="auth" action="logout"}">Logout</a></li>
                        {/if}
                    </ul>
                </div><!--/.nav-collapse -->
            {else}
                <div class="nav-collapse">
                    <ul class="nav pull-right">
                        <li class="dropdown">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown">Peering<b class="caret"></b></a>
                            <ul class="dropdown-menu">
                                {if not config('ixp_fe.frontend.disabled.lg' )}
                                    <li>
                                        <a href="{genUrl}/lg">Looking Glass</a>
                                    </li>
                                {/if}
                                {if ixp_min_auth( config( 'ixp.peering-matrix.min-auth' ) ) and !config( 'ixp_fe.frontend.disabled.peering-matrix' )}
                                    <li><a href="{route('peering-matrix@index')}">Peering Matrix</a></li>
                                {/if}
                            </ul>
                        </li>
                        <li class="dropdown {if $controller eq 'public-statistics' or substr( $action, 0, 9 ) eq 'statistic' or $action eq 'traffic-stats' or $action eq 'trunk-graphs' or $action eq 'switch-graphs' or $controller eq 'weather-map'}active{/if}">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown">Statistics<b class="caret"></b></a>
                            <ul class="dropdown-menu">
                                <li>
                                    <a href="{route( 'statistics/ixp' )}">Overall Peering Graphs</a>
                                </li>
                                <li>
                                    <a href="{route( 'statistics/infrastructure' )}">Infrastructure Graphs</a>
                                </li>
                                <li>
                                    <a href="{route( 'statistics/vlan' )}">VLAN / Per-Protocol Graphs</a>
                                </li>
                                <li>
                                    <a href="{route( 'statistics/trunk' )}">Inter-Switch / PoP Graphs</a>
                                </li>
                                <li>
                                    <a href="{route( 'statistics/switch' )}">Switch Aggregate Graphs</a>
                                </li>
                                <li class="divider"></li>
                                    {if is_array( config( 'ixp_tools.weathermap', false ) )}
                                        {foreach from=config( 'ixp_tools.weathermap' ) key=k item=w}
                                            <li>
                                                <a href="{route( 'weathermap', ['id' => {$k} ] ) }">{$w.menu}</a>
                                            </li>
                                        {/foreach}
                                    {/if}
                            </ul>
                        </li>

                        <li class="{if $controller eq 'static' and $action eq 'support'}active{/if}">
                            <a href="{genUrl controller="static" action="support"}">Support</a>
                        </li>
                        <li>
                            <a href="http://www.ixpmanager.org/" target="_blank">About</a>
                        </li>
                        <li class="{if $controller eq 'auth' and $action eq 'login'}active{/if}">
                            <a href="{genUrl controller="auth" action="login"}">Login</a>
                        </li>
                    </ul>
                </div>
            {/if}
        </div>
    </div>
</div>

{if isset( $hasIdentity ) and $hasIdentity and $user->getPrivs() eq 3}

    <div class="container-fluid">

    {tmplinclude file="menu.phtml"}

{elseif isset( $mode ) and $mode eq 'fluid'}

    <div class="container-fluid">

{else}

    <div class="container">

{/if}
