{if isset( $options.mini_js ) and $options.mini_js}
    <script type="text/javascript" src="{genUrl}/js/min.bundle-v37.js"></script>
{else}
    <script type="text/javascript" src="{genUrl}/js/200-jquery-1.11.0.js"></script>
    <script type="text/javascript" src="{genUrl}/js/210-jquery-ui-1.10.3.custom.js"></script>
    <script type="text/javascript" src="{genUrl}/js/220-jquery.dataTables-1.9.4.js"></script>
    <script type="text/javascript" src="{genUrl}/js/231-jquery.contextMenu-1.5.24.js"></script>
    <script type="text/javascript" src="{genUrl}/js/240-jquery.json-2.3.js"></script>
    <script type="text/javascript" src="{genUrl}/js/245-jquery-cookie.js"></script>
    <script type="text/javascript" src="{genUrl}/js/250-jquery-colorbox-1.4.21.js"></script>
    <script type="text/javascript" src="{genUrl}/js/300-chosen.jquery.js"></script>
    <script type="text/javascript" src="{genUrl}/js/310-throbber.js"></script>
    <script type="text/javascript" src="{genUrl}/js/700-php.js"></script>
    <script type="text/javascript" src="{genUrl}/js/800-bootstrap-2.3.2.js"></script>
    <script type="text/javascript" src="{genUrl}/js/830-bootstrap-wysihtml5.js"></script>
    <script type="text/javascript" src="{genUrl}/js/890-bootbox.js"></script>
    <script type="text/javascript" src="{genUrl}/js/900-oss-framework.js"></script>
    <script type="text/javascript" src="{genUrl}/js/999-ixpmanager.js"></script>
{/if}
