<li class="dropdown">
    <a href="#" class="dropdown-toggle" data-toggle="dropdown">Documentation<b class="caret"></b></a>
    <ul class="dropdown-menu">
        <li>
            <a href="{route( 'content', [ 'priv' => 0, 'page' => 'example' ] )}">Example Page</a>
        </li>

        {* PLEASE LEAVE THIS SOMEWHERE!  IT'S ONLY FAIR INEX GETS SOME CREDIT :D *}
        <li class="divider"></li>
        <li>
            <a href="http://www.ixpmanager.org/" target="_blank">About</a>
        </li>
    </ul>
</li>
