{tmplinclude file="header-base.phtml"}

<div class="navbar navbar-inverse navbar-fixed-top">
    <div class="navbar-inner">
        <div class="{if isset( $hasIdentity ) and $hasIdentity and $user->getPrivs() eq 3}container-fluid{else}container{/if}">
            <a class="brand" href="{genUrl}">{$options.identity.sitename}</a>
            {if isset( $hasIdentity ) and $hasIdentity}
                <div class="nav-collapse">
                     <ul class="nav">
                        {if $user->getPrivs() neq 2}
                            <li class="dropdown {if $action eq 'switch-configuration' or $action eq 'members-details-list' or ( $controller eq 'meeting' and $action eq 'read' )}active{/if}">
                                <a href="#" class="dropdown-toggle" data-toggle="dropdown">Member Information <b class="caret"></b></a>
                                <ul class="dropdown-menu">
                                    <li>
                                        <a href="{genUrl controller="switch" action="configuration"}">Switch Configuration</a>
                                    </li>
                                    <li>
                                        <a href="{genUrl controller="customer" action="details"}">Member Details</a>
                                    </li>
                                    <li>
                                        <a href="{genUrl controller="meeting" action="read"}">Meetings</a>
                                    </li>
                                </ul>
                            </li>
                            <li class="dropdown">
                                <a href="#" class="dropdown-toggle" data-toggle="dropdown">Peering<b class="caret"></b></a>
                                <ul class="dropdown-menu">
                                    {if $user->getPrivs() eq 1}
                                        <li>
                                            <a href="{genUrl controller="peering-manager"}">Peering Manager</a>
                                        </li>
                                    {/if}
                                    <li>
                                        <a href="{genUrl controller="peering-matrix"}">Public Peering Matrix</a>
                                    </li>
                                </ul>
                            </li>

                            {* STATIC DOCUMENTATION LINKS - SPECIFIC TO INDIVIDUAL IXPS *}
                            {* Add a skinned file in views/_skins/xxx/header-documentation.phtml for your IXP to override the sample *}
                            {tmplinclude file="header-documentation.phtml"}
                            
                            <li class="dropdown {if $controller eq 'statistics' or substr( $action, 0, 9 ) eq 'statistic' or $action eq 'traffic-stats' or $action eq 'trunk-graphs' or $action eq 'switch-graphs' or $controller eq 'weather-map'}active{/if}">
                                <a href="#" class="dropdown-toggle" data-toggle="dropdown">Statistics<b class="caret"></b></a>
                                <ul class="dropdown-menu">
                                    {if $user->getPrivs() eq USER::AUTH_CUSTUSER and not $user->getCustomer()->isTypeAssociate()}
                                        <li>
                                            <a href="{genUrl controller="statistics" action="member"}">My Statistics</a>
                                        </li>
                                        <li>
                                            <a href="{genUrl controller="statistics" action="p2p"}">My Peer to Peer Traffic</a>
                                        </li>
                                        <li class="divider"></li>
                                    {/if}
                                    <li>
                                        <a href="{genUrl controller="statistics" action="public"}">Overall Peering Statistics</a>
                                    </li>
                                    <li>
                                        <a href="{genUrl controller="statistics" action="trunks"}">Trunk Graphs</a>
                                    </li>
                                    <li>
                                        <a href="{genUrl controller="statistics" action="switches"}">Switch Aggregate Graphs</a>
                                    </li>
                                    {if isset( $options.weathermap )}
                                        {foreach from=$options.weathermap key=k item=w}
                                            <li>
                                                <a href="{genUrl controller="weather-map" action="index" id=$k}">{$w.menu}</a>
                                            </li>
                                        {/foreach}
                                    {/if}
                                </ul>
                            </li>
                        {/if}
                        <li class="{if $controller eq 'static' and $action eq 'support'}active{/if}">
                            <a href="{genUrl controller="static" action="support"}">Support</a>
                        </li>
                        {if $user->getPrivs() eq USER::AUTH_SUPERUSER}
                            {tmplinclude file="staff-links.phtml"}
                        {/if}
                        
                        {if $user->getPrivs() neq 3}
	                        <li class="{if $controller eq 'profile'}active{/if}">
	                            <a href="{genUrl controller="profile"}">Profile</a>
	                        </li>
                        {/if}
                        
                    </ul>
                    <ul class="nav pull-right">
                        {if $user->getPrivs() eq 3}
                            <form class="navbar-search pull-left">
                                <select data-placeholder="View a Customer..." id="menu-select-customer" type="select" name="id" class="chzn-select">
                                    <option></option>
                                    {foreach from=$customers key=k item=i}
                                        <option value="{$k}">{$i}</option>
                                    {/foreach}
                                </select>
                            </form>
                        {/if}
                            
                        {if isset( $session->switched_user_from ) and $session->switched_user_from}
                            <li><a href="{genUrl controller="auth" action="switch-user-back"}">Switch Back</a></li>
                        {elseif $user->getPrivs() eq 3}
	                        <li class="dropdown">
							    <a href="#" class="dropdown-toggle" data-toggle="dropdown">My Account<b class="caret"></b></a>
							    <ul class="dropdown-menu">
							        <li>
							            <a href="{genUrl controller="profile"}">Profile</a>
							        </li>
							        <li class="divider"></li>
							        <li>
		                                <a href="{genUrl controller="auth" action="logout"}">Logout</a>
        							</li>
							    </ul>
							</li>
                        {else}
                            <li><a href="{genUrl controller="auth" action="logout"}">Logout</a></li>
                        {/if}
                    </ul>
                </div><!--/.nav-collapse -->
            {else}
                <div class="nav-collapse">
                    <ul class="nav pull-right">
                        <li class="{if $controller eq 'static' and $action eq 'support'}active{/if}">
                            <a href="{genUrl controller="static" action="support"}">Support</a>
                        </li>
                        <li class="{if $controller eq 'index' and $action eq 'about'}active{/if}">
                            <a href="{genUrl controller="index" action="about"}">About</a>
                        </li>
                        <li class="{if $controller eq 'auth' and $action eq 'login'}active{/if}">
                            <a href="{genUrl controller="auth" action="login"}">Login</a>
                        </li>
                    </ul>
                </div>
            {/if}
        </div>
    </div>
</div>
    
{if isset( $hasIdentity ) and $hasIdentity and $user->getPrivs() eq 3}
    
    <div class="container-fluid">

    {tmplinclude file="menu.phtml"}
    
{elseif isset( $mode ) and $mode eq 'fluid'}

    <div class="container-fluid">

{else}

    <div class="container">

{/if}
