
<div class="row-fluid">
<div class="span2">
<div class="well sidebar-nav">

<ul class="nav nav-list">

    <form class="form-search" method="get" action="{route( 'search' )}">
        <input type="text" class="" style="width: 65%" placeholder="Search for..." name="search">
        <a class="btn btn-small" id="searchHelp" data-toggle="modal" data-target="#searchHelpModal"><i class="icon-question-sign"></i></a>
    </form>

    <li class="nav-header">IXP Customer Actions</li>

        <li {if $controller eq 'customer' and ( $action eq 'list' or $action eq 'add' or $action eq 'edit' or $action eq 'dashboard' )}class="active"{/if}>
            <a href="{route( 'customer@list')}">Customers</a>
        </li>

        <li>
            <a href="{genUrl controller='interfaces/virtual' action='list'}">Interfaces / Ports</a>
        </li>

        <li>
            <a href="{genUrl controller='interfaces/sflow-receiver' action='list'}">Sflow Receivers</a>
        </li>

    <li {if $controller eq 'patch-panel'}class="active"{/if}>
            <a href="{genUrl controller='patch-panel' action='list'}">Patch Panels</a>
        </li>
        <li {if $controller eq 'user' and $action neq 'last'}class="active"{/if}>
            <a href="{genUrl controller='user' action='list'}">Users</a>
        </li>
        <li {if $controller eq 'contact'}class="active"{/if}>
            <a href="{genUrl controller='contact' action='list'}">Contacts</a>
            {if $controller eq 'contact' or $controller eq 'contact-group'}
                <ul class="nav nav-list">
                    <li {if $controller eq 'contact-group'}class="active"{/if}>
                        <a href="{genUrl controller='contact-group' action='list'}">Contact Groups</a>
                    </li>
                </ul>
            {/if}
        </li>

    {if not isset( $options['frontend']['disabled']['cust-kit'] ) or not $options['frontend']['disabled']['cust-kit'] }
        <li {if $controller eq 'cust-kit'}class="active"{/if}>
            <a href="{genUrl controller='cust-kit' action='list'}">Colocated Equipment</a>
        </li>
    {/if}


    <li class="nav-header">IXP Admin Actions</li>

        <li {if $controller eq 'infrastructure'}class="active"{/if}>
            <a href="{genUrl controller='infrastructure' action='list'}">Infrastructures</a>
        </li>

        <li {if $controller eq 'location'}class="active"{/if}>
            <a href="{route( 'facility@list' )}">Facilities</a>
        </li>

        <li {if $controller eq 'cabinet'}class="active"{/if}>
            <a href="{route( 'rack@list' )}">Racks</a>
        </li>


        <li {if $controller eq 'switch'}class="active"{/if}>
            <a href="{route( 'switch@list' )}">Switches</a>
        </li>

        <li {if $controller eq 'router'}class="active"{/if}>
            <a href="{genUrl controller='router' action='list'}">Routers</a>
        </li>

        <li {if $controller eq 'console-server'}class="active"{/if}>
            <a href="{route( 'console-server@list' )}">Console Servers</a>
        </li>

        {if config( 'ixp_fe.frontend.beta.core_bundles', false )}

            <li>
                <a href="{genUrl controller='interfaces/core-bundle' action='list'}">Core Bundles</a>
            </li>

        {/if}

        <li>
            <a href="{route( 'ip-address@list', [ "protocol" => "6" ] )}">IPv4/6 Addresses</a>
        </li>

        <li>
            <a href="{genUrl controller='layer2-address' action='list'}">MAC Addresses</a>

            {if not isset( $options['frontend']['disabled']['mac-address'] ) or not $options['frontend']['disabled']['mac-address'] }

                {if $controller eq 'mac-address'}
                    <ul class="nav nav-list">
                        <li>
                            <a href="{genUrl controller='layer2-address' action='list'}">Configured Addresses</a>
                        </li>
                        <li {if $controller eq 'mac-address'}class="active"{/if}>
                            <a href="{genUrl controller='mac-address' action='list'}">Discovered Addresses</a>
                        </li>
                    </ul>
                {/if}

            {/if}

        </li>

        <li {if $controller eq 'vendor'}class="active"{/if}>
            <a href="{genUrl controller='vendor' action='list'}">Vendors</a>
        </li>

        <li {if $controller eq 'vlan' and $action neq 'private'}class="active"{/if}>
            <a href="{genUrl controller='vlan' action='list'}">VLANs</a>

            {if $controller eq 'vlan'}
                <ul class="nav nav-list">
                    <li {if $controller eq 'vlan' and $action eq 'private'}class="active"{/if}>
                        <a href="{genUrl controller='vlan' action='private'}">Private VLANs</a>
                    </li>
                </ul>
            {/if}

        </li>

        <li {if $controller eq 'irrdb-config'}class="active"{/if}>
            <a href="{genUrl controller='irrdb-config' action='list'}">IRRDB Configuration</a>
        </li>

        {if !config( 'ixp_fe.frontend.disabled.rs-prefixes', false ) }
            <li>
                <a href="{route( 'rs-prefixes@list' )}">Route Server Prefixes</a>
            </li>
        {/if}


    <li class="nav-header">IXP Statistics</li>

        <li {if $controller eq 'statistics' and $action eq 'members'}class="active"{/if}>
            <a href="{genUrl controller='statistics' action='members'}">Member Statistics</a>
        </li>

        {if $logoManagementActive}
            <li {if $controller eq 'logo' }class="active"{/if}>
                <a href="{route( 'logo@logos' )}">Member Logos</a>
            </li>
        {/if}
        <li {if $controller eq 'statistics' and $action eq 'league-table'}class="active"{/if}>
            <a href="{genUrl controller='statistics' action='league-table'}">League Table</a>
        </li>

        {* 95th Percentiles {genUrl controller="customer" action="ninety-fifth"} *}
        {* Last Logins      {genUrl controller="user" action="last"} *}



    <li class="nav-header">IXP Utilities</li>

        <li>
            <a href="{route( 'utils/phpinfo' )}">PHP Info</a>
        </li>
        <li {if $controller eq 'user' and $action eq 'last'}class="active"{/if}>
            <a href="{route('login-history@list')}">Last Logins</a>
        </li>


    </ul>

</div><!--/.well -->

<div id="searchHelpModal" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="searchHelpModalLabel" aria-hidden="true">
    <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
        <h3 id="searchHelpModalLabel">Search Help</h3>
    </div>
    <div class="modal-body">
        <p>
            The search box allows for an efficient database search via a number of parameters:
        </p>
        <div class="row-fluid">
            <div class="span6">
                <dl>
                    <dt>IPv4 Address</dt>
                    <dd>
                        Full address as <code>a.b.c.d</code> or last octet as <code>.d</code>
                    </dd>
                    <dt>AS Number / Macro</dt>
                    <dd>
                        Enter ASN as <code>XXX</code> or <code>asXXX</code> and AS macro as <code>as-XXX</code>
                    </dd>
                    <dt>Usernames</dt>
                    <dd>
                        Find usernames <em>starting with</em> <code>xxx</code> by entering <code>@xxx</code>
                    </dd>
                    <dt>Route Server Prefix</dt>
                    <dd>
                        Enter IPv4 <code>a.b.c.d/x</code> or IPv6 <code>a:b::/x</code>
                    </dd>
                    <dt>Patch Panel Port</dt>
                    <dd>
                        Enter ID <code>PPP-xxx</code>
                    </dd>
                </dl>
            </div>
            <div class="span6">
                <dl>
                    <dt>IPv6 Address</dt>
                    <dd>
                        Full (compact) address as <code>a:b::h</code> or last section as <code>:h</code>
                    </dd>
                    <dt>MAC Address</dt>
                    <dd>
                        Enter as <code>xxxxxxxxxxxx</code> or <code>xx:xx:xx:xx:xx:xx</code>
                    </dd>
                    <dt>Email Addresses</dt>
                    <dd>
                        Find contacts / users via full email address <code>xxx@example.com</code>
                    </dd>
                    <dt>Wildcard</dt>
                    <dd>
                        Any other text is searched as <code>%xxx%</code> on customer details
                    </dd>
                </dl>
            </div>
        </div>
    </div>
    <div class="modal-footer">
        <button class="btn" data-dismiss="modal" aria-hidden="true">Close</button>
    </div>
</div>


</div><!--/span-->
<div class="span10">
