
<div class="row-fluid">
<div class="span2">
<div class="well sidebar-nav">

<ul class="nav nav-list">

    <form class="form-search" method="get" action="{genUrl controller="search" action="do"}">
        <input type="text" class="search-query" style="width: 50%" placeholder="Search..." name="search">
        <a class="btn btn-small" id="searchHelp" data-toggle="modal" data-target="#searchHelpModal"><i class="icon-question-sign"></i></a>
    </form>

    <li class="nav-header">IXP Customer Actions</li>

        <li {if $controller eq 'customer' and ( $action eq 'list' or $action eq 'add' or $action eq 'edit' or $action eq 'dashboard' )}class="active"{/if}>
            <a href="{genUrl controller='customer' action='list'}">Customers</a>
        </li>
        <li {if $controller eq 'virtual-interface'}class="active"{/if}>
            {if $controller eq 'virtual-interface' or $controller eq 'vlan-interface' or $controller eq 'physical-interface'}
                <a href="{genUrl controller='virtual-interface' action='list'}">Interfaces (Virtual)</a>
                <ul class="nav nav-list">
                    <li {if $controller eq 'physical-interface'}class="active"{/if}>
                        <a href="{genUrl controller='physical-interface' action='list'}">Physical Interfaces</a>
                    </li>
                    <li {if $controller eq 'vlan-interface' and $action neq 'quick-add'}class="active"{/if}>
                        <a href="{genUrl controller='vlan-interface' action='list'}">Vlan Interfaces</a>
                    </li>
                </ul>
            {else}
                <a href="{genUrl controller='virtual-interface' action='list'}">Interfaces</a>
            {/if}

        </li>
        <li {if $controller eq 'user' and $action neq 'last'}class="active"{/if}>
            <a href="{genUrl controller='user' action='list'}">Users</a>
        </li>
        <li {if $controller eq 'contact'}class="active"{/if}>
            <a href="{genUrl controller='contact' action='list'}">Contacts</a>
            {if $controller eq 'contact' or $controller eq 'contact-group'}
                <ul class="nav nav-list">
                    <li {if $controller eq 'contact-group'}class="active"{/if}>
                        <a href="{genUrl controller='contact-group' action='list'}">Contact Groups</a>
                    </li>
                </ul>
            {/if}
        </li>

	{if not isset( $options['frontend']['disabled']['cust-kit'] ) or not $options['frontend']['disabled']['cust-kit'] }
            <li {if $controller eq 'cust-kit'}class="active"{/if}>
                <a href="{genUrl controller='cust-kit' action='list'}">Colocated Equipment</a>
            </li>
        {/if}

	{if not isset( $options['frontend']['disabled']['meeting'] ) or not $options['frontend']['disabled']['meeting'] }
            <li {if $controller eq 'meeting' and $controller neq 'meeting-item' and $action neq 'read'}class="active"{/if}>
                <a href="{genUrl controller='meeting' action='list'}">Meetings</a>

                {if $controller eq 'meeting' or $controller eq 'meeting-item' or ( $controller eq 'static' and $action eq 'meetings-instructions' )}
                    <ul class="nav nav-list">
                        <li {if $controller eq 'meeting-item'}class="active"{/if}>
                            <a href="{genUrl controller='meeting-item' action='list'}">Presentations</a>
                        </li>
                        <li {if $controller eq 'meeting' and $action eq 'read'}class="active"{/if}>
                            <a href="{genUrl controller='meeting' action='read'}">Member View</a>
                        </li>
                        <li {if $controller eq 'static' and $action eq 'meetings-instructions'}class="active"{/if}>
                            <a href="{genUrl controller='static' action='meetings-instructions'}">Instructions</a>
                        </li>
                    </ul>
                {/if}
            </li>
        {/if}


    <li class="nav-header">IXP Admin Actions</li>
        {if $multiIXP }
            <li {if $controller eq 'ixp'}class="active"{/if}>
                <a href="{genUrl controller='ixp' action='list'}">IXPs</a>
            </li>
        {/if}

        <li {if $controller eq 'infrastructure'}class="active"{/if}>
            <a href="{genUrl controller='infrastructure' action='list'}">Infrastructures</a>
        </li>

        <li {if $controller eq 'location'}class="active"{/if}>
            <a href="{genUrl controller='location' action='list'}">Locations</a>
        </li>

        <li {if $controller eq 'cabinet'}class="active"{/if}>
            <a href="{genUrl controller='cabinet' action='list'}">Cabinets</a>
        </li>

        <li {if $controller eq 'switch' and $action neq 'add-ports'}class="active"{/if}>
            <a href="{genUrl controller='switch' action='list'}">Switches</a>

            {if $controller eq 'switch' or $controller eq 'switch-port'}
                <ul class="nav nav-list">
                    <li {if $controller eq 'switch-port' and $action neq 'unused-optics'}class="active"{/if}>
                        <a href="{genUrl controller='switch-port' action='list'}">Switch Ports</a>
                    </li>
                    <li {if $controller eq 'switch-port' and $action eq 'unused-optics'}class="active"{/if}>
                        <a href="{genUrl controller='switch-port' action='unused-optics'}">Unused Optics</a>
                    </li>
                </ul>
            {/if}

        </li>

        <li>
            <a href="{genUrl controller='ipv6-address' action='list'}">IP Addressing</a>

            {if $controller eq 'ipv4-address' or $controller eq 'ipv6-address'}
                <ul class="nav nav-list">
                    <li {if $controller eq 'ipv4-address' and $action neq 'add-addresses'}class="active"{/if}>
                        <a href="{genUrl controller='ipv4-address' action='list'}">IPv4 Addresses</a>
                    </li>
                    <li {if $controller eq 'ipv6-address'}class="active"{/if}>
                        <a href="{genUrl controller='ipv6-address' action='list'}">IPv6 Addresses</a>
                    </li>
                </ul>
            {/if}

        </li>

        {if not isset( $options['frontend']['disabled']['mac-address'] ) or not $options['frontend']['disabled']['mac-address'] }
            <li {if $controller eq 'mac-address'}class="active"{/if}>
                 <a href="{genUrl controller='mac-address' action='list'}">MAC Addresses</a>
            </li>
        {/if}

        <li {if $controller eq 'vendor'}class="active"{/if}>
            <a href="{genUrl controller='vendor' action='list'}">Vendors</a>
        </li>

        {if not isset( $options['frontend']['disabled']['console-server-connection'] ) or not $options['frontend']['disabled']['console-server-connection'] }
            <li {if $controller eq 'console-server-connection'}class="active"{/if}>
                <a href="{genUrl controller='console-server-connection' action='list'}">Console Server Connections</a>
            </li>
        {/if}

        <li {if $controller eq 'vlan' and $action neq 'private'}class="active"{/if}>
            <a href="{genUrl controller='vlan' action='list'}">VLANs</a>

            {if $controller eq 'vlan'}
                <ul class="nav nav-list">
                    <li {if $controller eq 'vlan' and $action eq 'private'}class="active"{/if}>
                        <a href="{genUrl controller='vlan' action='private'}">Private VLANs</a>
                    </li>
                </ul>
            {/if}

        </li>

        <li {if $controller eq 'irrdb-config'}class="active"{/if}>
            <a href="{genUrl controller='irrdb-config' action='list'}">IRRDB Configuration</a>
        </li>

        {if not isset( $options['frontend']['disabled']['rs-prefixes'] ) or not $options['frontend']['disabled']['rs-prefixes'] }
            <li {if $controller eq 'rs-prefixes'}class="active"{/if}>
                <a href="{genUrl controller='rs-prefixes' action='index'}">Route Server Prefixes</a>
            </li>
        {/if}


    <li class="nav-header">IXP Statistics</li>

        <li {if $controller eq 'statistics' and $action eq 'members'}class="active"{/if}>
            <a href="{genUrl controller='statistics' action='members'}">Member Statistics - Graphs</a>
        </li>
        <li {if $controller eq 'statistics' and $action eq 'list'}class="active"{/if}>
            <a href="{genUrl controller='statistics' action='list'}">Member Statistics - List</a>
        </li>
        <li {if $controller eq 'statistics' and $action eq 'league-table'}class="active"{/if}>
            <a href="{genUrl controller='statistics' action='league-table'}">League Table</a>
        </li>

        {* 95th Percentiles {genUrl controller="customer" action="ninety-fifth"} *}
        {* Last Logins      {genUrl controller="user" action="last"} *}



    <li class="nav-header">IXP Utilities</li>

        <li {if $controller eq 'utils' and $action eq 'phpinfo'}class="active"{/if}>
            <a href="{genUrl controller='utils' action='phpinfo'}">PHP Info</a>
        </li>
        <li {if $controller eq 'utils' and $action eq 'apcinfolist'}class="active"{/if}>
            <a href="{genUrl controller='utils' action='apcinfo'}">APC Info</a>
        </li>
        <li {if $controller eq 'user' and $action eq 'last'}class="active"{/if}>
            <a href="{genUrl controller='user' action='last'}">Last Logins</a>
        </li>


    </ul>

</div><!--/.well -->

<div id="searchHelpModal" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="searchHelpModalLabel" aria-hidden="true">
    <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
        <h3 id="searchHelpModalLabel">Search Help</h3>
    </div>
    <div class="modal-body">
        <p>
            The search box allows for an efficient database search via a number of parameters:
        </p>
        <div class="row-fluid">
            <div class="span6">
                <dl>
                    <dt>IPv4 Address</dt>
                    <dd>
                        Full address as <code>a.b.c.d</code> or last octet as <code>.d</code>
                    </dd>
                    <dt>AS Number / Macro</dt>
                    <dd>
                        Enter ASN as <code>XXX</code> or <code>asXXX</code> and AS macro as <code>as-XXX</code>
                    </dd>
                    <dt>Usernames</dt>
                    <dd>
                        Find usernames <em>starting with</em> <code>xxx</code> by entering <code>@xxx</code>
                    </dd>
                    <dt>Route Server Prefix</dt>
                    <dd>
                        Enter IPv4 <code>a.b.c.d/x</code> or IPv6 <code>a:b::/x</code>
                    </dd>
                </dl>
            </div>
            <div class="span6">
                <dl>
                    <dt>IPv6 Address</dt>
                    <dd>
                        Full (compact) address as <code>a:b::h</code> or last section as <code>:h</code>
                    </dd>
                    <dt>MAC Address</dt>
                    <dd>
                        Enter as <code>xxxxxxxxxxxx</code> or <code>xx:xx:xx:xx:xx:xx</code>
                    </dd>
                    <dt>Email Addresses</dt>
                    <dd>
                        Find contacts / users via full email address <code>xxx@example.com</code>
                    </dd>
                    <dt>Wildcard</dt>
                    <dd>
                        Any other text is searched as <code>%xxx%</code> on customer details
                    </dd>
                </dl>
            </div>
        </div>
    </div>
    <div class="modal-footer">
        <button class="btn" data-dismiss="modal" aria-hidden="true">Close</button>
    </div>
</div>


</div><!--/span-->
<div class="span10">
