{tmplinclude file="header.phtml"}

<ul class="breadcrumb">
    <li>
        <a href="{genUrl}">Home</a> <span class="divider">/</span>
    </li>
    <li>
        Utilities <span class="divider">/</span>
    </li>
    <li class="active">
        APC Info
    </li>
</ul>

<div>
    
{OSS_Message}

<div class="row-fluid">
    <iframe class="span12"
        style="border: none; min-height: 600px; height: 600px;"
        src="{genUrl controller="utils" action="real-apcinfo"}"></iframe>
</div>
    
</div>

{tmplinclude file="utils/js/iframe.js"}
{tmplinclude file="footer.phtml"}
