<html>
    <head>
        <title>Port Utilisation Report</title>
    </head>
    <body>
        <h1>Port Utilisation Report</h1>
        <p>
            The following ports are at or have exceeded <?= $t->threshold ?>% utilisation over the past week.
        </p>

        <br><br>
        <?php foreach( $t->excess as $e ): ?>
            <h2>
                <?= $e['cust']->name ?>
            </h2>

            <?php foreach( $e['ports'] as $i => $p ): ?>
                <h3>Port(s) on <?= $p['switch']->name ?> - Speed: <?= $p['speed'] ?>Gbps</h3>

                <ul>
                    <?php if( $p['utilIn'] > $t->threshold ): ?>
                        <li>
                            <strong>INBOUND:</strong> Traffic inbound on this port reached a maximum of <?= sprintf( "%0.1f", $p['utilIn'] ) ?>%.
                        </li>
                    <?php endif; ?>

                    <?php if( $p['utilOut'] > $t->threshold ): ?>
                        <li>
                            <strong>OUTBOUND:</strong> Traffic outbound on this port reached a maximum of <?= sprintf( "%0.1f", $p['utilOut'] ) ?>%.
                        </li>
                    <?php endif; ?>
                </ul>

                <p>
                    <a href="<?= route( "customer@overview" , [ 'cust' => $e['cust']->id ] ) ?> ">
                        <img src="data:image/png;base64,<?= base64_encode( $p['png'] ) ?>">
                    </a>
                </p>

                <br>
            <?php endforeach; ?>
            <br><hr><br>
        <?php endforeach; ?>

        <?php if( count( $t->excess ) === 0 ): ?>
            <p>
                No ports were found with excess utilisation over the past week.
            </p>
        <?php endif; ?>

        <br><br>

        <p>
            <em>
                This report was generated by <a href="<?= url('') ?>">IXP Manager</a> for <?= env( 'IDENTITY_ORGNAME' ) ?>.
            </em>
        </p>
    </body>
</html>