
{if isset( $data.0 )}
    {assign var="example_api_key" value="/key/`$data.0.apiKey`"}
{else}
    {assign var="example_api_key" value="/key/\$your_api_key"}
{/if}

{if config( 'ixp_api.json_export_schema.public' )}
    {assign var="example_api_key" value=""}
{/if}

<br>
<h3>Available API Endpoints</h3>

<dl>

<dt>IXP JSON Schema Export</dt>
<dd>
    See <a href="https://github.com/euro-ix/json-schemas">here for details, versions and definition</a>.<br>
    Example:
        <code>
            <a href="{genUrl module="apiv1" controller="member-list" action="list"}{$example_api_key}">
                {genUrl module="apiv1" controller="member-list" action="list"}{$example_api_key}
            </a>
        </code>
        <br><br>
    The above will always return the latest inplemented version (highest of the versions below). Other versions as available as
    follows:
    <ul>
        {foreach $JSON_SCHEMAS as $version}
        <li>
            <code>
                <a href="{genUrl module="apiv1" controller="member-list" action="list"}{$example_api_key}/version/{$version}">
                    {genUrl module="apiv1" controller="member-list" action="list"}{$example_api_key}/version/{$version}
                </a>
            </code>
        </li>
        {/foreach}
    </ul>
    You are advised to specify the version you're developing against as the default will be updated as the specification is updated.
</dd>

</dl>

<br>
<h3>Available API Endpoints - V4</h3>

{if isset( $data.0 )}
    {assign var="example_api_key" value="`$data.0.apiKey`"}
{else}
    {assign var="example_api_key" value="\$your_api_key"}
{/if}


<p>
    API key can be passed in the header (preferred) or on the URL. For example:
    <ul>
        <li> <code>curl -X GET -H "X-IXP-Manager-API-Key: {$example_api_key}" {genUrl}/api/v4/test</code></li>
        <li> <code>wget {genUrl}/api/v4/test?apikey={$example_api_key}</code></li>
    </ul>
</p>

<dl>

    {if $user->isSuperUser()}

        <dt>Switch Ports</dt>
        <dd>
            <ul>
                <li>
                    Get the customer who has been allocated a switch port:<br>
                    <code>{genUrl}/api/v4/switch-port/{ldelim}id{rdelim}/customer</code> where <code>id</code> is the switch port ID.
                    <br><br>
                    If a switch port has an allocated customer, the JSON response is:<br>
                    <code>{ldelim}"customerFound":true,"id":102,"name":"Packet Shifters Ltd"{rdelim}</code><br>
                    where the enclosed id is the customer object id.
                    <br><br>
                    If a switch port does not have an allocated customer, the JSON response is:<br>
                    <code>{ldelim}"customerFound":false{rdelim}</code>
                    <br><br>
                    Lastly, if the switch port does not exist, a 404 HTTP response is thrown.
                </li>
            </ul>
        </dd>

    {/if}

</dl>