{tmplinclude file="header.phtml"}

    <div class="page-content">
        <div class="page-header">
            <h1>{$options.identity.orgname} Public Traffic Statistics</h1>
        </div>

<h3>{$graphs[$graphid]->title()} :: {foreach from=$categories key=cvalue item=cname}{if $category eq $cvalue}{$cname}{/if}{/foreach}</h3>

{OSS_Message}

<p>
<form action="{genUrl controller="public-statistics" action="public"}" method="post" class="form-horizontal">
<table>
<tr>
    <td width="20"></td>
    <td valign="middle"><strong>Select {if $multiIXP}IXP / {/if}Infrastructure:&nbsp;</strong></td>
    <td width="300">
        <select name="graph" class="chzn-select" onchange="this.form.submit();">
            {foreach $graphs as $id => $g}
                <option value="{$id}" {if $graphid eq $id}selected{/if}>{$g->title()}</option>
            {/foreach}
        </select>
    </td>
    <td width="20"></td>
    <td valign="middle"><strong>Category:&nbsp;</strong></td>
    <td width="100">
        <select name="category" class="chzn-select" onchange="this.form.submit();">
            {foreach from=$categories key=cval item=cname}
                <option value="{$cval}" {if $category eq $cval}selected{/if}>{$cname}</option>
            {/foreach}
        </select>
    </td>
</tr>
</table>
</form>
</p>

<div class="row-fluid">

{assign var='count' value=0}

{foreach from=$periods key=pvalue item=pname}

    <div class="span6">

        <div class="well">
            <h3>{$pname} Graph</h3>
            {$graph->setPeriod( $pvalue )->renderer()->boxLegacy()}
        </div>
    </div>

    {assign var='count' value=$count+1}

    {if $count%2 eq 0}
        </div><br /><div class="row-fluid">
    {/if}

{/foreach}

{if $count%2 neq 0}
    <div class="span3"></div>
{/if}

</div>

</div>



{tmplinclude file="footer.phtml"}
