{tmplinclude file="header.phtml"}

{if $user->getPrivs() eq 3}
    <ul class="breadcrumb">
        <li>
            <a href="{genUrl}">Home</a> <span class="divider">/</span>
        </li>
        <li>
            Documentation <span class="divider">/</span>
        </li>
        <li class="active">
            Membership Fees and Charges
        </li>
    </ul>

    <div>
{else}
    <div class="page-content">
        <div class="page-header">
            <h1>Membership Fees and Charges</h1>
        </div>
{/if}

<p>
INEX is a member supported organisation and operates on a not-for-profit basis.
Revenue for the organisation comes from two primary sources, membership fees and
port charges.
</p>

<h3>2015 Fees and Charges</h3>

<br /><br />
<h4>Membership Fees</h4>

<br /><br />

<div class="row-fluid">
    <div class="span9">
        <table class="table">
        <tr>
            <th width="75%" >Description</th>
            <th>Charge</th>
        </tr>

        <tr>
            <td>Associate Membership</td>
            <td>&euro;1,000 p.a.</td>
        </tr>

        <tr>
            <td>Full Membership</td>
            <td>&euro;1,000 p.a.</td>
        </tr>

        <tr>
            <td>Joining Fee</td>
            <td>No charge</td>
        </tr>
        </table>
    </div>
</div>


<br /><br />
<h4>Port Charges</h4>
<br /><br />

<div class="row-fluid">
    <div class="span9">
        <table class="table">
            <tr>
                <th width="30%">Description</th>
                <th>First Port</th>
                <th>Second Port</th>
                <th>Subsequent Port&nbsp;&nbsp;&nbsp;&nbsp;</th>
                <th>Term</th>
            </tr>

            <tr>
                <td>100Mbit/s port</td>
                <td>&euro;600</td>
                <td>Free (on LAN2)&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</td>
                <td>&euro;450</td>
                <td>per annum</td>
            </tr>

            <tr>
                <td>1Gbit/s port</td>
                <td>&euro;2,400 (inc. free 100Mb)&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</td>
                <td>&euro;1,800</td>
                <td>&euro;1,800</td>
                <td>per annum</td>
            </tr>

            <tr>
                <td>10Gbit/s port</td>
                <td>&euro;9,600</td>
                <td>&euro;7,200</td>
                <td>&euro;7,200</td>
                <td>per annum</td>
            </tr>
        </table>
    </div>
</div>

<br /><br />
<h4>Miscellaneous Charges</h4>
<br /><br />

<div class="row-fluid">
    <div class="span9">
        <table class="table">
            <tr>
                <th width="75%" >Description</th>
                <th>Charge</th>
            </tr>

            <tr>
                <td>Private Interconnection link within INEX Cage</td>
                <td>&euro;120 p.a.</td>
            </tr>

            <tr>
                <td>Private Interconnection link to external cross-connect</td>
                <td>&euro;240 p.a.</td>
            </tr>

            <tr>
                <td>Installation fee for long-haul (ZX/ER) optical ethernet link</td>
                <td>&euro;1,000 once off</td>
            </tr>

            <tr>
                <td>Rack space in INEX colocation cages above 3U</td>
                <td>&euro;240 p.a. per U</td>
            </tr>

            <tr>
                <td>Private VLAN between two members</td>
                <td>&euro;240 p.a. per party</td>
            </tr>

        </table>
    </div>
</div>

<br /><br />
<h4>Notes</h4>
<br /><br />
<ul>
    <li> Free second 100Mbps port only applicable to connections to the secondary peering LAN. </li>
    <li> Private Interconnections may only be installed between INEX members. Each party is liable to the charge noted in the table above. </li>
    <li> Port and private interconnect charges are not applicable to Associate Members, as associate members have no connectivity entitlements. </li>
    <li> There is no port connection charge, except for ZX gigabit and ER ten gigabit links </li>
    <li> VAT is charged on invoices to Irish based companies at the prevailing rate at the time of invoice (from January 2012: 23%).
</ul>



</div>




{tmplinclude file="footer.phtml"}
