{tmplinclude file="header.phtml"}

{if $user->getPrivs() eq 3}
    <ul class="breadcrumb">
        <li>
            <a href="{genUrl}">Home</a> <span class="divider">/</span>
        </li>
        <li>
            Documentation <span class="divider">/</span>
        </li>
        <li class="active">
            Membership Fees and Charges
        </li>
    </ul>

    <div>
{else}
    <div class="page-content">
        <div class="page-header">
            <h1>Membership Fees and Charges</h1>
        </div>
{/if}

<p>
INEX is a member supported organisation and operates on a not-for-profit basis.
Revenue for the organisation comes from two primary sources, membership fees and
port charges.
</p>

<h3>2016 Fees and Charges</h3>

<br /><br />
<h4>Membership Fees</h4>

<br /><br />

<div class="row-fluid">
    <div class="span9">
        <table class="table">
        <tr>
            <th width="75%" >Description</th>
            <th>Charge</th>
        </tr>

        <tr>
            <td>Associate Membership</td>
            <td>&euro;1,000 p.a.</td>
        </tr>

        <tr>
            <td>Full Membership</td>
            <td>&euro;1,000 p.a.</td>
        </tr>

        <tr>
            <td>Joining Fee</td>
            <td>No charge</td>
        </tr>
        </table>
    </div>
</div>


<br /><br />
<h4>Port Charges</h4>
<br /><br />

<div class="row-fluid">
    <div class="span9">
        <table class="table">
            <tr>
                <th width="30%">Description</th>
                <th>First LAN1 Port</th>
                <th>First LAN2 Port</th>
                <th>Subsequent Ports&nbsp;&nbsp;&nbsp;&nbsp;</th>
                <th>Term</th>
            </tr>

            <tr>
                <td>100Mbit/s<sup>1</sup></td>
                <td>&euro;0</td>
                <td>N/A&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</td>
                <td>N/A</td>
                <td>per annum</td>
            </tr>

            <tr>
                <td>1Gbit/s</td>
                <td>&euro;1,800<sup>2</sup>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</td>
                <td>&euro;0</td>
                <td>&euro;1,350</td>
                <td>per annum</td>
            </tr>

            <tr>
                <td>10Gbit/s</td>
                <td>&euro;8,400<sup>2</sup></td>
                <td>&euro;6,300</td>
                <td>&euro;6,300</td>
                <td>per annum</td>
            </tr>
        </table>
        <br />
        <div class="small">
            1. &quot;100Mbit&quot; ports are provisioned on a 1Gbit/s physical port. When 
               the measured maximum traffic level regularly exceeds 100Mbit/s over a period 
               of three months, the 1Gbit/s port charge is invoiced. Occasional spikes over 
               100Mbit/s are not counted.<br />
            2. Includes free 1Gbit/s port on INEX LAN2.
        </div>
    </div>
</div>



<br /><br />
<h4>Miscellaneous Charges</h4>
<br /><br />

<div class="row-fluid">
    <div class="span9">
        <table class="table">
            <tr>
                <th width="75%" >Description</th>
                <th>Charge</th>
            </tr>

            <tr>
                <td>Private Interconnection link within INEX Cage</td>
                <td>&euro;120 p.a.</td>
            </tr>

            <tr>
                <td>Private Interconnection link to external cross-connect</td>
                <td>&euro;240 p.a.</td>
            </tr>

            <tr>
                <td>10G ER (40km) Ethernet installation charge</td>
                <td>&euro;1,000 once off</td>
            </tr>

            <tr>
                <td>Rack space in INEX colocation cages above 3U</td>
                <td>&euro;240 p.a. per U</td>
            </tr>

            <tr>
                <td>Private VLAN between two members</td>
                <td>&euro;240 p.a. per party</td>
            </tr>

        </table>
    </div>
</div>

<br /><br />
<h4>Service Notes</h4>
<br /><br />
<ul>
    <li> Free port offers on INEX LAN2 are only applicable when a port of 1Gb or larger is maintained on INEX LAN1. </li>
    <li> Initial port connection charge applies only to 10G links which require ER/ZR transceivers. </li>
    <li> Second and subsequent ports may be ordered on LAN1 or LAN2. Multiple ports on the same LAN can be configured separately using different IP addresses, or may be bonded together using IEEE 802.3ad link aggregation with LACP signalling. </li>
    <li> Link aggregation is not supported for 100Mbit/s connections.  No more than three 1G ports may be bundled into a single link aggregate. </li>
    <li> Private interconnections may only be installed between full members of INEX. Each party is liable to the private interconnection charge noted in the table above. </li>
    <li> Associate Members are not entitled to connectivity services at INEX.</li>
</ul>

                                                                       

</div>




{tmplinclude file="footer.phtml"}
