<li class="pull-right" style="margin-top: -12px;">
<div class="btn-toolbar" style="display: inline-block;">

    <div class="btn-group">
        <a class="btn btn-mini dropdown-toggle" data-toggle="dropdown" href="#">
            {if $action eq 'op-status'}
                Live Port States (with SNMP poll)
            {else if $action eq 'list'}
                Ports (database only)
            {else if $action eq 'snmp-poll'}
                Ports (with SNMP poll)
            {else if $action eq 'list-mau'}
                Port MAU Detail (database only)
            {else}
                Unknown action?
            {/if}
            <span class="caret"></span>
        </a>
        <ul class="dropdown-menu pull-right">
            <li {if $action eq 'op-status'}class="active"{/if}>
                <a href="{genUrl controller='switch-port' action='op-status' switch=$sid}">View Live Port States (with SNMP poll)</a>
            </li>
            <li {if $action eq 'list'}class="active"{/if}>
                <a href="{genUrl controller='switch-port' action='list'      switch=$sid}">View / Edit Ports (database only)</a>
            </li>
            <li {if $action eq 'snmp-poll'}class="active"{/if}>
                <a href="{genUrl controller='switch-port' action='snmp-poll' switch=$sid}">View / Edit Ports (with SNMP poll)</a>
            </li>
        </ul>
    </div>

    <div class="btn-group">
        <a class="btn btn-mini dropdown-toggle" data-toggle="dropdown" href="#">
            {if isset( $sid ) and $sid}{$switches.$sid}{else}Limit to switch...{/if}
            <span class="caret"></span>
        </a>
        <ul class="dropdown-menu pull-right">
            {foreach $switches as $sid => $sname}
                <li> <a href="{genUrl controller='switch-port' action=$action switch=$sid}">{$sname}</a> </li>
            {/foreach}
        </ul>
    </div>
</div>
</li>
