<li class="pull-right" style="margin-top: -12px;"> 
<div class="btn-toolbar" style="display: inline-block;">

    <div class="btn-group">
        <a class="btn btn-mini dropdown-toggle" data-toggle="dropdown" href="#">
            {if isset( $sid ) and $sid}{$switches.$sid}{else}Limit to switch...{/if}
            <span class="caret"></span>
        </a>
        <ul class="dropdown-menu">
            {foreach $switches as $sid => $sname}
                <li> <a href="{genUrl controller='switch-port' action='list' switch=$sid}">{$sname}</a> </li>
            {/foreach}
        </ul>
    </div>

    <div class="btn-group">
        <a class="btn btn-mini" href="{genUrl controller='switch-port' action="add"}"><i class="icon-plus"></i></a>
    </div>
</div>
</li>
