{tmplinclude file="header.phtml"}

<ul class="breadcrumb">
    <li>
        <a href="{genUrl}">Home</a> <span class="divider">/</span>
    </li>
    <li>
        <a href="{genUrl controller='switch' action='list'}">Switches</a> <span class="divider">/</span>
    </li>
    <li class="active">
        SNMP Poll <em>{$switch->getName()}</em>
    </li>
    
    {tmplinclude file='switch-port/list-toolbar.phtml'}
</ul>

{OSS_Message}

<form id="poll-actions" method="post">
    <table class="table table-hover">
        <thead>
            <tr>
                <th></th>
                <th>Name</th>
                <th>Customer</th>
                <th>Description</th>
                <th>Alias</th>
                <th>Active</th>
                <th>Type</th>
                <th></th>
            </tr>
        </thead>
        {foreach $portsData as $pd }
            <tr id="poll-tr-{$pd.port->getId()}">
                <td><input type="checkbox" name="switch-port[{$pd.port->getId()}]" id="switch-port-{$pd.port->getId()}" value="{$pd.port->getId()}" /></td>
                <td>{$pd.port->getIfName()}</td>
                <td>
                    {if $pd.port->getPhysicalInterface()}
                        {$cust = $pd.port->getPhysicalInterface()->getVirtualInterface()->getCustomer()}
                        <a href="{genUrl controller='customer' action='overview' id=$cust->getId() tab='ports'}">{$cust->getShortname()}</a>
                    {/if}
                </td>
                <td>{$pd.port->getName()}</td>
                <td>{$pd.port->getIfAlias()}</td>
                <td><i class="icon-{if $pd.port->getActive()}ok{else}remove{/if}"></i></td>
                <td>
                    <div style="float: left;">
                    <select id="port-type-{$pd.port->getId()}" class="chzn-select" style="width: 150px;">
                        {foreach $portTypes as $idx => $name}
                            <option value="{$idx}" label="{$name}" {if $pd.port->getType() == $idx}selected="selected"{/if}>{$name}</option>
                        {/foreach}
                    </select></div>
                    <div id="port-type-state-{$pd.port->getId()}" style="float: left; padding: 2px 0px 0px 5px; width: 20px;"></div>
                </td>
                <td>
                    {if $pd.bullet ==  "new"}
                        <span class="badge badge-success">New</span>
                    {else if $pd.bullet ==  "db"}
                        <span class="badge badge-important">DB Only</span>
                    {/if}
                </td>
            </tr>
        {foreachelse}
            <tr align="center"><td colspan="6"><strong>SNMP polling information failed or there are no Ethernet ports on this switch</strong></td></tr>
        {/foreach}
        <tr>
            <td colspan="6">
                {if count( $portsData )}
                    <br />
                    With selected: <a href="#" id="poll-group-delete">Delete</a> | <a href="#" id="poll-group-type">Set type: </a>
                                <select name="shared-type" id="shared-type" class="chzn-select" style="width: 150px;">
                                    {foreach $portTypes as $idx => $name}
                                        <option value="{$idx}" label="{$name}">{$name}</option>
                                    {/foreach}
                                </select>
                                | <a href="#" id="poll-group-active">Set Active</a> | <a href="#" id="poll-group-inactive">Set Inactive</a>
                    <br />
                    <a href="#" id="poll-select-all">Select All</a> | <a href="#" id="poll-select-none">Deselect All</a> | <a href="#" id="poll-select-inverse">Inverse</a>
                    <input name="poll-action" id="poll-action" type="hidden" />
                {/if}
            </td>
        </tr>
    </table>
    
</from>

<script type="text/javascript">
    {tmplinclude file="switch-port/js/snmp-poll.js"}
</script>

{tmplinclude file="footer.phtml"}
