<h3>Notes / Instructions</h3>

<dl>
    <dt>Peering Matrix</dt>
    <dd>
        Selecting this checkbox means that this VLAN will appear on the
        <a href="{genUrl controller='peering-matrix'}" target="_blank">peering matrix</a>.
        Note that this does not mean that this matrix will be populated. For that, you
        need to <a href="https://github.com/inex/IXP-Manager/wiki/Peering-Matrix">configure
        sflow support for this</a>.
    </dd>
    <dt>Peering Manager</dt>
    <dd>
        Selecting this checkbox means that this VLAN will appear on the members'
        peering manager. Note that this does not mean that it will be populated. For that, you
        need to <a href="https://github.com/inex/IXP-Manager/wiki/Peering-Manager">configure
        sflow support for this</a>.
    </dd>
</dl>
