{tmplinclude file="header.phtml"}

<ul class="breadcrumb">
    <li>
        <a href="{genUrl}">Home</a> <span class="divider">/</span>
    </li>
    <li>
        <a href="{genUrl controller='vlan' action='private'}">VLANs</a> <span class="divider">/</span>
    </li>
    <li class="active">
        Private VLAN Details
    </li>
</ul>


{if isset( $infra ) and $infra}

<div class="row-fluid">
    <div class="alert alert-info">
        Only showing private VLANs for: <strong>{$infra->getName()}</strong>.
        <span class="pull-right">
            <a href="{genUrl controller='vlan' action='private'}" class='btn btn-small'>Show All</a>
        </span>
    </div>
</div>

{/if}


<div class="row-fluid">

    <div class="span12">

        <table class="table">

            <thead>

                <th>VLAN Name</th>
                <th>Tag</th>
                {if $multiIXP}
                    <th>IXP</th>
                {/if}
                <th>Infrastructure</th>
                <th>Members</th>
                <th>Locations</th>
                <th>Switches</th>

            </thead>

            <tbody>

                {foreach $pvs as $pv}

                    <tr>
                        <td>{$pv.name}</td>
                        <td>{$pv.number}</td>
                        {if $multiIXP}
                            <td>{if isset( $pv.ixp )}{$pv.ixp}{/if}</td>
                        {/if}
                        <td>{if isset( $pv.infrastructure )}{$pv.infrastructure}{/if}</td>
                        <td>
                            {foreach $pv.members as $custid => $cust}
                                <a href="{genUrl controller="customer" action="overview" id=$custid}">{$cust.name}</a>
                                (<a href="{genUrl controller="virtual-interface" action="edit" id=$cust.vintid}">interface details</a>)<br />
                                {if count( $pv.members.$custid.locations ) > 1 }
                                    {for $i=2 to count( $pv.members.$custid.locations ) }
                                        <br />
                                    {/for}
                                {/if}
                            {/foreach}
                        </td>
                        <td>
                            {foreach $pv.members as $custid => $cust}
                                {foreach $cust.locations as $l}
                                    {$l}<br />
                                {/foreach}
                            {/foreach}
                        </td>
                        <td>
                            {foreach $pv.members as $custid => $cust}
                                {foreach $cust.switches as $s}
                                    {$s}<br />
                                {/foreach}
                            {/foreach}
                        </td>
                    </tr>

                {/foreach}

            </tbody>


        </table>


    </div>

</div>


{tmplinclude file="footer.phtml"}
