{if isset( $hasIdentity ) and $hasIdentity}
    {tmplinclude file="header.phtml" mode="fluid"}
{else}
    {tmplinclude file="header.phtml" mode="fluid" brand="{$options.identity.orgname} - {$options.identity.name} - Peering Matrix"}
{/if}

<ul class="breadcrumb">
    <li>
        <a href="{genUrl}">Home</a> <span class="divider">/</span>
    </li>
    <li>
        <a href="{genUrl}">Peering Matrices</a>
    </li>
    <li class="active">
        for the {$vlans.$vid} using {$protos.$proto}
    </li>

    <li class="pull-right">
        <div class="btn-toolbar" style="display: inline; margin-top: -12px;">
            <div class="btn-group" id="peer-btn-group">
                <a class="btn btn-mini dropdown-toggle" data-toggle="dropdown" id="peer-dd" >
                    <span id="peer-dd-text">All Peerings</span>
                    <span class="caret"></span>
                </a>
                <ul id="peer-dd-ul" class="dropdown-menu">
                    <li> <a id="peer-filter-all" >All Peerings</a> </li>
                    <li> <a id="peer-filter-bi">Bilateral Peerings</a> </li>
                    <li> <a id="peer-filter-rs">Route Server Peerings</a> </li>
                </ul>
            </div>
            {if count( $vlans ) > 1}
                <div class="btn-group">
                    <a class="btn btn-mini dropdown-toggle" data-toggle="dropdown" href="#">
                        {$vlans.$vid}
                        <span class="caret"></span>
                    </a>
                    <ul class="dropdown-menu">
                        {foreach $vlans as $id => $vname}
                            <li> <a href="{genUrl controller="peering-matrix" action="index" vid=$id proto=$proto}">{$vname}</a> </li>
                        {/foreach}
                    </ul>
                </div>
            {/if}
            <div class="btn-group">
                <a class="btn btn-mini dropdown-toggle" data-toggle="dropdown" href="#">
                    {$protos.$proto}
                    <span class="caret"></span>
                </a>
                <ul class="dropdown-menu">
                    {foreach from=$protos key=id item=name}
                        <li> <a href="{genUrl controller="peering-matrix" action="index" vid=$vid proto=$id}">{$name}</a> </li>
                    {/foreach}
                </ul>
            </div>
            <div class="btn-group">
                <button id="btn-zoom-out" class="btn btn-mini"><i class="icon-zoom-out"></i></button>
                <button id="btn-zoom-in"  class="btn btn-mini"><i class="icon-zoom-in"></i></button>
            </div>
        </div>
    </li>
</ul>

<div class="row-fluid">



<table id="table-pm" class="pm-table">

<colgroup id="cg-name"></colgroup>
<colgroup id="cg-asn"></colgroup>
{foreach from=$custs key=x_as item=peers}
    <colgroup id="cg-as-{$x_as}"></colgroup>
{/foreach}

<thead>

    <tr>

        <th id="th-name" class="name zoom3"></th>
        <th id="th-asn" class="asn zoom3"></th>

        {foreach from=$custs key=x_as item=peers}

            <th id="th-as-{$x_as}" class="zoom3 asn">
                {assign var=asn value=$x_as|string_format:$asnStringFormat}
                {assign var=len value=strlen( $asn )}
                {for $pos=0 to $len}
                    {$asn|truncate:1:''}{if $pos < $len}<br />{/if}
                    {assign var=asn value=substr( $asn, 1 )}
                {/for}
            </th>

        {/foreach}

    </tr>

</thead>

<tbody id="tbody-pm" class="zoom3">

{assign var=outer value=0}

{foreach from=$custs key=x_as item=x}


	<tr id="tr-name-{$x_as}">

	    <td id="td-name-{$x_as}" class="name zoom3">{$x.name|replace:" ":"&nbsp;"}</td>
	    <td id="td-asn-{$x_as}" class="asn zoom3">{$x.autsys}</td>

        {assign var=inner value=0}

	    {foreach from=$custs key=y_as item=y}

		    <td id="td-{$x_as}-{$y_as}" class="col-yasn-{$y_as} peering
		        {if $y.autsys neq $x.autsys}
    		        {if isset( $sessions.$x_as.peers.$y_as ) and $x.rsclient and $y.rsclient}
    		             peered bilateral-rs
		            {else if isset( $sessions.$x_as.peers.$y_as )}
    		             peered bilateral-only
    		        {else if $x.rsclient and $y.rsclient}
    		             peered rs-only
    	            {else}
    		            not-peered
    		        {/if}
		        {/if}
		        zoom3">
		    </td>

        {assign var=inner value=$inner+1}

        {* for the last cell of the last row, we add a empty cell *}
        {if $outer eq $custs|@count and $inner eq $custs|@count}
            <td></td>
        {/if}
	    {/foreach}

	</tr>

{assign var=outer value=$outer+1}

{/foreach}

</tbody>

</table>

<div class="row-fluid" style="margin-top: 40px;">

    <div class="span2">&nbsp;</div>

    <div class="span8">

        <div class="well">

            <h3>Notes on the Peering Matrix</h3>

            <ul>
                <li>
                    Clicking the AS number in the table header will isolate that column. Clicking individual
                    cells in the body will freeze the dynamic highlighting.
                </li>
                <li>
                    Where a {$options.identity.orgname} member is not listed on this peering matrix, it is because they are
                    currently not actively peering at {$options.identity.orgname}, or because they have opted out of presenting
                    their peering information in this database.
                </li>
                <li>
                    This peering matrix is based on sflow traffic accounting data from the {$options.identity.orgname} peering
                    LANs and route server BGP peerings.
                </li>
                <li>
                    This peering matrix only detects if there is bidirectional TCP flow between routers at
                    {$options.identity.orgname}. It cannot detect whether there are actually prefixes swapped between routers.
                </li>
            </ul>

        </div>

    </div>

    <div class="span2">&nbsp;</div>

</div>

{if isset( $user ) and $user->getPrivs() eq 3}
</div>
{/if}

<script type="text/javascript">
{tmplinclude file="peering-matrix/index.js"}
</script>

{tmplinclude file="footer.phtml"}
