#!/usr/bin/perl
#
# control-sflow-to-rrd-handler
#
# Copyright (C) 2009-2013 Internet Neutral Exchange Association Limited.
# All Rights Reserved.
# 
# This file is part of IXP Manager.
# 
# IXP Manager is free software: you can redistribute it and/or modify it
# under the terms of the GNU General Public License as published by the Free
# Software Foundation, version v2.0 of the License.
# 
# IXP Manager is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or   
# FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License for
# more details.
# 
# You should have received a copy of the GNU General Public License v2.0
# along with IXP Manager.  If not, see:
# 
# http://www.gnu.org/licenses/gpl-2.0.html
#
# Description:
#
# startup script for sflow-to-rrd-handler.

use warnings;
use strict;
use Daemon::Control;

Daemon::Control->new({
	name		=>	"control-sflow-to-rrd-handler",
	lsb_start	=>	'$syslog $remote_fs',
	lsb_stop	=>	'$syslog',
	lsb_sdesc	=>	'Sflow control daemon',
	lsb_desc	=>	'Controller for the sflow-to-rrd-daemon.',
	path		=>	'/usr/local/sbin',
	program		=>	'sflow-to-rrd-handler',
	program_args	=>	[],
	pid_file	=>	'/var/run/sflow-to-rrd-handler.pid',
	fork		=>	2,
})->run;
