#!/usr/bin/perl
#
# control-sflow-detect-ixp-bgp-sessions
#
# Copyright (C) 2009-2016 Internet Neutral Exchange Association Company Limited By Guarantee.
# All Rights Reserved.
# 
# This file is part of IXP Manager.
# 
# IXP Manager is free software: you can redistribute it and/or modify it
# under the terms of the GNU General Public License as published by the Free
# Software Foundation, version v2.0 of the License.
# 
# IXP Manager is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or   
# FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License for
# more details.
# 
# You should have received a copy of the GNU General Public License v2.0
# along with IXP Manager.  If not, see:
# 
# http://www.gnu.org/licenses/gpl-2.0.html
#
# Description:
#
# startup script for sflow-detect-ixp-bgp-sessions

use warnings;
use strict;
use Daemon::Control;

my $progname = 'sflow-detect-ixp-bgp-sessions';

Daemon::Control->new({
	name		=>	"control-$progname",
	lsb_start	=>	'$syslog $remote_fs',
	lsb_stop	=>	'$syslog',
	lsb_sdesc	=>	"BGP session sflow control daemon",
	lsb_desc	=>	"Controller for $progname",
	path		=>	"/usr/local/bin/$progname",
	program		=>	"/usr/local/bin/$progname",
	program_args	=>	[],
	pid_file	=>	"/var/run/$progname.pid",
	fork		=>	2,
})->run;
