


<table class="table table-bordered table-striped">

    <thead>
        <tr>
            <th>Member</th>
            <th>ASN</th>
            <th>Policy</th>

            {foreach $vlans as $vlan}

                {if isset( $me[ 'vlaninterfaces' ][ $vlan->getNumber() ] )}
                    <th>{$vlan->getName()}</th>
                {/if}

            {/foreach}

            <th></th>
        </tr>
    </thead>

    <tbody>

        {foreach from=$listOfCusts key=as item=p}

            {assign var=c value=$custs.$as}
            {assign var=cid value=$c.id}

            {if $p}
            <tr>
                <td id="peer-name-{$cid}">{$c.name}</td>
                <td>{$c.autsys}</td>
                <td>{$c.peeringpolicy}</td>

                {foreach $vlans as $avlan}
                    {$vlan = $avlan->getNumber()}
                    {if isset( $c.$vlan )}
                        <td>
                            {foreach from=$protos item=proto}
                                {if isset( $c.$vlan.$proto )}
                                    {if $c.$vlan.$proto}
                                        <span class="badge badge-success">IPv{$proto}</span>
                                    {else}
                                        <span class="badge badge-important">IPv{$proto}</span>
                                    {/if}
                                {/if}
                            {/foreach}
                        </td>
                    {elseif isset( $me.vlaninterfaces.$vlan )}
                        <td></td>
                    {/if}
                {/foreach}

                <td width="220px">
                    <div class="btn-group">
                        <button id="peering-request-{$cid}"
                                data-days="{if isset( $peers.$cid )}{$peers.$cid.email_days}{else}-1{/if}"
                                class="btn btn-mini {if not $c.ispotential}disabled" disabled="disabled{/if}">
                            <i id="peering-request-icon-{$cid}"
                                class="{if isset( $peers.$cid.emails_sent ) and $peers.$cid.emails_sent}icon-repeat{else}icon-envelope{/if}"></i> Request Peering
                        </button>
                        <button id="peering-notes-{$cid}" class="btn btn-mini">
                            <i id="peering-notes-icon-{$cid}" class="{if isset( $peers.$cid.notes ) and strlen( $peers.$cid.notes )}icon-star{else}icon-star-empty{/if}"></i> Notes
                        </button>
                        <button class="btn btn-mini {if isset( $peers.$cid ) and ( $peers.$cid.peered or $peers.$cid.rejected )}btn-info{/if} dropdown-toggle" data-toggle="dropdown">
                            <span class="caret"></span>
                        </button>
                        <ul class="dropdown-menu">
                            <li>
                                <a href="{genUrl controller="peering-manager" action="mark-peered" custid=$cid}">
                                    {if isset( $peers.$cid ) and $peers.$cid.peered}
                                        Unmark as Peered
                                    {else}
                                        Move to Peered
                                    {/if}
                                </a>
                            </li>
                            <li>
                                <a href="{genUrl controller="peering-manager" action="mark-rejected" custid=$cid}">
                                    {if isset( $peers.$cid ) and $peers.$cid.rejected}
                                        Unmark as Rejected / Ignored
                                    {else}
                                        Move to Rejected / Ignored
                                    {/if}
                                </a>
                            </li>
                        </ul>
                    </div>
                </td>
            </tr>
            {/if}

        {/foreach}

    </tbody>
</table>
