
Dear {$peer->getName()} Peering Team,

We are {$user->getCustomer()->getName()} ({$user->getCustomer()->getCorpwww()}) and we are fellow members of {$options.identity.orgname} ({$options.identity.location.city}, {$options.identity.location.country}).

We would like to arrange peering session(s) with you on the following interface(s):

{foreach $pp as $p}

{assign value=$p.my var='pmy'}
{assign value=$p.your var='pyour'}

{$pmy->getVlan()->getName()|underline}

{if $pmy->getIpv4enabled() and $pyour->getIpv4enabled()}
Our IPv4 Address: {$pmy->getIpv4address()->getAddress()}
{if $pmy->getIpv6enabled() and $pyour->getIpv6enabled()}
Our IPv6 Address: {$pmy->getIpv6address()->getAddress()}
{/if}
Our AS Number:    {$user->getCustomer()->getAutsys()}
{if $user->getCustomer()->getPeeringmacro()}Our AS Macro:     {$user->getCustomer()->getPeeringmacro()}
{/if}

Your IPv4 Address: {$pyour->getIpv4address()->getAddress()}
{if $pmy->getIpv6enabled() and $pyour->getIpv6enabled()}
Your IPv6 Address: {$pyour->getIpv6address()->getAddress()}
{/if}
Your AS Number:    {$peer->getAutsys()}
{/if}

{/foreach}


{"NOC Details for "|cat:$user->getCustomer()->getName()|underline:"="}

The following are our NOC details for your reference:

NOC Hours:     {$user->getCustomer()->getNochours()}
NOC Phone:     {$user->getCustomer()->getNocphone()}
{if $user->getCustomer()->getNoc24hphone()}NOC 24h Phone: {$user->getCustomer()->getNoc24hphone()}
{/if}
{if $user->getCustomer()->getNocfax()}NOC Fax:       {$user->getCustomer()->getNocfax()}
{/if}
NOC Email:     {$user->getCustomer()->getNocemail()}
{if $user->getCustomer()->getNocwww()}NOC WWW:       {$user->getCustomer()->getNocwww()}{/if}


Kind regards,
The {$user->getCustomer()->getName()} Peering Team


--

This email was composed with the assistance of the {$options.identity.orgname} Peering Manager which is part of your members' area at: {genUrl}.
