

<div class="alert alert-block alert-info fade in" id="oss-message-0">
    <a class="close" href="#" data-dismiss="alert">×</a>
    <h4>Use of this method is discouraged!</h4>

    It is possible to add switches without SNMP polling but this is strongly discouraged as SNMP is built heavily into the switch and switch port management.

    <br>
    Please consider using <a href="{genUrl controller='switch' action='add-by-snmp'}">the SNMP method to add switches</a>.
</div>
