{tmplinclude file="header.phtml"}

<ul class="breadcrumb">
    <li>
        <a href="{genUrl}">Home</a> <span class="divider">/</span>
    </li>
    <li>
        <a href="{genUrl controller='switch' action='list'}">Switches</a> <span class="divider">/</span>
    </li>
    <li class="active">
        Add New Switch (via SNMP)
    </li>
    
    <li class="pull-right">
        <div class="btn-group">
            <a class="btn btn-mini" href="{genUrl module=$module controller=$controller action='list'}"><i class="icon-list"></i></a>
        </div>
    </li>
</ul>

<div>

{OSS_Message}

<p>
    Please complete the details below and click next. The hostname and SNMP community
    entered below will be used to poll the switch for its details.
</p>

{$f}
    
    
</div>

{tmplinclude file="footer.phtml"}