{tmplinclude file="header.phtml"}

{if isset( $user ) and $user->getPrivs() eq USER::AUTH_SUPERUSER}
    <ul class="breadcrumb">
        <li>
            <a href="{genUrl}">Home</a> <span class="divider">/</span>
        </li>
        <li>
            <a href="{genUrl controller="switch" action="list"}">Switches</a> <span class="divider">/</span>
        </li>
        <li class="active">
            Configuration
        </li>

        <li class="pull-right">
            <form class="form-inline" method="post">
                {if $multiIXP}
                    <select data-placeholder="Limit to IXP..." class="chzn-select" name="ixp">
                        <option></option>
                        {foreach $ixps as $iid => $iname}
                            <option value="{$iid}" {if isset( $ixpid ) and $ixpid eq $iid}selected="selected"{/if}>{$iname}</option>
                        {/foreach}
                    </select>
                {/if}
                <select data-placeholder="Limit to switch..." class="chzn-select-deselect" name="sid">
                    <option></option>
                    {foreach $switches as $sid => $sname}
                        <option value="{$sid}" {if isset( $switchid ) and $switchid eq $sid}selected="selected"{/if}>{$sname}</option>
                    {/foreach}
                </select>

                {if count( $vlans ) > 1}
                    <select data-placeholder="Limit to peering LAN..." class="chzn-select-deselect" name="vid">
                        <option></option>
                        {foreach $vlans as $vid => $vname}
                            <option value="{$vid}" {if isset( $vlanid ) and $vlanid eq $vid}selected="selected"{/if}>{$vname}</option>
                        {/foreach}
                    </select>
                {/if}

                <button type="submit" class="btn btn-small" style="display: inline-block; position: relative;" >Update</button>
            </form>
        </li>
    </ul>

    <div>
{else}
    <div class="page-content" >

        <div class="page-header" >
            <h1 style="display: inline;">Switch Configuration</h1>

            <span style="float: right; margin-top: -10px;">
                <form class="form-inline" method="post">
                    {if $multiIXP && count( $ixps ) > 1 }
                        <select data-placeholder="Limit to IXP..." class="chzn-select" name="ixp">
                            <option></option>
                            {foreach $ixps as $iid => $iname}
                                <option value="{$iid}" {if isset( $ixpid ) and $ixpid eq $iid}selected="selected"{/if}>{$iname}</option>
                            {/foreach}
                        </select>
                    {/if}

                    <select data-placeholder="Limit to switch..." class="chzn-select-deselect" name="sid">
                        <option></option>
                        {foreach $switches as $sid => $sname}
                            <option value="{$sid}" {if isset( $switchid ) and $switchid eq $sid}selected="selected"{/if}>{$sname}</option>
                        {/foreach}
                    </select>

                    {if count( $vlans ) > 1}
                        <select data-placeholder="Limit to peering LAN..." class="chzn-select-deselect" name="vid">
                            <option></option>
                            {foreach $vlans as $vid => $vname}
                                <option value="{$vid}" {if isset( $vlanid ) and $vlanid eq $vid}selected="selected"{/if}>{$vname}</option>
                            {/foreach}
                        </select>
                    {/if}

                    <button type="submit" class="btn btn-small" style="display: inline-block; position: relative;" >Update</button>
                </form>
            </span>
        </div>
{/if}

    {OSS_Message}

    <table id='frontend-list-table' class="table table-bordered">

    <thead>
        <tr>
            <th>Customer</th>
            {if not isset( $switchid )}<th>Switch</th>{/if}
            <th>Port</th>
            <th>Speed</th>
            {if not isset( $vlanid ) and count( $vlans ) > 1}<th>Peering LAN</th>{/if}
            <th>ASN</th>
            <th>Route Server</th>
            <th>IPv4</th>
            <th>IPv6</th>
            <th>Status</th>
        </tr>
    </thead>

    <tbody>
        {foreach $config as $idx => $row}
            <tr>
                <td>
                    {if $user->getPrivs() eq USER::AUTH_SUPERUSER}
                        <a href="{genUrl controller="customer" action="view" id=$row.custid}">{$row.customer}</a>
                    {else}
                        <a href="{genUrl controller="customer" action="detail" id=$row.custid}">{$row.customer}</a>
                    {/if}
                </td>
                {if not isset( $switchid )}
                    <td>
                        {if $user->getPrivs() eq USER::AUTH_SUPERUSER}
                            <a href="{genUrl controller="switch" action="port-report" id=$row.switchid}">{$row.switchname}</a>
                        {else}
                            <a href="{genUrl controller="switch" action="configuration" sid=$row.switchid}">{$row.switchname}</a>
                        {/if}
                    </td>
                {/if}
                <td>{$row.ifName}</td>
                <td>{$row.speed}</td>
                {if not isset( $vlanid ) and count( $vlans ) > 1}<td>{$row.vlan}</td>{/if}
                <td>{$row.asn|asnumber}</td>
                <td>{if $row.rsclient}Yes{else}No{/if}</td>
                <td>{$row.ipv4address}</td>
                <td>{$row.ipv6address}</td>
                <td>{if isset( $states[ $row.portstatus ] )}{$states[ $row.portstatus ]}{/if}</td>
            </tr>
        {/foreach}
    </tbody>

    </table>
</div>

<script type="text/javascript">
{tmplinclude file="switch/js/configuration.js"}
</script>
{tmplinclude file="footer.phtml"}
