<li class="pull-right"  style="margin-top: -6px;">
<div class="btn-toolbar" style="display: inline;">

    <div class="btn-group">
        {if $action eq 'os-view'}
            <a class="btn btn-mini pull-right" href="{genUrl controller=$controller action="list"}">Standard View</a>
        {else}
            <a class="btn btn-mini pull-right" href="{genUrl controller=$controller action="os-view"}">OS View</a>
        {/if}
    </div>

    <div class="btn-group">
        <a class="btn btn-mini pull-right"
            href="https://github.com/inex/IXP-Manager/wiki/Switch-and-Switch-Port-Management"
            target="ixp-help">Help</a>
    </div>

    
    <div class="btn-group">
        <a class="btn btn-mini pull-right" href="{genUrl controller=$controller action="add-by-snmp"}"><i class="icon-plus"></i></a>
    </div>
</div>
</li>
