<div class="btn-group">
    <a class="btn btn-mini have-tooltip-below" href="{genUrl module=$module controller=$controller action='view' id=$row.id}" title="Preview"><i class="icon-eye-open"></i></a>
    <a class="btn btn-mini have-tooltip-below" href="{genUrl module=$module controller=$controller action='edit' id=$row.id}" title="Edit"><i class="icon-pencil"></i></a>
    <a class="btn btn-mini have-tooltip-below" id='list-delete-{$row.id}' href="{genUrl module=$module controller=$controller action='delete' id=$row.id}" title="Delete"><i class="icon-trash"></i></a>
    <a class="btn btn-mini dropdown-toggle" data-toggle="dropdown" href="#">
        More...
        <span class="caret"></span>
    </a>
    <ul class="dropdown-menu pull-right">
        {if $row.active}
            <li>
                <a href="{genUrl controller='switch-port' action='snmp-poll' switch=$row.id}">View / Edit Ports (with SNMP poll)</a>
            </li>
            <li>
                <a href="{genUrl controller='switch-port' action='op-status' switch=$row.id}">View Live Port States (with SNMP poll)</a>
            </li>
        {/if}
        <li>
            <a href="{genUrl controller='switch-port' action='list' switch=$row.id}">View / Edit Ports (database only)</a>
        </li>
        {if $row.mauSupported}
            <li>
                <a href="{genUrl controller='switch-port' action='list-mau' switch=$row.id}">View Port MAU Detail (database only)</a>
            </li>
        {/if}
        <li>
            <a href="{genUrl controller='switch' action='port-report' id=$row.id}">View Port Report</a>
        </li>
    </ul>
</div>
