<li class="pull-right"  style="margin-top: -6px;">
<div class="btn-toolbar" style="display: inline;">

    <div class="btn-group">
        <a class="btn btn-mini dropdown-toggle" data-toggle="dropdown" href="#">
            {if isset( $stype ) and $stype}Type: {$switchTypes.$stype}{else}Limit to type...{/if}
            <span class="caret"></span>
        </a>
        <ul class="dropdown-menu pull-right">
            <li {if not $stype}class="active"{/if}> 
                <a href="{genUrl controller='switch' action=$action stype=0}">All types</a> </li>
            <li class="divider"></li>
            {foreach $switchTypes as $stypeid => $stypename}
                <li {if $stype eq $stypeid}class="active"{/if}> <a href="{genUrl controller='switch' action=$action stype=$stypeid}">
                    {$stypename}</a> </li>
            {/foreach}
        </ul>
    </div>

    <div class="btn-group">
        {if $activeOnly}
            <a class="btn btn-mini pull-right" href="{genUrl controller=$controller action=$action activeOnly=0}">
                Include Inactive
            </a>
        {else}
            <a class="btn btn-mini pull-right" href="{genUrl controller=$controller action=$action activeOnly=1}">
                Show Active
            </a>
        {/if}
    </div>

    <div class="btn-group">
        {if $action eq 'os-view'}
            <a class="btn btn-mini pull-right" href="{genUrl controller=$controller action="list"}">Standard View</a>
        {else}
            <a class="btn btn-mini pull-right" href="{genUrl controller=$controller action="os-view"}">OS View</a>
        {/if}
    </div>

    <div class="btn-group">
        <a class="btn btn-mini pull-right"
            href="https://github.com/inex/IXP-Manager/wiki/Switch-and-Switch-Port-Management"
            target="ixp-help">Help</a>
    </div>

    
    <div class="btn-group">
        <a class="btn btn-mini pull-right" href="{genUrl controller=$controller action="add-by-snmp"}"><i class="icon-plus"></i></a>
    </div>
</div>
</li>
