{tmplinclude file="header.phtml"}

<ul class="breadcrumb">
    <li>
        <a href="{genUrl}">Home</a> <span class="divider">/</span>
    </li>
    <li>
        Route Server Prefixes <span class="divider">/</span>
    </li>
    <li class="active">
        Summary by Customer
    </li>
</ul>

{OSS_Message}

<div class="row-fluid">
    <div class="span12 tabbable">

    	<ul class="nav nav-tabs">
    	
			<li class="active">
			    <a href="#adv_nacc" data-toggle="tab">Advertised but Not Accepted</a>
			</li>
        
			<li>
			    <a href="#adv_acc" data-toggle="tab">Advertised &amp; Accepted</a>
			</li>
        
			<li>
			    <a href="#nadv_acc" data-toggle="tab">Not Advertised but Acceptable</a>
			</li>
        
        </ul>
        
        <div class="tab-content">
        
	        <div class="tab-pane active" id="adv_nacc">
	            {$type = "adv_nacc"}
	        	{tmplinclude file="rs-prefixes/table-summary.phtml"}
	        </div>
        
	        <div class="tab-pane" id="adv_acc">
	            {$type = "adv_acc"}
	            {tmplinclude file="rs-prefixes/table-summary.phtml"}
	        </div>
        
	        <div class="tab-pane" id="nadv_acc">
	            {$type = "nadv_acc"}
	            {tmplinclude file="rs-prefixes/table-summary.phtml"}
	        </div>
        
        </div>
    </div>
</div>
    
<script>{tmplinclude file="rs-prefixes/js/index.js"}</script>
{tmplinclude file="footer.phtml"}

