{tmplinclude file="header.phtml"}

<ul class="breadcrumb">
    <li>
        <a href="{genUrl}">Home</a> <span class="divider">/</span>
    </li>
    <li>
        <a href="{genUrl controller="rs-prefixes"}">Route Server Prefixes</a> <span class="divider">/</span>
    </li>
    <li class="active">
        {$cust->getName()} [{$cust->getAutsys()|asnumber}]
    </li>
</ul>

{OSS_Message}

<div class="row-fluid">
    <div class="span12">
    
    <table class="table">
        <thead>
            <th>Prefix</th>
            <th>Protocol</th>
            <th>Timestamp</th>
            {if $type eq 'adv_acc' or $type eq 'adv_nacc'}
                <th>Origin AS</th>
            {/if}
        </thead>
        <tbody>
            {foreach $routes as $r}
                <tr>
                    <td>{$r.prefix}</td>
                    <td>IPv{$r.protocol}</td>
                    <td>{$r.timestamp->format( 'Y-m-d H:i:s' )}</td>
                    {if $type eq 'adv_acc' or $type eq 'adv_nacc'}
                        <td>{$r.rsorigin|asnumber}</td>
                    {/if}
                </tr>
            {/foreach}
        </tbody>
    </table>
    
    </div>
</div>

{tmplinclude file="footer.phtml"}
