
Dear New INEX Member,

Firstly, welcome to INEX! This is your INEX welcome e-mail.

If you are unfamiliar with how IXPs work, please grab a cup of coffee and take some time to read this email -- it contains important information concerning your INEX membership.


Connection Details
==================

You have opted to connect to INEX using {$customer->getVirtualInterfaces()|@count} ports. We have assigned the following IP addresses and switch ports for your connections:

{foreach $customer->getVirtualInterfaces() as $connection}
============================================
Connection {counter name=numconnections}
============================================

LAG Port:        {if $connection->getPhysicalinterfaces()|@count > 1}Yes, comprising of:{else}No{/if}

802.1q Tagged:   {if $connection->getTrunk()}Yes{else}No{/if}

{foreach $connection->getPhysicalinterfaces() as $pi}
Switch Port:     {$pi->getSwitchPort()->getSwitcher()->getName()}.inex.ie, {$pi->getSwitchPort()->getName()}
Speed:           {$pi->resolveSpeed()} ({$pi->getDuplex()} duplex)
Location:        {$pi->getSwitchPort()->getSwitcher()->getCabinet()->getLocation()->getName()}
Colo Cabinet ID: {$pi->getSwitchPort()->getSwitcher()->getCabinet()->getName()}

{/foreach}

{foreach $connection->getVlanInterfaces() as $vi}
{$vlanid = $vi->getVlan()->getId()}
{$vi->getVlan()->getName()}
---------------------------------------------

{if $connection->getTrunk()}
802.1q Tag:    {$vi->getVLAN()->getNumber()}
{/if}

{if $vi->getIpv6enabled()}
IPv6 Address:  {$vi->getIPv6Address()->getAddress()}/{$netinfo.$vlanid.6.masklen}
IPv6 Hostname: {$vi->getIpv6hostname()}
{else}
IPv6:          Please contact us at {$options.identity.email} to enable IPv6
{/if}

{if $vi->getIpv4enabled()}
IPv4 Address:  {$vi->getIPv4Address()->getAddress()}/{$netinfo.$vlanid.4.masklen}
IPv4 Hostname: {$vi->getIpv4hostname()}
{else}
IPv4:          Please contact us at {$options.identity.email} to enable IPv4
{/if}

{/foreach}

{/foreach}


Member Portal :: IXP Manager
============================

INEX provides a portal for members which provides traffic graphs for your ports, peer to peer graphs (who much traffic you are sending and receiving from each member), the contact and peering details of all other members, a Peering Manager tool, documentation, support information, mailing list subscription management and much more.

Every member is assigned an administration account with which you then create individual user accounts. The administration account is only meant for this purpose and as such, all functionality is only available through user accounts.

{if $admins|@count}
We have created your administration account(s) with the following username(s) and email address(es):

{foreach $admins as $a}
  * {$a->getUsername()} <{$a->getEmail()}>
{/foreach}

Please browse to the following page and use the 'Lost Password' facility to set a new password for this account.

{genUrl controller="auth" action="lost-password"}
{else}
Please contact us for your account details at {$options.identity.email}.
{/if}



Route Servers
=============

INEX operates a Route Server cluster; this facility allows all members who connect to the cluster to see all routing prefixes sent to the cluster by any other member.  I.e. it provides a quick, safe and easy way to peer with any other route server user.

The service is designed to be reliable. It operates on two physical servers, each located in a different data centre. The service is available on all networks (public peering lans #1 and #2, and INEX Cork), on both ipv4 and ipv6.  The route servers also filter inbound routing prefixes based on published RIPE IRR policies, which means that using the route servers for peering is generally much safer than peering directly with other members.

See https://www.inex.ie/technical/route-servers/ for full details.

Your connection to the route servers will be brought live during standard provisioning of your new port(s).



External Connections to the {$options.identity.orgname} Infrastructure
===============================================

Cross-connect termination points are provided under separate cover including LoAs (letters of authority - normally required by data centres before they will install a cross connect to INEX).

Getting cross connects installed is normally the more common delay in bringing your new INEX service live. Please order it/them as soon as possible and from your co-lo / metro ethernet provider.

Please also notify INEX Operations once it is complete as we often do not get notified by the co-lo providers.



Mailing Lists
=============

To encourage co-operation between INEX members, INEX provides two mailing list services:

Name:                   tech@inex.ie
Purpose:                INEX technical discussion
Subscription Policy:    individuals, roles, aliases,
                        no limit per organisation
Distribution:           private

Name:                   members@inex.ie
Purpose:                Non-technical discussions relevant to INEX
Subscription Policy:    individuals only, no limit per organisation
Distribution:           private & confidential

Should you wish to subscribe to either or both mailing lists, please create a user account on the IXP Manager (as explained above) and then browse to the 'Profile' page where you can subscribe to the above and more mailing lists.



INEX Operations
===============

Technical support contact details for INEX can be found at:

        https://www.inex.ie/support/

In general, the best way to contact INEX operations is by email at: operations@inex.ie.  If there is a genuine emergency requiring immediate assistance, please use the 24/7 phone number listed on the web page.


Peering
=======

INEX facilitates peering between its members, but other than the minimum current peering requirements (2 other members per LAN) does not mandate peering with any particular member apart from INEX itself.

You will find a full list of members on the IXP Manager, along with the correct email addresses to use for peering requests.

When emailing other INEX members about peering requests, please include all technical details relevant to the peering session, including your IP address, your AS number, and an estimate of the number of prefixes you intend to announce to that candidate peer.

The My Peering Manager tool in the IXP Manager will compose mails with the above details for you automatically.

Please note that INEX members are required to reply to peering requests within a reasonable time frame.  If your emails to other INEX members about peering go unanswered, please let us know and we will do what we can.

INEX requires that all new members peer and share routes with the INEX route collectors for administrative purposes.  We would be obliged if you could set up your router(s) and make the necessary arrangements for this as soon as possible.

INEX's details are:

remote-as:      AS2128
AS Macro:       AS-INEXIE

{foreach $customer->getVirtualInterfaces() as $connection}
    {foreach $connection->getVlanInterfaces() as $vli}
        {if $vli->getVlan()->getNumber() eq 10}

Peering VLAN #1
    IPv6 address:       2001:7F8:18::F:0:1
    IPv6 session MD5:   {$vli->getIpv6bgpmd5secret()}

    IPv4 address:       185.6.36.126
    IPv4 session MD5:   {$vli->getIpv4bgpmd5secret()}
{elseif $vli->getVlan()->getNumber() eq 12}

Peering VLAN #2
    IPv6 address:       2001:7F8:18:12::9999
    IPv6 session MD5:   {$vli->getIpv6bgpmd5secret()}

    IPv4 address  :     194.88.240.126
    IPv4 session MD5:   {$vli->getIpv4bgpmd5secret()}
        {/if}

    {/foreach}
{/foreach}

No prefixes are announced by the route collector and it will not forward traffic.


NOC Details
===========

For the convenience of its members, INEX maintains a list of NOC and peering contact details for its members.  These details are held on a private INEX database, and are available only from the IXP Manager on the following URL:

        {genUrl controller="customer" action="details"}

This area of the INEX website is password protected and SSL secured. Passwords are only provided to current INEX members.  This information is considered private and will not be passed on to other third parties by INEX.

We would appreciate if you could take the time to ensure that the following details we hold on file are correct:

Your Input
----------

Member name:                    {$customer->getName()}
Primary corporate web page:     {$customer->getCorpwww()}
Peering Email Address:          {$customer->getPeeringemail()}
NOC Phone number:               {$customer->getNocphone()}
General NOC email address:      {$customer->getNocemail()}
NOC Hours:                      {$customer->getNochours()}
Dedicated NOC web page:         {$customer->getNocwww()}
AS Number:                      {$customer->getAutsys()}

----------


Router and Switch Configuration
=================================

If you are new to internet exchanges, we would ask you to note that all members are expected to adhere to the technical requirements of the INEX MoU.  In particular, we would draw your attention to section 2 of these requirements which outline what types of traffic may and may not be forwarded to the INEX peering LAN.

For Cisco IOS based routers, we recommend the following interface configuration commands:

 no ip redirects
 no ip proxy-arp
 no ip directed-broadcast
 no mop enabled
 no cdp enable
 udld port disable

If you intend to use IPv6 with a Cisco IOS based router, please also consider the following interface commands:

 no ipv6 redirects
 ipv6 nd suppress-ra

As part of standard provisioning for your new connection(s), INEX operations will put your new port through our quarantine process. This involves checking your port to ensure:

* no *-discover protocols are enabled (CDP, LLDP, etc)
* keepalive, MOP, etc are disabled
* there are no spanning tree BPDUs
* no 802.1q tagging (or, if your port is to be tagged, then tagged appropriately)

We will also get you to connect to the INEX quarantine route collector and advertise your prefixes over BGP. The details are exactly the same as the produciton route collector details above.

If you are connecting to INEX through a switch, please additionally read: https://www.inex.ie/ixp/static/switches

It would aid us greatly if you could prepare your new connection(s) for quarantine by configuring the appropriate IP addresses from the "Connection Details" section above and set up the route collector BGP session as per the details in the "Peering" section above.



IRC
===

INEX member staff and other INEX member employees may regularly be seen on irc.inex.ie (port 6697, SSL only), channel #inex-ops. 

Although this IRC server is secured with SSL, INEX does not recommend swapping passwords or any other private / confidential information on this facility.


AS112 Service
=============

For the benefit of its members, INEX hosts an AS112 nameserver which answers bogus requests to private IP address space.  This service is available as a regular peering host on both INEX peering LANs.

Full details are at: https://www.inex.ie/technical/as112-service/

Your session to the AS112 service will be brought up during normal the standard INEX provisioning of your new connection(s).



PeeringDB
=========

PeeringDB ( http://www.peeringdb.com/ ) facilitates the exchange of information related to peering. Specifically, what networks are peering, where they are peering, and if they are likely to peer with you.

More and more organisations are using PeeringDB to make decisions on where they should open POPs, provision new links, etc.

We would very much appreciate it if you could mark your new INEX peering under the "Public Peering Locations" section of your PeeringDB page. If you do not yet have a PeeringDB account, we would suggest that you register for one on their site.

INEX's PeeringDB entries are:

- INEX LAN1: https://www.peeringdb.com/ix/48
- INEX LAN2: https://www.peeringdb.com/ix/387
- INEX Cork: https://www.peeringdb.com/ix/1262

Note that a number of INEX members now require any network they peer with to have a PeeringDB entry.


Welcome to INEX, Ireland's Internet hub.


INEX Operations
INEX - Internet Neutral Exchange Association Company Limited By Guarantee
