<?php

namespace Repositories;

use Doctrine\ORM\EntityRepository;

/**
 * ChangeLogRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ChangeLogRepository extends EntityRepository
{
}
