<?php

namespace Repositories;

use Doctrine\ORM\EntityRepository;

/**
 * CustomerEquipment
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CustomerEquipment extends EntityRepository
{
}
