<?php

namespace Repositories;

use Doctrine\ORM\EntityRepository;

/**
 * IPv6AddressRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class IPv6AddressRepository extends EntityRepository
{
}
