<?php

namespace Repositories;

use Doctrine\ORM\EntityRepository;

/**
 * Location
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Location extends EntityRepository
{
}
