<?php

namespace Repositories;

use Doctrine\ORM\EntityRepository;

/**
 * PhysicalInterface
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PhysicalInterface extends EntityRepository
{
}
