<?php

namespace Repositories;

use Doctrine\ORM\EntityRepository;

/**
 * RSDroppedPrefix
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RSDroppedPrefix extends EntityRepository
{
}
