<?php

namespace Repositories;

use Doctrine\ORM\EntityRepository;

/**
 * SecEventRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SecEventRepository extends EntityRepository
{
}
