<?php

namespace Repositories;

use Doctrine\ORM\EntityRepository;

/**
 * Switcher
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Switcher extends EntityRepository
{
}
