<?php

namespace Repositories;

use Doctrine\ORM\EntityRepository;

/**
 * Traffic95thMonthlyRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Traffic95thMonthlyRepository extends EntityRepository
{
}
