<?php

namespace Repositories;

use Doctrine\ORM\EntityRepository;

/**
 * TrafficDaily
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TrafficDaily extends EntityRepository
{
}
