<?php

namespace Repositories;

use Doctrine\ORM\EntityRepository;

/**
 * VlanInterface
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VlanInterface extends EntityRepository
{
}
