{tmplinclude file="header.phtml" pageTitle="IXP Manager :: Administrator's Home"}

<ul class="breadcrumb">
    <li class="active">
        <a href="{genUrl controller='admin' action='index'}">Home</a>
    </li>
</ul>

{OSS_Message}

<div class="row-fluid">

<div class="span6">

    <div class="row-fluid">
        <table class="table table-bordered table-striped">
            <thead>
                <tr>
                    <th>Customer Type</th>
                    <th>Count</th>
                </tr>
            </thead>
            <tbody>
                {foreach from=$ctypes key=t item=c}

                    <tr>
                        <td>{CUSTOMER::$CUST_TYPES_TEXT.$t}</td>
                        <td>{$c}</td>
                    </tr>

                {/foreach}
            </tbody>

        </table>
    </div>

    {if $multiIXP}
        <br />
        <h3>Customer Ports by IXP</h3>

        <div class="row-fluid">
            <table class="table table-bordered table-striped">
                <thead>
                    <tr>
                        <th>IXP</th>

                        {foreach from=$speeds key=k item=i}
                            <th>{$k}</th>
                        {/foreach}

                        <th>Total</th>
                    </tr>
                </thead>
                <tbody>
                    {assign var=colcount value=0}
                    {foreach from=$byixp key=n item=spds}
                        {assign var=rowcount value=0}

                        <tr>
                            <td>{$n}</td>
                            {foreach from=$speeds key=k item=i}
                                <td>
                                    {if isset( $spds.$k )}
                                        {$spds.$k}
                                        {assign var=rowcount value=$rowcount+$spds.$k}
                                        {else}
                                        0
                                    {/if}
                                </td>
                            {/foreach}
                            <td>{$rowcount}</td>
                        </tr>
                        {assign var=colcount value=$rowcount+$colcount}

                    {/foreach}

                    <tr>
                        <td><strong>Totals</strong></td>
                        {foreach from=$speeds key=k item=i}
                            <td>
                                <strong>{$i}</strong>
                            </td>
                        {/foreach}
                        <td><strong>{$colcount}</strong></td>
                    </tr>
                </tbody>

            </table>
        </div>
    {/if}

    <br />
    <h3>Customer Ports by Location</h3>

    <div class="row-fluid">
        <table class="table table-bordered table-striped">
            <thead>
                <tr>
                    <th>Location</th>

                    {foreach from=$speeds key=k item=i}
                        <th>{$k}</th>
                    {/foreach}

                    <th>Total</th>
                </tr>
            </thead>
            <tbody>
                {assign var=colcount value=0}
                {foreach from=$bylocation key=n item=spds}
                    {assign var=rowcount value=0}

                    <tr>
                        <td>{$n}</td>
                        {foreach from=$speeds key=k item=i}
                            <td>
                                {if isset( $spds.$k )}
                                    {$spds.$k}
                                    {assign var=rowcount value=$rowcount+$spds.$k}
                                    {else}
                                    0
                                {/if}
                            </td>
                        {/foreach}
                        <td>{$rowcount}</td>
                    </tr>
                    {assign var=colcount value=$rowcount+$colcount}

                {/foreach}

                <tr>
                    <td><strong>Totals</strong></td>
                    {foreach from=$speeds key=k item=i}
                        <td>
                            <strong>{$i}</strong>
                        </td>
                    {/foreach}
                    <td><strong>{$colcount}</strong></td>
                </tr>
            </tbody>

        </table>
    </div>

    <br />
    <h3>Customer Ports by Infrastructure</h3>

    <div class="row-fluid">
        <table class="table  table-bordered table-striped">
            <thead>
                <tr>
                    <th>Infrastructure</th>

                    {foreach from=$speeds key=k item=i}
                        <th>{$k}</th>
                    {/foreach}

                    <th>Total</th>
                    <th>Connected<br>Capacity</th>
                </tr>
            </thead>
            <tbody>
                {assign var=colcount value=0}
                {foreach from=$bylan key=n item=spds}

                    {assign var=rowcount value=0}
                    {assign var=rowcap value=0}

                    <tr>
                        <td>{$n}</td>
                        {foreach from=$speeds key=k item=i}
                            <td>
                                {if isset( $spds.$k )}
                                    {$spds.$k}
                                    {assign var=rowcount value=$rowcount+$spds.$k}
                                    {assign var=rowcap value=$rowcap+$spds.$k*$k}
                                {else}
                                    0
                                {/if}
                            </td>
                        {/foreach}
                        <td>{$rowcount}</td>
                        <td>{$rowcap/1000}G</td>
                    </tr>
                    {assign var=colcount value=$rowcount+$colcount}
                {/foreach}

                <tr>
                    <td><strong>Totals</strong></td>
                    {assign var=rowcap value=0}
                    {foreach from=$speeds key=k item=i}
                        {assign var=rowcap value=$rowcap+$i*$k}
                        <td>
                            <strong>{$i}</strong>
                        </td>
                    {/foreach}
                    <td><strong>{$colcount}</strong></td>
                    <td><strong>{$rowcap/1000}G</strong></td>
                </tr>

            </tbody>

        </table>
    </div>

</div>

<div class="span6">

        {if isset( $graphs ) and count( $graphs )}
            {foreach $graphs as $id => $data}
                <div class="row-fluid">
                    <div class="well">
                        <h3>{$data.title}</h3>

                        <p>
                            {genMrtgGraphBox
                                ixp=$id
                                shortname='X_Peering'
                                period='month'
                                category='bits'
                                values=$stats.$id
                                graph=$data.name
                            }
                        </p>
                    </div>
                </div>
            {/foreach}
        {else}
            <div class="row-fluid">
               <div class="well">
                   <h3>Configure Your Aggregate Graph(s)</h3>

                   <p>
                       Aggregate graphs have not been configured.
                       Please see <a href="https://github.com/inex/IXP-Manager/wiki/MRTG---Traffic-Graphs">this documentation</a>.
                   </p>
               </div>
            </div>
        {/if}
</div>
</div>





{tmplinclude file="footer.phtml"}
