


<h3>Recent Members</h3>

<p>Our three most recent members are listed below.</p>

<table id="recentMembersTable" class="table">
    <thead>
        <tr>
            <th>Name</th>
            <th>AS Number</th>
            <th>Date Joined</th>
        </tr>
    </thead>
    <tbody>

    {$i = 0}
    {foreach from=$recentMembers item=member}
        <tr>
            <td>{$member->getName()}</td>
            <td>{$member->getAutsys()|asnumber}</td>
            <td>{$member->getDatejoin()->format( 'Y-m-d' )}</td>
        </tr>
        {if $i >= 2}{break}{/if}
	{$i = $i + 1}
    {/foreach}

    </tbody>
</table>


