<div class="row-fluid">
    <div class="span6">
        <strong>Member of IXPs</strong>
        {if count( $cust->getIXPs() )}    
            <ul>
                {foreach $cust->getIXPs() as $i}
                    <li>{$i->getName()}</li>
                {/foreach}
            </ul>
        {else}
            <p style="padding-left: 40px;">
                No IXPs found.
            </p>
        {/if}
    </div>
    <div class="span6">
        {if count( $validIXPs )}
            <strong>Available IXPs</strong>
            <ul>
                {foreach $validIXPs as $i}
                    <li>{$i}</li>
                {/foreach}
            </ul>
        {/if}
    </div>
</div>