
<div class="row-fluid">

    <div class="span6">
        <h3>Aggregate Peering Statistics</h3>
        
        {if $multiIXP}
            {foreach $cust->getIXPs() as $ixp}
                <br />
                <div class="well">
                    <h3>{$ixp->getName()}</h3>
                	<a href="{genUrl controller="statistics" action="member-drilldown" ixp=$ixp->getId() shortname=$cust->getShortname() category='bits' monitorindex='aggregate'}">
                        {genMrtgImgUrlTag ixp=$ixp->getId() shortname=$cust->getShortname() category='bits' monitorindex='aggregate'}
                    </a>
                </div>
            {/foreach}
        {else}
            <br />
            <div class="well">
            	<a href="{genUrl controller="statistics" action="member-drilldown" shortname=$user->getCustomer()->getShortname() category='bits' monitorindex='aggregate'}">
                    {genMrtgImgUrlTag shortname=$user->getCustomer()->getShortname() category='bits' monitorindex='aggregate'}
                </a>
            </div>
        {/if}
    </div>
    
    <div class="span6">

        <h3>Recent Members</h3>

        <p>Our three most recent members are listed below. {if not $user->getCustomer()->isTypeAssociate()}Have you arranged peering with them yet?{/if}</p>

        <table id="recentMembersTable" class="table">
            <thead>
                <tr>
                    <th>Name</th>
                    <th>AS Number</th>
                    <th>Date Joined</th>
                    {if not $user->getCustomer()->isTypeAssociate()}
                        <th>Peering Contact</th>
                    {/if}
                </tr>
            </thead>
            <tbody>

                {for $i=0 to 2}
                    {if isset( $recentMembers.$i ) }
                        <tr>
                            <td>{$recentMembers.$i->getName()}</td>
                            <td>{$recentMembers.$i->getAutsys()|asnumber}</td>
                            <td>{$recentMembers.$i->getDatejoin()->format( 'Y-m-d' )}</td>
                            <td>
                                <a href="mailto:{$recentMembers.$i->getPeeringemail()}">{$recentMembers.$i->getPeeringemail()}</a>
                            </td>
                        </tr>
                    {/if}
                {/for}

            </tbody>
        </table>

    </div>
</div>
        
{tmplinclude file="dashboard/index-tabs/overview-news.phtml"}
        
