
<form class="form-horizontal" enctype="application/x-www-form-urlencoded"
        accept-charset="UTF-8" method="post" horizontal="1"
        {if $isEdit}
            action="{genUrl controller="customer" action="edit" id=$object->getId()}"
        {else}
            action="{genUrl controller="customer" action="add"}"
        {/if}>

<div class="row-fluid">

    <div class="span6">

        <fieldset>
            <legend>Customer Details</legend>

            {$element->name}
            {$element->type}
            {$element->shortname}
            {$element->corpwww}
            {$element->datejoin}
            {$element->dateleave}
            {$element->status}
            {$element->MD5Support}
            {$element->abbreviatedName}

        </fieldset>

    </div>

    <div class="span6">

        <fieldset id="full-member-details" >
            <legend>Peering Details</legend>

            {$element->autsys}
            {$element->maxprefixes}
            {$element->peeringemail}
            {$element->peeringmacro}
            {$element->peeringmacrov6}
            {$element->peeringpolicy}
            {$element->irrdb}
            {$element->activepeeringmatrix}

            <p><em>Note that the IPv4 peering macro is used when there is no v6 macro set. To force no macro
            for IPv6, set it as AS-NULL.</em></p>
        </fieldset>

    </div>


</div>

<div id="full-member-details2" class="row-fluid">

    <div class="span6">

     <fieldset>
        <legend>NOC Details</legend>

        {$element->nocphone}
        {$element->noc24hphone}
        {$element->nocfax}
        {$element->nocemail}
        {$element->nochours}
        {$element->nocwww}

    </fieldset>
    </div>

    <div class="span6">
        {if $resellerMode || $multiIXP }
            <fieldset>
                <legend>
                    {if $resellerMode && $multiIXP }
                        Reseller & IXP Association Details
                    {else if $resellerMode }
                        Reseller Details
                    {else}
                        IXP Association Details
                    {/if}
                </Legend>
                {if $resellerMode }
                    {$element->isReseller}
                    {$element->isResold}
                    <div id="reseller-element-div" style="margin-top: -15px; margin-left: 80px; {if !$element->reseller->getValue()}display: none;{/if} ">
                        {$element->reseller}
                    </div>
                {/if}
                {$element->ixp}
            </fieldset>
            {if $resellerMode }
                <script type="text/javascript">
                    $( document ).ready( function(){

                        $( "#isResold" ).change( function(){
                            if( $( this ).prop( "checked" ) )
                            {
                                $( '#reseller-element-div' ).show();
                                if( $( '#isReseller' ).prop( "checked" ) )
                                    $( '#isReseller' ).prop( "checked", false );
                            }
                            else
                                $( '#reseller-element-div' ).hide();

                        });

                        $( "#isReseller" ).change( function(){
                            if( $( this ).prop( "checked" ) )
                            {
                                if( $( '#isResold' ).prop( "checked" ) )
                                    $( '#isResold' ).prop( "checked", false ).trigger( "change" );
                            }

                        });
                    });
                </script>
            {/if}
        {else}
            {$element->ixp}
        {/if}

    </div>

</div>


<div class="form-actions">

    {$element->cancel}
    {$element->submit}

</div>


</form>


<script type="text/javascript">

$(document).ready( function(){

    $('#datejoin').datepicker({
        changeMonth: true,
        changeYear: true,
        dateFormat: 'yy-mm-dd'
    });

    $('#dateleave').datepicker({
        changeMonth: true,
        changeYear: true,
        dateFormat: 'yy-mm-dd'
    });

    if( $('#datejoin').val().length > 10 )
        $('#datejoin').val( $('#datejoin').val().substr( 0, 10 ) );

    if( $('#dateleave').val().length > 10 )
        $('#dateleave').val( $('#dateleave').val().substr( 0, 10 ) );

    $( '#type' ).bind( 'change', function( event ){
        if( $( '#type' ).val() == 2 )  // associate member
        {
            $( '#full-member-details' ).slideUp( 'fast' );
            $( '#full-member-details2' ).slideUp( 'fast' );
        }
        else {
            $( '#full-member-details2' ).slideDown( 'fast' );
            $( '#full-member-details' ).slideDown( 'fast', function() {
                //$( '#irrdb' ).trigger( "liszt:updated" );
                //$(".chzn-select").chosen();
            });
        }
    });

    $( "#name" ).on( "change", function(){
        if( $( '#abbreviatedName' ).val() == "" )
            $( '#abbreviatedName' ).val( $('#name' ).val() );
    });

    {if $isEdit and $object->getType() eq 2}
        $( '#full-member-details' ).slideUp( 'fast' );
        $( '#full-member-details2' ).slideUp( 'fast' );
    {/if}

    $( '#type' ).trigger( 'change' );

});

</script>
