
<form class="form-horizontal" enctype="application/x-www-form-urlencoded"
        accept-charset="UTF-8" method="post" horizontal="1"
        {if isset( $isEdit ) and $isEdit}
            action="{genUrl controller="customer" action="edit" id=$object.id}"
        {else}
            action="{genUrl controller="customer" action="add"}"
        {/if}>
            
<div class="row-fluid">

    <div class="span12">
    
        <fieldset>
            <legend>Send Email to Customer</legend>
            <br><br>
        </fieldset>
    </div>
</div>

<div class="row-fluid">

    <div class="span12">

        {$element->to}
        {$element->subject}
        {$element->cc}
        {$element->bcc}
        {$element->message}
        
    </div>
</div>

<div class="form-actions">

    <a class="btn" href="{genUrl controller="customer" action="overview" id=$customer->getId()}">Cancel</a>
    <input type="submit" name="commit" id="commit" value="Send Welcome Email" class="btn btn-primary">

</div>

    
</form>


<script type="text/javascript">

$(document).ready( function(){

    /* $( '#message' ).wysihtml5({

    	'allowObjectResizing':  true
    	    
    }); */
	
});
	
</script>



