{tmplinclude file="header.phtml" pageTitle="IXP Manager :: Member Dashboard"}

{if $user->getPrivs() eq 3}
    <ul class="breadcrumb">
        <li>
            <a href="{genUrl}">Home</a> <span class="divider">/</span>
        </li>
        <li>
            <a href="{genUrl controller="customer" action="list"}">Customers</a> <span class="divider">/</span>
        </li>
        <li class="active">
            Details
        </li>

        {if $multiIXP}
            <li class="pull-right" style="margin-top: -12px;">
                <div class="btn-toolbar">
                    <div class="btn-group">
                        <a class="btn btn-mini dropdown-toggle" data-toggle="dropdown" href="#">
                            {if isset( $ixp ) }{$ixp->getName()}{else}Limit to IXP...{/if}
                            <span class="caret"></span>
                        </a>
                        <ul class="dropdown-menu pull-right">
                            {foreach $ixpNames as $xid => $xname}
                                <li> <a href="{genUrl controller=$controller action=$action ixp=$xid}">{$xname}</a> </li>
                            {/foreach}
                        </ul>
                    </div>
                </div>
            </li>
        {/if}
    </ul>
    
    <div>
{else}
    <div class="page-content">
    
        <div class="page-header">

            {if $multiIXP && isset( $ixpNames ) && count( $ixpNames ) > 1 }
                <div class="pull-right">
                    <div class="btn-toolbar">
                        <div class="btn-group">
                            <a class="btn btn-mini dropdown-toggle" data-toggle="dropdown" href="#">
                                {if isset( $ixp ) }{$ixp->getName()}{else}Limit to IXP...{/if}
                                <span class="caret"></span>
                            </a>
                            <ul class="dropdown-menu pull-right">
                                {foreach $ixpNames as $xid => $xname}
                                    <li> <a href="{genUrl controller=$controller action=$action ixp=$xid}">{$xname}</a> </li>
                                {/foreach}
                            </ul>
                        </div>
                    </div>
                </div>
            {/if}

            <h1>Member Details</h1>
        </div>
        
{/if}
    
{OSS_Message}

<table id="ixpDataTable" class="table table-striped table-bordered">
    <thead>
        <tr>
            <th>Member</th>
            <th>Peering Email</th>
            <th>ASN</th>
            <th>NOC Phone</th>
            <th>NOC Hours</th>
            <th></th>
        </tr>
    </thead>
    <tbody>

    {foreach $details as $md}

        <tr>
            <td><a href="{$md.corpwww}">{$md.name}</a></td>
            <td><a href="mailto:{$md.peeringemail}">{$md.peeringemail}</a></td>
            <td>{if $md.type eq CUSTOMER::TYPE_ASSOCIATE}<em>(associate)</em>{else}{$md.autsys|asnumber}{/if}</td>
            <td>{$md.nocphone}</td>
            <td>{$md.nochours}</td>
            <td><a href="{genUrl controller='customer' action="detail" id=$md.id}">view</a></td>
        </tr>

    {/foreach}

    </tbody>
</table>

<script>
$(document).ready(function() {

    oTable = $('#ixpDataTable').dataTable({
        {if $hasIdentity and $user->getPrivs() eq 3}
            "sDom": "<'row-fluid'<'span6'l><'span6'f>r>t<'row-fluid'<'span6'i><'span6'p>>",
        {else}
            "sDom": "<'row'<'span6'l><'span6'f>r>t<'row'<'span6'i><'span6'p>>",
        {/if}
        "sPaginationType": "bootstrap",
    	"iDisplayLength": 100
    });

});
</script>

</div>

{tmplinclude file="footer.phtml"}
