{tmplinclude file="header.phtml" pageTitle="IXP Manager :: Member Dashboard"}

{if $user->getPrivs() eq 3}
    <ul class="breadcrumb">
        <li>
            <a href="{genUrl}">Home</a> <span class="divider">/</span>
        </li>
        <li>
            <a href="{genUrl controller="customer" action="details"}">Customer Details</a> <span class="divider">/</span>
        </li>
        <li class="active">
            {$cust->getName()}
        </li>
    </ul>

    <div>
{else}
    <div class="page-content">

        <div class="page-header">
            <h1>Member Details - {$cust->getName()}</h1>
        </div>
{/if}

{OSS_Message}

<table id="ixpDataTable">

<tr>
    <td width="200"><strong>Member Type:</strong></td>
    <td width="200" id="value">{CUSTOMER::$CUST_TYPES_TEXT[ $cust->getType() ]}</td>
    <td width="40"></td>
    <td width="200"><strong>Member Status:</strong></td>
    <td width="200" id="value">{CUSTOMER::$CUST_STATUS_TEXT[ $cust->getStatus() ]}</td>
</tr>

<tr>
    <td>&nbsp;</td><td></td><td></td><td></td><td></td>
</tr>

<tr>
    <td><strong>AS Number:</strong></td>
    <td id="value">{$cust->getAutsys()|asnumber}</td>
    <td></td>
    <td><strong>Peering Macro:</strong></td>
    <td id="value">{$cust->getPeeringmacro()}</td>
</tr>

<tr>
    <td></td><td></td><td></td><td></td><td></td>
</tr>

<tr>
    <td><strong>Peering Policy:</strong></td>
    <td id="value">{$cust->getPeeringpolicy()}</td>
    <td></td>
    <td></td>
    <td></td>
</tr>

<tr>
    <td>&nbsp;</td><td></td><td></td><td></td><td></td>
</tr>

<tr>
    <td><strong>Peering Email:</strong></td>
    <td id="value">{$cust->getPeeringemail()}</td>
    <td></td>
    <td><strong>NOC Email</strong></td>
    <td id="value">{$cust->getNocemail()}</td>
</tr>

<tr>
    <td></td><td></td><td></td><td></td><td></td>
</tr>

<tr>
    <td><strong>NOC Phone:</strong></td>
    <td id="value">{$cust->getNocphone()}</td>
    <td></td>
    <td><strong>NOC 24 Hour Phone</strong></td>
    <td id="value">{$cust->getNoc24hphone()}</td>
</tr>

<tr>
    <td></td><td></td><td></td><td></td><td></td>
</tr>

<tr>
    <td><strong>Dedicated NOC Web:</strong></td>
    <td id="value"><a href="{$cust->getNocwww()}">{$cust->getNocwww()}</a></td>
    <td></td>
    <td><strong>NOC Fax</strong></td>
    <td id="value">{$cust->getNocfax()}</td>
</tr>

<tr>
    <td></td><td></td><td></td><td></td><td></td>
</tr>

<tr>
    <td><strong>NOC Hours:</strong></td>
    <td id="value">{$cust->getNochours()}</td>
    <td></td>
    <td></td>
    <td></td>
</tr>

<tr>
    <td>&nbsp;</td><td></td><td></td><td></td><td></td>
</tr>

<tr>
    <td><strong>Corporate Web:</strong></td>
    <td id="value"><a href="{$cust->getCorpwww()}">{$cust->getCorpwww()}</a></td>
    <td></td>
    {if $multiIXP}
        <td><strong>IXPs:</strong></td>
        <td>
            {foreach $cust->getIXPs() as $ixp}
                {if $ixp@index != 0}<br />{/if}
                {$ixp->getName()}
            {/foreach}
        </td>
    {else}
        <td></td>
        <td></td>
    {/if}
</tr>

<tr>
    <td>&nbsp;</td><td></td><td></td><td></td><td></td>
</tr>

</table>


{foreach $cust->getVirtualInterfaces() as $vi}

<hr width="95%"></hr>

<h3>
    Connection {counter name=numconnections}
    {assign var='vlanints' value=$vi->getVlanInterfaces()}
    {assign var='vlanint' value=$vlanints.0}
    {if $vlanint}
    <small>
        &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Infrastructure #{if $vlanint->getVlan()->getNumber() % 10 == 0}1{else}2{/if}
        {if $vi->getPhysicalInterfaces()|@count > 1}
            {assign var='isLAG' value=1}
            &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;LAG Port
        {else}
            {assign var='isLAG' value=0}
        {/if}
    </small>
    {/if}
</h3>

{foreach $vi->getPhysicalInterfaces() as $pi}

    {if $isLAG}<h5>Port {counter name=numphysports} of {$vi->getPhysicalInterfaces()|@count} in LAG</h5>{/if}

    <table id="myDetailsTable">
        <tr>
            <td width="200"><strong>Switch:</strong></td>
            <td width="200" id="value">{$pi->getSwitchPort()->getSwitcher()->getName()}</td>
            <td width="40"></td>
            <td width="200"><strong>Switch Port:</strong></td>
            <td width="200" id="value">{$pi->getSwitchPort()->getName()}</td>
        </tr>
        <tr>
            <td><strong>Speed:</strong></td>
            <td id="value">{$pi->getSpeed()} Mbps</td>
            <td></td>
            <td><strong>Duplex:</strong></td>
            <td id="value">{$pi->getDuplex()}</td>
        </tr>
        <tr>
            <td><strong>Location:</strong></td>
            <td id="value">{$pi->getSwitchPort()->getSwitcher()->getCabinet()->getLocation()->getName()}</td>
            <td></td>
            <td><strong>Colo Cabinet ID:</strong></td>
            <td id="value">{$pi->getSwitchPort()->getSwitcher()->getCabinet()->getName()}</td>
        </tr>
        <tr>
            <td></td><td></td><td></td><td></td><td></td>
        </tr>
    </table>
{/foreach}

<br /><br />


{foreach $vi->getVlanInterfaces() as $vli}
{assign var='vlanid' value=$vli->getVlan()->getId()}

{if not $vli->getVlan()->getPrivate()}

    <h4>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;{$vli->getVlan()->getName()}:</h4>

    <table id="myDetailsTable">

    <tr>
        <td width="40"></td>
        <td width="200"><strong>IPv6 Address:</strong></td>
        <td width="200" id="value">
            {if $vli->getIpv6enabled() and $vli->getIpv6address()}
                {$vli->getIPv6Address()->getAddress()}/{$netinfo.$vlanid.6.masklen}
            {else}
                IPv6 not enabled.
            {/if}
        </td>
        <td width="40"></td>
        <td width="200"><strong>IPv4 Address:</strong></td>
        <td width="200" id="value">
            {if $vli->getIpv4enabled() and $vli->getIpv4address()}
                {$vli->getIPv4Address()->getAddress()}/{$netinfo.$vlanid.4.masklen}
            {else}
                IPv4 not enabled.
            {/if}
        </td>
    </tr>

    <tr>
        <td></td><td></td><td></td><td></td><td></td><td></td>
    </tr>

    <tr>
        <td></td>
        <td><strong>Multicast Enabled:</strong></td>
        <td id="value">{if $vli->getMcastenabled()}Yes{else}No{/if}</td>
        <td></td>
        <td><strong>Max Prefixes:</strong></td>
        <td id="value">global: {$cust->getMaxprefixes()}, per-interface: {$vli->getMaxbgpprefix()}</td>
    </tr>

    <tr>
        <td></td><td></td><td></td><td></td><td></td><td></td>
    </tr>

    <tr>
        <td></td>
        <td><strong>Route Server Client:</strong></td>
        <td id="value">{if $vli->getRsclient()}Yes{else}No{/if}</td>
        <td></td>
        {if $as112UiActive}
            <td><strong>AS112 Client:</strong></td>
            <td id="value">{if $vli->getAs112client()}Yes{else}No{/if}</td>
        {else}
            <td></td>
            <td></td>
        {/if}
    </tr>

    </table>

{/if} {* end is private vlan *}

{/foreach}

<br /><br />

{/foreach}

</div>

{tmplinclude file="footer.phtml"}
