
{if isset( $validCustomers )}
    <div class="modal hide fade" id="cust-assign-dialog">
        <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
            <h3>Assign Customer</h3>
        </div>
        <div class="modal-body" style="min-height: 20px;">
            <form class="form-horizontal" style="position: fixed; z-index: 10px">
                <div class="control-group">
                    <label class="control-label" for="customer">Customer</label>
                    <div class="controls">
                        <select id="customer" class="chzn-select" chzn-fix-width=1 >
                            {foreach $validCustomers as $c}
                                <option value="{$c->getId()}">{$c->getName()}</option>
                            {/foreach}
                        </select>
                    </div>
                </div>
            </form>
        </div>
        <div class="modal-footer">
            <span id="cust-assign-dialog-close" class="btn">Close</span>
            <span id="cust-assign-dialog-assign" class="btn btn-primary">Assign</span>
        </div>
    </div>
{/if}
