<td>
    {if $row.dateleave neq null and $row.dateleave->format( 'Y-m-d' ) neq '0000-00-00' and $row.dateleave->format( 'Y-m-d' ) neq '-0001-11-30'}
        <span class="label label-important">CLOSED</span>
    {else}
        {if $row.$col == CUSTOMER::STATUS_SUSPENDED}
            <span class="label label-important">SUSPENDED</span>
        {elseif $row.$col == CUSTOMER::STATUS_NORMAL or ( $row.type == CUSTOMER::TYPE_ASSOCIATE and $row.$col == CUSTOMER::STATUS_NOTCONNECTED )}
            {* An associate member can't be connected anyway! *}
            <span class="label label-success">NORMAL</span>
        {elseif $row.$col == CUSTOMER::STATUS_NOTCONNECTED}
            <span class="label label-warning">NOT CONNECTED</span>
        {else}
            <span class="label">{$cconf.mapper[$row.$col]}</span>
        {/if}
    {/if}
</td>
