
{tmplinclude file="header.phtml"}

<ul class="breadcrumb">
    <li>
        <a href="{genUrl}">Home</a> <span class="divider">/</span>
    </li>
    <li>
        <a href="{genUrl controller="customer" action="list"}">Customers</a> <span class="divider">/</span>
    </li>
    <li>
        <a href="{genUrl controller="customer" action="overview" id=$customer->getId()}">{$customer->getName()}</a> <span class="divider">/</span>
    </li>
    <li class="active">
        Manage Logo
    </li>
</ul>

{OSS_Message}

{if $orig}

    <div class="row-fluid">
        <div class="span6">
            <h3>Your Existing Logo:</h3>
        </div>
        <div class="span6">
            <img src="{genUrl}/logos/{$orig->getShardedPath()}" class="www80-padding">
        </div>
    </div>
    <div class="row-fluid">
        <br><br>
    </div>

{/if}

<div class="row-fluid">
    <div class="span12">
        <p>
            If you would like your logo displayed on our website, please {if $orig}replace{else}add{/if} your logo below.
        </p>

        <div class="alert alert-info">
            <strong>For best results, your logo must be uploaded as a PNG image with a <u>transparent background</u> that is 80px high and without any margin.</strong>
        </div>

        <p>
            Any other size will be scaled to 80px high which may affect the quality. We'll add a margin when displaying so you should not include any.
        </p>
        <p>
            If your logo does not conform to these specifications, we will remove it as it will not look appropriate to our website design.
            <br><br><br>
        </p>

        {$form}

        {if $orig}
            <hr>
            <p>
                If you want to remove your logo, please click here:
                <a class="btn btn-danger" href="{genUrl controller="customer" action="remove-logo" id=$customer->getId()}">
                    Remove My Logo
                </a>
            </p>
        {/if}
    </div>
</div>

{tmplinclude file="footer.phtml"}
