{tmplinclude file="header.phtml" pageTitle="IXP Manager :: Administrator's Home"}

<ul class="breadcrumb">
    <li>
        <a href="{genUrl}">Home</a> <span class="divider">/</span>
    </li>
    <li>
        <a href="{genUrl controller="customer" action="list"}">Customers</a> <span class="divider">/</span>
    </li>
    <li class="active">
        Overview for {$cust->getName()}
    </li>
    <li class="pull-right">
        <div class="btn-toolbar" style="display: inline;">
        
            <div class="btn-group">
                <a class="btn btn-mini dropdown-toggle" data-toggle="dropdown" href="#">
                    <i class="icon-cog"></i>
                    <span class="caret"></span>
                </a>
                <ul class="dropdown-menu">
                    <li>
                        <a href="{genUrl controller="customer" action="send-welcome-email" id=$cust->getId()}">Send Welcome Email...</a>
                    </li>
                </ul>
            </div>
        
            <div class="btn-group">
                <a class="btn btn-mini" href="{genUrl controller='customer' action="edit" id=$cust->getId()}"><i class="icon-pencil"></i></a>
                <a class="btn btn-mini" onclick="return confirm( 'Are you sure you want to delete this record?' );" href="{genUrl controller='customer' action="delete" id=$cust->getId()}"><i class="icon-trash"></i></a>
            </div>
    
            <div class="btn-group">
                {assign var=haveprev value=0}
                {assign var=havenext value=0}
                {foreach from=$customers key=k item=i name=custs}
                    {if $smarty.foreach.custs.first}
                        {assign var=cidprev  value=$k}
                    {/if}
                    
                    {if $k eq $cust->getId()}
                        {assign var=haveprev value=1}
                    {elseif $haveprev and not $havenext}
                        {assign var=havenext value=1}
                        {assign var=cidnext value=$k}
                    {/if}
                    
                    {if not $haveprev}
                        {assign var=cidprev value=$k}
                    {/if}
                    
                    {if not $havenext and $smarty.foreach.custs.last}
                        {assign var=cidnext value=$k}
                    {/if}
                    
                {/foreach}
                
                <a class="btn btn-mini" href="{genUrl controller='customer' action="dashboard" id=$cidprev}"><i class="icon-chevron-left"></i></a>
                <a class="btn btn-mini" href="{genUrl controller='customer' action="dashboard" id=$cust->getId()}"><i class="icon-refresh"></i></a>
                <a class="btn btn-mini" href="{genUrl controller='customer' action="dashboard" id=$cidnext}"><i class="icon-chevron-right"></i></a>
            </div>
        </div>
    </li>
</ul>

{OSS_Message}

<div class="row-fluid">

    <div class="span6">
    
        <div class="row-fluid">
        
            <h3>
                {$cust->getName()}
                {if $cust->getType() eq CUSTOMER::TYPE_ASSOCIATE}
                    <span class="label label-warning">ASSOCIATE MEMBER</span>
                {elseif $cust->getType() eq CUSTOMER::TYPE_PROBONO}
                    <span class="label label-info">PROBONO MEMBER</span>
                {elseif $cust->getType() eq CUSTOMER::TYPE_INTERNAL}
                    <span class="label label-inverse">INTERNAL INFRASTRUCTURE</span>
                {elseif $cust->getType() eq CUSTOMER::TYPE_FULL}
                    <span class="label label-success">FULL MEMBER</span>
                {else}
                    <span class="label">UNKNOWN MEMBER TYPE</span>
                {/if}
                {if $cust->hasLeft()}
                    <span class="label label-important">ACCOUNT CLOSED</span>
                {/if}
            </h3>
            <h4 style="padding-left: 30px;">
                {if $cust->getCorpwww()}<a href="{$cust->getCorpwww()}">{$cust->getCorpwww()}</a>{/if}
                {if $cust->getPeeringemail()} - {mailto address=$cust->getPeeringemail()}{/if}
            </h4>
            <br />
            
            <table class="table">
                <tbody>
                
                        <tr>
                            <td><strong>Status</strong></td>
                            <td>{CUSTOMER::$CUST_STATUS_TEXT[$cust->getStatus()]}</td>
                            <td><strong>Joined</strong></td>
                            <td>{$cust->getDatejoin()->format( 'Y-m-d' )}</td>
                        </tr>
                        <tr>
                            <td><strong>Type</strong></td>
                            <td>{CUSTOMER::$CUST_TYPES_TEXT[$cust->getType()]}</td>
                            <td><strong>Left</strong></td>
                            <td>{if $cust->hasLeft()}{$cust->getDateleave()->format( 'Y-m-d' )}{/if}</td>
                        </tr>
                        {if $cust->getType() neq CUSTOMER::TYPE_ASSOCIATE}
                            <tr>
                                <td><strong>Peering Policy</strong></td>
                                <td>{$cust->getPeeringpolicy()}</td>
                                <td><strong>ASN</strong></td>
                                <td>{$cust->getAutsys()|asnumber} {if $cust->getPeeringmacro()}({$cust->getPeeringmacro()}){/if}</td>
                            </tr>
                        {/if}
                        <tr>
                            <td>{if $cust->getType() neq CUSTOMER::TYPE_ASSOCIATE}<strong>NOC Details</strong>{/if}</td>
                            <td>
                                {if $cust->getType() neq CUSTOMER::TYPE_ASSOCIATE}
                                    {if $cust->getNochours()}    {$cust->getNochours()}<br />    {/if}
                                    {if $cust->getNocemail()}    {mailto address=$cust->getNocemail()}<br />{/if}
                                    {if $cust->getNocwww()}      {$cust->getNocwww()}<br />      {/if}
                                    {if $cust->getNocphone()}    {$cust->getNocphone()}<br />    {/if}
                                    {if $cust->getNoc24hphone()} {$cust->getNoc24hphone()} (24h) {/if}
                                {/if}
                            </td>
                            <td><strong>Billing Details</strong></td>
                            <td>
                                {if $cust->getBillingContact()}    {$cust->getBillingContact()}<br />     {/if}
                                {if $cust->getBillingAddress1()}   {$cust->getBillingAddress1()}<br />    {/if}
                                {if $cust->getBillingAddress2()}   {$cust->getBillingAddress2()}<br />    {/if}
                                {if $cust->getBillingCity()}       {$cust->getBillingCity()}<br />        {/if}
                                {if $cust->getBillingCountry()}    {$cust->getBillingCountry()}<br />     {/if}
                            </td>
                        </tr>
                        
                </tbody>
            </table>


            
            {if $cust->getType() neq CUSTOMER::TYPE_ASSOCIATE and ( not $cust->hasLeft() )}
            
                <br /><br />
                <h3>Interfaces <a class="btn btn-mini" href="{genUrl controller='virtual-interface' action="add-wizard" custid=$cust->getId()}"><i class="icon-plus"></i></a></h3>
                
                {if count( $cust->getVirtualInterfaces() )}
                
                    <table class="table">
                        <thead>
                            <th>Infrastructure</th>
                            <th>Location</th>
                            <th>Switch</th>
                            <th>Port</th>
                            <th>Speed</th>
                            <th></th>
                        </thead>
                        <tbody>
        
                        {foreach $cust->getVirtualInterfaces() as $vi}
                        
                            {assign var="pis" value=$vi->getPhysicalinterfaces()}
                        
                            <tr>
                            
                                <td>
                                    LAN #{$pis[0]->getSwitchPort()->getSwitcher()->getInfrastructure()}
                                </td>
                                <td>
                                    {$pis[0]->getSwitchPort()->getSwitcher()->getCabinet()->getLocation()->getName()}</td>
                                <td>
                                    {foreach from=$pis item=pi name=pis1}
                                        {$pi->getSwitchPort()->getSwitcher()->getName()}{if not $smarty.foreach.pis1.last}<br />{/if}
                                    {/foreach}
                                </td>
                                <td>
                                    {foreach from=$pis item=pi name=pis2}
                                        <a href="{genUrl controller='dashboard' action="statistics-drilldown" monitorindex=$pi->getMonitorindex() category='bits' shortname=$cust->getShortname()}">
                                            {$pi->getSwitchPort()->getName()}
                                        </a>{if not $smarty.foreach.pis2.last}<br />{/if}
                                    {/foreach}
                                </td>
                                <td>
                                    {foreach from=$pis item=pi name=pis3}
                                        {$pi->getSpeed()}/{$pi->getDuplex()}{if not $smarty.foreach.pis3.last}<br />{/if}
                                    {/foreach}
                                </td>
                                <td>
                                    <div class="btn-group">
                                        <a class="btn btn-mini" href="{genUrl controller='virtual-interface' action="edit" id=$vi->getId()}"><i class="icon-eye-open"></i></a>
                                    </div>
                                </td>
                                
                            </tr>
                            
                        {/foreach}
                        
                        </tbody>
                        
                    </table>

                {else}
                
                    <p style="padding-left: 40px;">No interfaces found.</p>
                    
                {/if}
                
            {/if} {* end dateleave *}
                
                
            
            
            <br /><br />
            <h3>User Accounts <a class="btn btn-mini" href="{genUrl controller='user' action="add" custid=$cust->getId()}"><i class="icon-plus"></i></a></h3>
            
            {if count( $cust->getUsers() )}
            
                <table class="table">
                    <thead>
                        <th>Username</th>
                        <th>Type</th>
                        <th>Email</th>
                        <th>Mobile</th>
                        <th></th>
                    </thead>
                    <tbody>
                        {foreach $cust->getUsers() as $u}
                            <tr>
                                <td>{$u->getUsername()}</td>
                                <td>{USER::$PRIVILEGES[$u->getPrivs()]}</td>
                                <td>{$u->getEmail()}</td>
                                <td>{$u->getAuthorisedMobile()}</td>
                                <td>
                                    <div class="btn-group">
                                        <a class="btn btn-mini" href="{genUrl controller='user' action="edit" id=$u->getId()}"><i class="icon-pencil"></i></a>
                                        <a class="btn btn-mini" onclick="return confirm( 'Are you sure you want to delete this user?' );" href="{genUrl controller='user' action="delete" id=$u->getId()}"><i class="icon-trash"></i></a>
                                        <a class="btn btn-mini" href="{genUrl controller='auth' action="switch-user" id=$u->getId()}" rel="tooltip" title="Log in as this user..."><i class="icon-user"></i></a>
                                    </div>
                                </td>
                            </tr>
                        {/foreach}
                    </tbody>
                </table>
                            
            {else}
            
                <p style="padding-left: 40px;">No users found.</p>
                
            {/if}
                
                            
            <br /><br />
            <h3>Contacts <a class="btn btn-mini" href="{genUrl controller='contact' action="add" custid=$acust.id}"><i class="icon-plus"></i></a></h3>

            
            {if count( $cust->getContacts() )}
            
                <table class="table">
                    <thead>
                        <th>Name</th>
                        <th>Email</th>
                        <th>Phone</th>
                        <th>Mobile</th>
                        <th></th>
                    </thead>
                    <tbody>
                        {foreach $cust->getContacts() as $c}
                            <tr>
                                <td>{$c->getName()}</td>
                                <td>{$c->getEmail()}</td>
                                <td>{$c->getPhone()}</td>
                                <td>{$c->getMobile()}</td>
                                <td>
                                    <div class="btn-group">
                                        <a class="btn btn-mini" href="{genUrl controller='contact' action="edit" id=$c->getId()}"><i class="icon-pencil"></i></a>
                                        <a class="btn btn-mini" onclick="return confirm( 'Are you sure you want to delete this user?' );" href="{genUrl controller='contact' action="delete" id=$c->getId()}"><i class="icon-trash"></i></a>
                                    </div>
                                </td>
                            </tr>
                        {/foreach}
                    </tbody>
                </table>
                                
                            
            {else}
            
                <p style="padding-left: 40px;">No contacts found.</p>
                
            {/if}
        
                            
            
        </div>
    </div>
    


    <div class="span6">
    
        {if $cust.type neq Cust::TYPE_ASSOCIATE and $acust.type neq Cust::TYPE_INTERNAL and ( not $acust.dateleave or $acust.dateleave eq '0000-00-00' )}
    
                <div class="row-fluid">
                
                    <div class="well">
                        <h3>Aggregate Traffic Statistics</h3>
                
                        <p>
                            <br />
                            <a href="{genUrl controller='dashboard' action='statistics-drilldown' monitorindex='aggregate' category='bits' shortname=$acust.shortname}">
                                {genMrtgImgUrlTag shortname=$acust.shortname category='bits' monitorindex='aggregate'}
                            </a>
                        </p>
                    </div>
                
                </div>
        
        
                {foreach from=$connections item=connection}
        
                    {foreach from=$connection.Physicalinterface item=pi}
        
                        <div class="row-fluid">
                        
                            <div class="well">
                
                                <h4>
                                        {$pi.Switchport.SwitchTable.Cabinet.Location.name}
                                        / {$pi.Switchport.SwitchTable.name}
                                        / {$pi.Switchport.name} ({$pi.speed}Mb/s)
                                </h4>
                
                
                                <p>
                                    <br />
                                    <a href="{genUrl controller='dashboard' action='statistics-drilldown' monitorindex=$pi.monitorindex category='bits' shortname=$acust.shortname}">
                                        {genMrtgImgUrlTag shortname=$acust.shortname category='bits' monitorindex=$pi.monitorindex}
                                    </a>
                                </p>
                
                            </div>
        
                        </div>
        
                    {/foreach}
                    
                {/foreach}


            {/if}  {* end dateleave *}
        
    </div>

    
    
</div>





{tmplinclude file="footer.phtml"}
