{tmplinclude file="header.phtml" pageTitle="IXP Manager :: Administrator's Home"}

<ul class="breadcrumb">
    <li>
		<h3>
            {$cust->getName()}
            {if $cust->getType() eq CUSTOMER::TYPE_ASSOCIATE}
                <span class="label label-warning">ASSOCIATE MEMBER</span>
            {elseif $cust->getType() eq CUSTOMER::TYPE_PROBONO}
                <span class="label label-info">PROBONO MEMBER</span>
            {elseif $cust->getType() eq CUSTOMER::TYPE_INTERNAL}
                <span class="label label-inverse">INTERNAL INFRASTRUCTURE</span>
            {elseif $cust->getType() eq CUSTOMER::TYPE_FULL}
                <span class="label label-success">FULL MEMBER</span>
            {else}
                <span class="label">UNKNOWN MEMBER TYPE</span>
            {/if}
            {if $cust->hasLeft()}
                <span class="label label-important">ACCOUNT CLOSED</span>
            {/if}
        </h3>
    </li>
    <li class="pull-right" style="margin-top: 12px;">
        <div class="btn-toolbar" style="display: inline;">
        
            <div class="btn-group">
                <a class="btn btn-mini dropdown-toggle" data-toggle="dropdown" href="#">
                    <i class="icon-cog"></i>
                    <span class="caret"></span>
                </a>
                <ul class="dropdown-menu pull-right">
                    <li>
                        <a href="{genUrl controller='virtual-interface' action="add-wizard" custid=$cust->getId() rtn="ov"}">
                        	Provision new port...
                        </a>
                    </li>
                	<li class="divider"></li>
                    <li>
                        <a href="{genUrl controller="customer" action="welcome-email" id=$cust->getId()}">Send Welcome Email...</a>
                    </li>
                </ul>
            </div>
        
            <div class="btn-group">
                <a class="btn btn-mini" href="{genUrl controller='customer' action="edit" id=$cust->getId()}"><i class="icon-pencil"></i></a>
            </div>
    
            <div class="btn-group">
                {assign var=haveprev value=0}
                {assign var=havenext value=0}
                {foreach from=$customers key=k item=i name=custs}
                    {if $smarty.foreach.custs.first}
                        {assign var=cidprev  value=$k}
                    {/if}
                    
                    {if $k eq $cust->getId()}
                        {assign var=haveprev value=1}
                    {elseif $haveprev and not $havenext}
                        {assign var=havenext value=1}
                        {assign var=cidnext value=$k}
                    {/if}
                    
                    {if not $haveprev}
                        {assign var=cidprev value=$k}
                    {/if}
                    
                    {if not $havenext and $smarty.foreach.custs.last}
                        {assign var=cidnext value=$k}
                    {/if}
                    
                {/foreach}
                
                <a class="btn btn-mini" href="{genUrl controller='customer' action="overview" id=$cidprev}"><i class="icon-chevron-left"></i></a>
                <a class="btn btn-mini" href="{genUrl controller='customer' action="overview" id=$cust->getId()}"><i class="icon-refresh"></i></a>
                <a class="btn btn-mini" href="{genUrl controller='customer' action="overview" id=$cidnext}"><i class="icon-chevron-right"></i></a>
            </div>
        </div>
    </li>
</ul>

{OSS_Message}

<div class="row-fluid">

    <div class="span12 tabbable">
    
    	<ul class="nav nav-tabs">
    	
			<li class="active">
			    <a href="#overview" data-toggle="tab">Overview</a>
			</li>
			
            {if $cust->getType() neq CUSTOMER::TYPE_ASSOCIATE and ( not $cust->hasLeft() )}
			    <li>
			        <a href="#ports" data-toggle="tab">Ports</a>
    			</li>
			
    			{if $cust->hasPrivateVLANs()}
					<li>
					    <a href="#private-vlans" data-toggle="tab">Private VLANs</a>
					</li>
				{/if}
    		{/if}
				
			<li>
			    <a href="#users" data-toggle="tab">Users</a>
			</li>
			
			<li>
			    <a href="#contacts" data-toggle="tab">Contacts</a>
			</li>
			
            {* if count( $cust->getRSPrefixes() )}
			    <li>
			        <a href="#prefixes" data-toggle="tab">Dropped Prefixes</a>
    			</li>
    		{/if *}
			
            {if count( $cust->getConsoleServerConnections() )}
			    <li>
			        <a href="#console-server-connections" data-toggle="tab">OOB Access</a>
    			</li>
    		{/if}
			
    		{if $cust->getType() neq CUSTOMER::TYPE_ASSOCIATE and ( not $cust->hasLeft() )}
			    <li>
			        <a href="{genUrl controller="statistics" action="p2p" shortname=$cust->getShortname()}">P2P &raquo;</a>
    			</li>
    		{/if}
			
		</ul>
        
        <div class="tab-content">
	        <div class="tab-pane active" id="overview">
	        	{tmplinclude file="customer/overview-tabs/overview.phtml"}
	        </div>
	    
            {if $cust->getType() neq CUSTOMER::TYPE_ASSOCIATE and ( not $cust->hasLeft() )}
		        <div class="tab-pane" id="ports">
		        	{tmplinclude file="customer/overview-tabs/ports.phtml"}
	        	</div>
			        	
				{if $cust->hasPrivateVLANs()}
		            <div class="tab-pane" id="private-vlans">
		        	    {tmplinclude file="customer/overview-tabs/private-vlans.phtml"}
	        	    </div>
				{/if}
			{/if}
				
	        <div class="tab-pane" id="users">
	        	{tmplinclude file="customer/overview-tabs/users.phtml"}
        	</div>
        	
	        <div class="tab-pane" id="contacts">
	        	{tmplinclude file="customer/overview-tabs/contacts.phtml"}
        	</div>
        	
            {* if count( $cust->getRSPrefixes() )}
    	        <div class="tab-pane" id="prefixes">
    	        	{tmplinclude file="customer/overview-tabs/prefixes.phtml"}
            	</div>
            {/if *}
            
            {if count( $cust->getConsoleServerConnections() )}
			    <div class="tab-pane" id="console-server-connections">
    	        	{tmplinclude file="customer/overview-tabs/console-server-connections.phtml"}
            	</div>
        	{/if}
            
        </div>
		    
    </div>
    
</div>

{tmplinclude file="footer.phtml"}
