{tmplinclude file="header.phtml" pageTitle="IXP Manager :: Administrator's Home"}

<ul class="breadcrumb">
    <li>
    <h3>
            {$cust->getName()}
            {tmplinclude file='customer/custtype.phtml'}
        </h3>
        {if $resellerMode && $cust->getReseller()}
            <p style="margin-left: 15px;">Resold customer of <a href="{genUrl controller=$controller action=$action id=$cust->getReseller()->getId()}">{$cust->getReseller()->getName()}</p>
        {/if}
    </li>
    <li class="pull-right" style="margin-top: 12px;">
        <div class="btn-toolbar" style="display: inline;">
        
            <div class="btn-group">
                <a class="btn btn-mini dropdown-toggle" data-toggle="dropdown" href="#">
                    <i class="icon-cog"></i>
                    <span class="caret"></span>
                </a>
                <ul class="dropdown-menu pull-right">
                    <li>
                        <a href="{genUrl controller='virtual-interface' action="add-wizard" custid=$cust->getId() rtn="ov"}">
                        	Provision new port...
                        </a>
                    </li>
                	<li class="divider"></li>
                    <li>
                        <a href="{genUrl controller="customer" action="welcome-email" id=$cust->getId()}">Send Welcome Email...</a>
                    </li>
                </ul>
            </div>
        
            <div class="btn-group">
                <a class="btn btn-mini dropdown-toggle" href="#" data-toggle="dropdown">
                    <i class="icon-pencil"></i>
                    <span class="caret"></span>
                </a>
                <ul class="dropdown-menu pull-right">
                    <li>
                        <a href="{genUrl controller=$controller action="edit" id=$cust->getId()}">
                            Edit Customer Details
                        </a>
                    </li>
                    <li>
                        <a href="{genUrl controller=$controller action="billing-registration" id=$cust->getId()}">
                            {if (!isset( $options.reseller.no_billing_for_resold_customers ) || !$options.reseller.no_billing_for_resold_customers ) || !$resellerMode || !$cust->isResoldCustomer()}
                                Edit Billing/Registration Details
                            {else}
                                Edit Registration Details
                            {/if}
                        </a>
                    </li>
                </ul>
            </div>
    
            <div class="btn-group">
                {assign var=haveprev value=0}
                {assign var=havenext value=0}
                {foreach from=$customers key=k item=i name=custs}
                    {if $smarty.foreach.custs.first}
                        {assign var=cidprev  value=$k}
                    {/if}
                    
                    {if $k eq $cust->getId()}
                        {assign var=haveprev value=1}
                    {elseif $haveprev and not $havenext}
                        {assign var=havenext value=1}
                        {assign var=cidnext value=$k}
                    {/if}
                    
                    {if not $haveprev}
                        {assign var=cidprev value=$k}
                    {/if}
                    
                    {if not $havenext and $smarty.foreach.custs.last}
                        {assign var=cidnext value=$k}
                    {/if}
                    
                {/foreach}
                
                <a class="btn btn-mini" href="{genUrl controller='customer' action="overview" id=$cidprev}"><i class="icon-chevron-left"></i></a>
                <a class="btn btn-mini" href="{genUrl controller='customer' action="overview" id=$cust->getId()}"><i class="icon-refresh"></i></a>
                <a class="btn btn-mini" href="{genUrl controller='customer' action="overview" id=$cidnext}"><i class="icon-chevron-right"></i></a>
            </div>
        </div>
    </li>
</ul>

{OSS_Message}
<div id="co-messages"></div>

<div class="row-fluid">

    <div class="span12 tabbable">
    
        <ul id="customer-overview-tabs" class="nav nav-tabs">
        
        <li class="active">
            <a href="#overview" data-toggle="tab">Overview</a>
        </li>

        {if $multiIXP }
            <li>
                <a href="#ixps" data-toggle="tab">IXPs</a>
            </li>
        {/if}

        <li>
            <a href="#details" data-toggle="tab">Details</a>
        </li>

        {if $resellerMode && $cust->isReseller()}
            <li>
                <a href="#resold-customers" data-toggle="tab">Resold Customers</a>
            </li>
        {/if}
            
        {if $cust->getType() neq CUSTOMER::TYPE_ASSOCIATE and ( not $cust->hasLeft() )}
            <li>
                <a href="#ports" data-toggle="tab">Ports</a>
            </li>

            {if $cust->hasPrivateVLANs()}
                <li>
                    <a href="#private-vlans" data-toggle="tab">Private VLANs</a>
                </li>
            {/if}
        {/if}
                
        <li>
            <a href="#users" data-toggle="tab">Users</a>
        </li>
        
        <li>
            <a href="#contacts" data-toggle="tab">Contacts</a>
        </li>
        
        <li>
            <a href="#logins" data-toggle="tab">Logins</a>
        </li>
                
        <li>
            <a href="#notes" id="tab-notes" data-toggle="tab">
                Notes {if isset( $unreadNotes ) and $unreadNotes}
                    <span id="notes-unread-indicator" class="badge badge-success">{$unreadNotes}</span>
                {/if}
            </a>
        </li>
        
        {if count( $cust->getConsoleServerConnections() )}
            <li>
                <a href="#console-server-connections" data-toggle="tab">OOB Access</a>
            </li>
        {/if}
        
        {if $cust->getType() neq CUSTOMER::TYPE_ASSOCIATE and ( not $cust->hasLeft() )}
        
            {if not isset( $options['frontend']['disabled']['rs-prefixes'] ) or not $options['frontend']['disabled']['rs-prefixes'] }
                {if $cust->isRouteServerClient()}
                    <li>
                        <a href="{genUrl controller="rs-prefixes" action="list" custid=$cust->getId()}">
                            RS Prefixes
                            {if $rsRoutes.adv_nacc.total gt 0}
                                <span class="badge badge-important">{$rsRoutes.adv_nacc.total}</span>
                            {/if}
                            &raquo;
                        </a>
                    </li>
                {/if}
            {/if}

            {if isset( $options.sflow.enabled ) and $options.sflow.enabled}
                <li>
                    <a href="{genUrl controller="statistics" action="p2p" shortname=$cust->getShortname()}">P2P &raquo;</a>
                </li>
            {/if}
        {/if}
        
        </ul>
        
        <div class="tab-content">
        <div class="tab-pane active" id="overview">
            {tmplinclude file="customer/overview-tabs/overview.phtml"}
        </div>

        {if $multiIXP}
            <div class="tab-pane" id="ixps">
                {tmplinclude file="customer/overview-tabs/ixps.phtml"}
            </div>
        {/if}

        <div class="tab-pane" id="details">
            {tmplinclude file="customer/overview-tabs/details.phtml"}
        </div>

        {if $resellerMode && $cust->isReseller()}
            <div class="tab-pane" id="resold-customers">
                {tmplinclude file="customer/overview-tabs/resold-customers.phtml"}
            </div>
        {/if}

        {if $cust->getType() neq CUSTOMER::TYPE_ASSOCIATE and ( not $cust->hasLeft() )}
            <div class="tab-pane" id="ports">
                {if $resellerMode && $cust->isReseller()}
                    {tmplinclude file="customer/overview-tabs/reseller-ports.phtml"}
                {else}
                    {tmplinclude file="customer/overview-tabs/ports.phtml"}
                {/if}
            </div>

                {if $cust->hasPrivateVLANs()}
                    <div class="tab-pane" id="private-vlans">
                        {tmplinclude file="customer/overview-tabs/private-vlans.phtml"}
                    </div>
                {/if}
        {/if}
            
        <div class="tab-pane" id="users">
            {tmplinclude file="customer/overview-tabs/users.phtml"}
        </div>
        
        <div class="tab-pane" id="contacts">
            {tmplinclude file="customer/overview-tabs/contacts.phtml"}
        </div>
        
         <div class="tab-pane" id="logins">
            {tmplinclude file="customer/overview-tabs/logins.phtml"}
        </div>
        
        <div class="tab-pane" id="notes">
            {tmplinclude file="customer/overview-tabs/notes.phtml"}
        </div>
        
        {if count( $cust->getConsoleServerConnections() )}
            <div class="tab-pane" id="console-server-connections">
                {tmplinclude file="customer/overview-tabs/console-server-connections.phtml"}
            </div>
        {/if}
            
        </div>
        
    </div>
    
</div>

<script>{tmplinclude file="customer/js/overview.js"}</script>
{tmplinclude file="footer.phtml"}
