{tmplinclude file="header.phtml"}

<ul class="breadcrumb">
    <li>
        <a href="{genUrl}">Home</a> <span class="divider">/</span>
    </li>
    <li>
        Customers <span class="divider">/</span>
    </li>
    <li class="active">
        Unread Notes for You
    </li>
</ul>

{OSS_Message}

<div class="row-fluid">
    <div class="span12">
    
    {if count( $notes )}
        The following customers have new or updated notes that you have not seen.
    {else}
        There are no notes for any customers that you have not seen.
    {/if}
    
    </div>
</div>

{if count( $notes )}
<div class="row-fluid">
    <div class="span12">

    <table class="table " id="list-table-notes">
        <thead>
            <th>Customer</th>
            <th>Notes Last Created / Updated</th>
        </thead>
        <tbody>
            {foreach $notes as $n}
                <tr>
                    <td><a href="{genUrl controller="customer" action="overview" tab="notes" id=$n.cid}">{$n.cname}</a></td>
                    <td>{$n.latest}</td>
                </tr>
            {/foreach}
        </tbody>
    </table>
    
    
    </div>
</div>
{/if}

<!--  script>{tmplinclude file="rs-prefixes/js/index.js"}</script -->
{tmplinclude file="footer.phtml"}
