<div class="modal-header">
        <a href="#" class="close" data-dismiss="modal">&times;</a>
           <h1 style="display: inline;">
            {$feParams->pagetitle}&nbsp;&nbsp;
            <small>{if $isEdit}Edit{else}Add New {$feParams->titleSingular}{/if}</small>
        </h1>
    </div>
<div class="modal-body" style="min-height: 200px;">

    {OSS_Message}

    {* do we have any additional text to put before the table? *}
    {if $addPreamble}{include file=$addPreamble}{/if}

    {$form}

    {* do we have any additional text to put after the table? *}
    {if $addPostamble}{include file=$addPostamble}{/if}

</div>
<div class="modal-footer" id="mtfooter">
    <button id="modal_dialog_save" class="btn btn-primary">{if $isEdit}Save Changes{else}Add{/if}</button>
    <button id="modal_dialog_cancel" class="btn">Cancel</button>
    <script type="text/javascript">
    $(document).ready(function()
    {
        tmp = $( 'form form' ).html();
        $( 'form form' ).after( tmp );
        $( 'form form' ).remove();

        $( "div .form-actions" ).remove();
        $( "select" ).chosen();
        $( ".chzn-container .chzn-drop" ).parent().css( "position", "fixed" );
        $('#modal_dialog_save').bind('click', function() {
            valid = true;
            var data = $('#modal_dialog').html();

            var Throb = ossThrobber( 32, 14, 1.8 ).appendTo( $( '#mtfooter' ).get(0) ).start();

            $('#modal_dialog_save').attr('disabled', 'disabled' ).addClass( 'disabled' );
            $('#modal_dialog_cancel').attr('disabled', 'disabled' ).addClass( 'disabled' );

            $.ajax({
                url: "{$form->getAction()}",
                data: $( '#{$form->getId()}' ).serialize()+"&submit=1",
                async: true,
                cache: false,
                type: 'POST',
                timeout: 10000,
                success: function(data) {
                    if( data == "ok" ) {
                        dialog.modal('hide');
                            location.reload();
                    }
                    else if( data.substring(0, 26) == '<div class="modal-header">' ){
                        $('#modal_dialog').html( data );
                        $( '#modal_dialog_cancel' ).bind( 'click', function(){
                            dialog.modal('hide');
                        });

                        $( '#username' ).bind( 'change', function() { ossJscriptFieldValidator( 'username', true ) } );
                        $( '#password' ).bind( 'change', function() { ossJscriptFieldValidator( 'password' ) } );
                    }
                    else {
                        dialog.modal('hide');
                        ossAddMessage( 'An unexpected error has occured.', 'error' );
                    }
                },
                error:   ossAjaxErrorHandler
            });
        });
    });
    </script>
    {if $addScript}<script>{include file=$addScript}</script>{/if}
    </div>