{include file="header.phtml"}

<div class="page-content" >

    <div class="page-header" >
        <h1 style="display: inline;">{$feParams->pagetitle}</h1>
        
        <span style="float: right; margin-top: -10px;">
            {* do we have a customer page header toolbar? *}
            {if $listToolbar}
                {include file=$listToolbar}
           {else if $module != "index"}
                <div class="btn-toolbar">
                    <div class="btn-group">
                        <a class="btn" href="{genUrl module=$module controller=$controller action='add'}"><i class="icon-plus"></i></a>
                    </div>
                </div>
            {else}
                <div class="btn-toolbar">
                    <div class="btn-group">
                        <a class="btn" href="{genUrl controller=$controller action='add'}"><i class="icon-plus"></i></a>
                    </div>
                </div>
            {/if}
        </span>
    </div>
    
    {OSS_Message}

    {* do we have any additional text to put before the table? *}
    {if $listPreamble}{include file=$listPreamble}{/if}

    {if count( $data )}
    <table id='frontend-list-table' class="table hide">
    
    <thead>
        <tr>
            {foreach $feParams->listColumns as $col => $cconf}
                {if not is_array( $cconf ) or not isset( $cconf.display ) or $cconf.display}
                    <th>{if is_array( $cconf )}{$cconf.title}{else}{$cconf}{/if}</th>
                {/if}
            {/foreach}
            <th></th>
        </tr>
    </thead>
    
    <tbody>
        {foreach $data as $idx => $row}
        <tr>
            {foreach $feParams->listColumns as $col => $cconf}
                {if not is_array( $cconf )}
                    <td>{$row.$col}</td>
                {elseif not isset( $cconf.display ) or $cconf.display}
                    {if isset( $cconf.type )}
                        {if $cconf.type eq $FE_COL_TYPES.HAS_ONE}
                            <td>
                                {assign var=hasOneId value=$cconf.idField}
                                <a href="{genUrl controller=$cconf.controller action=$cconf.action id=$row.$hasOneId}">{$row.$col}</a>
                            </td>
                        {elseif $cconf.type eq $FE_COL_TYPES.DATETIME}
                            <td>
                                {$row.$col|date_format:'%Y-%m-%d %H:%M:%S'}
                            </td>
                        {elseif $cconf.type eq $FE_COL_TYPES.SCRIPT}
                            {tmplinclude file=$cconf.script}
                        {else}
                            <td>Type?</td>
                        {/if}
                    {else}
                        <td>{$row.$col}</td>
                    {/if}
                {/if}
            {/foreach}
            <td>
                {* do we have a custom menu defined for this table? *}
                {if not $listRowMenu}
                    <div class="btn-group">
                        <a class="btn btn-mini have-tooltip-below" href="{genUrl module=$module controller=$controller action='view' id=$row.id}" title="Preview"><i class="icon-eye-open"></i></a>
                        <a class="btn btn-mini have-tooltip-below" href="{genUrl module=$module controller=$controller action='edit' id=$row.id}" title="Edit"><i class="icon-pencil"></i></a>
                        <a class="btn btn-mini have-tooltip-below" id='list-delete-{$row.id}' href="{genUrl module=$module controller=$controller action='delete' id=$row.id}" title="Delete"><i class="icon-trash"></i></a>
                    </div>
                {else}
                    {include file=$listRowMenu}
                {/if}
            </td>
        </tr>
        {/foreach}
    </tbody>
    
    </table>
    {else}
        <p>
            There are no entries.{if !isset( $feParams->addWhenEmpty ) || $feParams->addWhenEmpty } Do you want to <a href="{genUrl controller=$controller action='add'}">add one...</a>{/if}
        </p>
    {/if} {* end if count( $data ) *}
    
    {* do we have any additional text to put after the table? *}
    {if $listPostamble}{include file=$listPostamble}{/if}
    
</div>


{if $listScript}<script>{include file=$listScript}</script>{/if}
{if $listAddonScript}<script>{include file=$listAddonScript}</script>{/if}
{include file="footer.phtml"}