{tmplinclude file="header.phtml"}

{if isset( $user ) and $user->getPrivs() eq USER::AUTH_SUPERUSER}
    <ul class="breadcrumb">
        <li>
            <a href="{genUrl}">Home</a> <span class="divider">/</span>
        </li>
        <li>
            <a href="{genUrl controller=$controller action="list"}">{$feParams->pagetitle}</a> <span class="divider">/</span>
        </li>
        <li class="active">
            View {$feParams->titleSingular}
        </li>
        
        <li class="pull-right">
            {* do we have a custom page header toolbar? *}
            {if $viewToolbar}
                {tmplinclude file=$viewToolbar}
            {else}
                <div class="btn-group">
                    <a class="btn btn-mini" href="{genUrl controller=$controller action='list'}"><i class="icon-list"></i></a>
                    {if !isset( $feParams->readonly ) or !$feParams->readonly}
                        <a class="btn btn-mini" href="{genUrl controller=$controller action='edit' id=$object.id}"><i class="icon-pencil"></i></a>
                        <a class="btn btn-mini" href="{genUrl controller=$controller action='add'}"><i class="icon-plus"></i></a>
                    {/if}
                </div>
            {/if}
        </li>
    </ul>

    <div>
{else}
    <div class="page-content" >
    
        <div class="page-header" >
            <h1 style="display: inline;">{$feParams->pagetitle}</h1>
            
            <span style="float: right; margin-top: -10px;">
                {* do we have a custom page header toolbar? *}
                {if $viewToolbar}
                    {tmplinclude file=$viewToolbar}
                {else}
                    <div class="btn-toolbar">
                    	<div class="btn-group">
                            <a class="btn" href="{genUrl controller=$controller action='list'}"><i class="icon-list"></i></a>
                            <a class="btn" href="{genUrl controller=$controller action='edit' id=$object.id}"><i class="icon-pencil"></i></a>
                            <a class="btn" href="{genUrl controller=$controller action='add'}"><i class="icon-plus"></i></a>
                        </div>
                    </div>
                {/if}
            </span>
        </div>
{/if}
    
    {OSS_Message}

    {* do we have any additional text to put before the view? *}
    {if $viewPreamble}{tmplinclude file=$viewPreamble}{/if}

    <dl>
        {foreach $feParams->viewColumns as $col => $cconf}
            {if not is_array( $cconf ) or not isset( $cconf.display ) or $cconf.display}
                <dt>
                    {if not is_array( $cconf )}{$cconf}{else}{$cconf.title}{/if}
                </dt>
                <dd>
                    {if not is_array( $cconf )}
                        {if $object.$col eq false}0{else}{$object.$col}{/if}
                    {elseif isset( $cconf.type )}
                        {if $cconf.type eq $FE_COL_TYPES.HAS_ONE}
                            {assign var=hasOneId value=$cconf.idField}
                            <a href="{genUrl controller=$cconf.controller action=$cconf.action id=$object.$hasOneId}">{$object.$col}</a>
                        {elseif $cconf.type eq $FE_COL_TYPES.XLATE}
                            {if isset($cconf.xlator[ $object.$col ])}{$cconf.xlator[ $object.$col ]}{else}{$object.$col}{/if}
                        {elseif $cconf.type eq $FE_COL_TYPES.DATETIME}
                            {if $object.$col}{$object.$col|date_format:'%Y-%m-%d %H:%M:%S'}{/if}
                        {elseif $cconf.type eq $FE_COL_TYPES.DATE}
                            {if $object.$col}{$row.$col|date_format:'%Y-%m-%d'}{/if}
                        {elseif $cconf.type eq $FE_COL_TYPES.TIME}
                            {if $object.$col}{$row.$col|date_format:'%H:%M:%S'}{/if}
                        {elseif $cconf.type eq $FE_COL_TYPES.SCRIPT}
                            {tmplinclude file=$cconf.script}
                        {else}
                            Type?
                        {/if}
                    {else}
                        {$object.$col}
                    {/if}
                </dd>
            {/if}
        {/foreach}
    </dl>
    
    {* do we have any additional text to put after the view? *}
    {if $viewPostamble}{tmplinclude file=$viewPostamble}{/if}
    
</div>


{if $viewScript}<script>{tmplinclude file=$viewScript}</script>{/if}
{tmplinclude file="footer.phtml"}