<form class="form-horizontal" enctype="application/x-www-form-urlencoded"
        accept-charset="UTF-8" method="post" horizontal="1"
>

<div class="row-fluid">
    <div class="span6">

        {$element->virtualinterfaceid}
        {$element->vlanid}
        {$element->irrdbfilter}
        {$element->mcastenabled}

    </div>
    <div class="span6">

        {$element->maxbgpprefix}
        {$element->rsclient}
        {$element->as112client}
        {$element->busyhost}

    </div>
</div>

<div class="row-fluid">

    <div class="span6">
        {$element->ipv4enabled}

        <div id="ipv4details" class="hide">
            {$element->ipv4DisplayGroup}
        </div>
    </div>

    <div class="span6">
        {$element->ipv6enabled}

        <div id="ipv6details" class="hide">
            {$element->ipv6DisplayGroup}
        </div>
    </div>


</div>


{$element->preselectIPv4Address}
{$element->preselectIPv6Address}
{$element->preselectVlanInterface}

<div class="form-actions">
    {$element->cancel}
    {$element->submit}
</div>


</form>



