
<div class="well">
    <h5>MAC Address: {$search}</h5>
    <ul>
    {foreach $interfaces[ $cust->getId() ] as $vi}
        {foreach $vi->getPhysicalInterfaces() as $pi}
            <li>
                <a href="{genUrl controller="virtual-interface" action="edit" id=$vi->getId()}"> 
                    {$pi->getSwitchport()->getSwitcher()->getName()} :: {$pi->getSwitchport()->getName()} 
                </a> 
            </li>
        {/foreach}
    {/foreach}
    </ul>
</div>
