<html>
<head>
    <title>{$options.identity.sitename} - Your Accounts</title>
</head>
<body>
<h2>{$options.identity.sitename} - Your Accounts</h2>

<p>
To whom it may concern,
</p>
<p>
You, or someone purporting to be you, has requested a username
reminder for your email address for {$options.identity.sitename}.
</p>

<p>
The usernames linked to your account are:
</p>

<ul>
    {foreach $users as $u}
        <li> {$u->getUsername()} &nbsp;&nbsp;&nbsp;&nbsp;(for <em>{$u->getCustomer()->getName()}</em>) </li>
    {/foreach}
</ul>

<p>
If you did not make this request, please contact our support team.

<p>
Thanks and kind regards,
</p>

<p>
{$options.identity.name}<br />
<a href="mailto:{$options.identity.email}">{$options.identity.email}</a>
</p>

</body>
</html>
