<html>
<head>
    <title>{$options.identity.sitename} - Password Reset Information</title>
</head>
<body>
<h2>{$options.identity.sitename} - Password Reset Information</h2>

<p>
To whom it may concern,
</p>
<p>
You, or someone purporting to be you, has requested a password reset
for {$options.identity.sitename}.
</p>

<p>
If you wish to proceed, please click on the following link:
</p>

<p>
<a href="{genUrl controller="auth" action="reset-password" username=$user->getUsername() token=$token}">
    {genUrl controller="auth" action="reset-password" username=$user->getUsername() token=$token}
</a>
</p>

<p>
If you did not make this request, please contact our support team.
</p>

<p>
Thanks and kind regards,
</p>

<p>
{$options.identity.name}<br />
<a href="mailto:{$options.identity.email}">{$options.identity.email}</a>
</p>

</body>
</html>
