<html>
<head>
    <title>{$options.identity.sitename} - Your Password Has Been Reset</title>
</head>
<body>
<h2>{$options.identity.sitename} - Your Password Has Been Reset</h2>

<p>
To whom it may concern,
</p>

<p>
Your password for {$options.identity.sitename} has been reset by the user
initiated password reset procedure.
</p>

<p>
If you did not make this request, please contact us immediately.
</p>

<p>
Thanks and kind regards,
</p>


<p>
{$options.identity.name}<br />
<a href="mailto:{$options.identity.email}">{$options.identity.email}</a>
</p>

</body>
</html>
