#
# IXP Manager MRTG configuration file
#
# This file is generated by IXP Manager.
#

### DO NOT EDIT THIS FILE - IT IS AUTOMATICALLY GENERATED
###
### LAST GENERATION: <?php echo date('Y-m-d H:i:s'); ?>

### Global Config Options
WorkDir: {$options.mrtg.conf.workdir}
RunAsDaemon:Yes
Interval:5

IconDir: /images/

### Global Defaults
#  to get bits instead of bytes and graphs growing to the right
Options[_]: growright, bits
WithPeak[_]: ym
PageTop[_]: <h1>{$options.identity.orgname} Traffic Analysis</h1>
PageFoot[_]:  <table border=0 cellspacing=0 cellpadding=0 width=476>
  <tr valign=top>
   <td align=left style="font: Arial,Helvetica; size: 80%">
     &copy; 2007-{$smarty.now|date_format:'Y'} <a href="http://www.inex.ie/">Internet Neutral Exchange Association Limited</a>.
     All rights Reserved.
   </td>
   <td width=10>&nbsp;</td>
   <td align=right style="font: Arial,Helvetica; size: 80%">
     Generated by <a href="https://github.com/inex/IXP-Manager">IXP Manager</a> at {$smarty.now|date_format:'Y-m-d H:i:s'}.
   </td>
  </tr>
 </table>
