{tmplinclude file="header.phtml" pageTitle="IXP Manager :: Member Dashboard"}

{if $user->getPrivs() eq 3}
    <ul class="breadcrumb">
        <li>
            <a href="{genUrl}">Home</a> <span class="divider">/</span>
        </li>
        <li>
            <a href="{genUrl controller='customer' action='list'}">Customers</a> <span class="divider">/</span>
        </li>
        <li>
            <a href="{genUrl controller='customer' action='overview' id=$cust->getId()}">{$cust->getName()}</a> <span class="divider">/</span>
        </li>
        <li>
            <a href="{genUrl controller="statistics" action="member" ixp=$ixp->getId() shortname=$cust->getShortname()}">Statistics</a> <span class="divider">/</span>
        </li>
        <li class="active">
            Smokeping
        </li>
    </ul>
    <div>
{else}
    <div class="page-content">
        <div class="page-header">
            <h1>
                IXP Smokeping Graphs
                <a class="btn btn-primary pull-right"
                        href="{genUrl controller="statistics" action="member" ixp=$ixp->getId() shortname=$cust->getShortname()}">
                    Return to Statistics Overview
                </a>
            </h1>
        </div>
{/if}


{OSS_Message}

<div class="row-fluid">
    <div class="span12">
        <form class="inline" method="post" action="{genUrl controller="smokeping" action="member-drilldown" ixp=$ixp->getId() vi=$vi->getId()}">
            <h4>
                Smokeping Graphs for
                {if $multiIXP}
                    {$ixp->getShortname()} /
                {/if}
                {$inf->getName()}
        
                &nbsp;&nbsp;&nbsp;

                <select name="vlanid" onchange="this.form.submit();" class="chzn-select">
                    {foreach $vi->getVlanInterfaces() as $cvli}
                        {if $cvli->getVLAN()->getPrivate()}{continue}{/if}
                        <option value="{$cvli->getVLAN()->getId()}" {if $vlanid eq $cvli->getVLAN()->getId()}selected{/if}>{$cvli->getVLAN()->getName()}</option>
                    {/foreach}
                </select>
                
                &nbsp;&nbsp;&nbsp;
                
                <select name="proto" onchange="this.form.submit();" class="chzn-select">
                    {foreach $protos as $p => $n}
                        <option value="{$p}" {if $proto eq $p}selected{/if}>{$n}</option>
                    {/foreach}
                </select>
                
                &nbsp;&nbsp;&nbsp;
                
                on {$ip}
        
                {if $user->getPrivs() eq 3}
                    <a class="btn btn-primary pull-right"
                            href="{genUrl controller="statistics" action="member" ixp=$ixp->getId() shortname=$cust->getShortname()}">
                        Return to Statistics Overview
                    </a>
                {/if}
                </h4>
        </form>
        <br />
    </div>
</div>

<div class="row-fluid">

{assign var='count' value=0}

    {foreach $periods as $scale => $name}

        <div class="span6">
    
            <h4>{$name}</h4>
    
            <p>
                <img src="{genUrl controller="smokeping" action="retrieve-image" ixp=$ixp->getId() scale=$scale
                    infra=$pi->getSwitchPort()->getSwitcher()->getInfrastructure()->getId()
                    vlan=$vli->getVLAN()->getId() vlanint=$vli->getId() proto=$proto}"
                />
            </p>
    
        </div>
    
        {assign var='count' value=$count+1}
    
        {if $count%2 eq 0}
            </div><br /><div class="row-fluid">
        {/if}

    {/foreach}

{if $count%2 neq 0}
    <div class="span3"></div>
{/if}

</div>
</div>

{tmplinclude file="footer.phtml"}

