<?php

namespace Proxies\__CG__\Entities;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class NetworkInfo extends \Entities\NetworkInfo implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array<string, null> properties to be lazy loaded, indexed by property name
     */
    public static $lazyPropertiesNames = array (
);

    /**
     * @var array<string, mixed> default values of properties to be lazy loaded, with keys being the property names
     *
     * @see \Doctrine\Common\Proxy\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array (
);



    public function __construct(?\Closure $initializer = null, ?\Closure $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', 'protocol', 'network', 'masklen', 'rs1address', 'rs2address', 'dnsfile', 'id', 'Vlan'];
        }

        return ['__isInitialized__', 'protocol', 'network', 'masklen', 'rs1address', 'rs2address', 'dnsfile', 'id', 'Vlan'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (NetworkInfo $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy::$lazyPropertiesDefaults as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @deprecated no longer in use - generated code now relies on internal components rather than generated public API
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function setProtocol($protocol)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setProtocol', [$protocol]);

        return parent::setProtocol($protocol);
    }

    /**
     * {@inheritDoc}
     */
    public function getProtocol()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getProtocol', []);

        return parent::getProtocol();
    }

    /**
     * {@inheritDoc}
     */
    public function setNetwork($network)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNetwork', [$network]);

        return parent::setNetwork($network);
    }

    /**
     * {@inheritDoc}
     */
    public function getNetwork()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNetwork', []);

        return parent::getNetwork();
    }

    /**
     * {@inheritDoc}
     */
    public function setMasklen($masklen)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMasklen', [$masklen]);

        return parent::setMasklen($masklen);
    }

    /**
     * {@inheritDoc}
     */
    public function getMasklen()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMasklen', []);

        return parent::getMasklen();
    }

    /**
     * {@inheritDoc}
     */
    public function setRs1address($rs1address)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setRs1address', [$rs1address]);

        return parent::setRs1address($rs1address);
    }

    /**
     * {@inheritDoc}
     */
    public function getRs1address()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRs1address', []);

        return parent::getRs1address();
    }

    /**
     * {@inheritDoc}
     */
    public function setRs2address($rs2address)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setRs2address', [$rs2address]);

        return parent::setRs2address($rs2address);
    }

    /**
     * {@inheritDoc}
     */
    public function getRs2address()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRs2address', []);

        return parent::getRs2address();
    }

    /**
     * {@inheritDoc}
     */
    public function setDnsfile($dnsfile)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDnsfile', [$dnsfile]);

        return parent::setDnsfile($dnsfile);
    }

    /**
     * {@inheritDoc}
     */
    public function getDnsfile()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDnsfile', []);

        return parent::getDnsfile();
    }

    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setVlan(\Entities\Vlan $vlan = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setVlan', [$vlan]);

        return parent::setVlan($vlan);
    }

    /**
     * {@inheritDoc}
     */
    public function getVlan()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getVlan', []);

        return parent::getVlan();
    }

}
