{tmplinclude file="header.phtml" pageTitle="IXP Manager :: Search"}

<ul class="breadcrumb">
    <li class="active">
        Search
    </li>
</ul>

{OSS_Message}

{if isset( $results ) and count( $results )}
<div class="row-fluid">
    <div class="span12">
        <h4>{count( $results )} Result(s):</h4>
    </div>
</div>

{if $type eq 'username' or $type eq 'email'}

    {tmplinclude file='search/contacts.phtml'}

{elseif $type eq 'rsprefix'}

    {tmplinclude file='search/rsprefixes.phtml'}

{else}

{foreach $results as $cust}
<div class="row-fluid">
    <div class="span11 offset1">
 
        <h3>
            <a href="{genUrl controller="customer" action="overview" id=$cust->getId()}">
                {$cust->getAbbreviatedName()} - AS{$cust->getAutsys()}
            </a>
            &nbsp;&nbsp;&nbsp;&nbsp;
            {tmplinclude file='customer/custtype.phtml'}
        </h3>
        
        {if isset( $interfaces ) and count( $interfaces )}
            {if $type eq 'mac'}
                {tmplinclude file='search/additional/mac.phtml'}
            {elseif $type eq 'ipv4' or $type eq 'ipv6'}
                {tmplinclude file='search/additional/ip.phtml'}
            {/if}
        {/if}

        <div class="btn-group">
            <a class="btn" href="{genUrl controller="customer" action="overview" id=$cust->getId()}">Overview</a>
            <a class="btn" href="{genUrl controller="customer" action="overview" id=$cust->getId() tab=ports}">Ports</a>
            <a class="btn" href="{genUrl controller="statistics" action="member-drilldown" monitorindex="aggregate" shortname=$cust->getShortname()}">
                Statistics  
            </a>
            <a class="btn" href="{genUrl controller="statistics" action="p2p" shortname=$cust->getShortname()}">
                P2P  
            </a>
            <a class="btn" href="{genUrl controller="customer" action="overview" id=$cust->getId() tab=users}">Users</a>
            <a class="btn" href="{genUrl controller="customer" action="overview" id=$cust->getId() tab=contacts}">Contacts</a>
        </div>


    </div>
</div>
{/foreach}

{/if}

{/if}


<div class="row-fluid">

    <div class="span12">

        {if isset( $search ) and $search != '' and not ( isset( $results ) and count( $results ) )}
            <h3>No results found.</h3>
        {/if}
    
    </div>
    
</div>

<div class="row-fluid">

    <div class="span12">

    <form class="form-search" method="get" action="{genUrl controller="search" action="do"}">
        <div class="input-append">
            <input type="text" class="search-query" style="input-large" placeholder="Search..." name="search"
                {if isset( $search )}value="{$search}"{/if}
            >
            <button type="submit" class="btn">Search</button>
        </div>
        <a class="btn btn-small" id="searchHelp" data-toggle="modal" data-target="#searchHelpModal">
            <i class="icon-question-sign"></i>&nbsp;Search Help
        </a>
    </form>
    
    </div>
    
</div>


{tmplinclude file="footer.phtml"}
