<?php

/**
 * MacaddressTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class MacaddressTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object MacaddressTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Macaddress');
    }
}