<?php

/*
 * Copyright (C) 2009-2011 Internet Neutral Exchange Association Limited.
 * All Rights Reserved.
 * 
 * This file is part of IXP Manager.
 * 
 * IXP Manager is free software: you can redistribute it and/or modify it
 * under the terms of the GNU General Public License as published by the Free
 * Software Foundation, version v2.0 of the License.
 * 
 * IXP Manager is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
 * FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License for
 * more details.
 * 
 * You should have received a copy of the GNU General Public License v2.0
 * along with IXP Manager.  If not, see:
 * 
 * http://www.gnu.org/licenses/gpl-2.0.html
 */


/**
 * PatchPanelPort
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 *
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: PatchPanelPort.php 446 2011-05-26 13:40:19Z barryo $
 */
/**
 *
 * Auto-generated Doctrine ORM File
 *
 * @category ORM
 * @package IXP_ORM_Models
 * @copyright Copyright 2008 - 2010 Internet Neutral Exchange Association Limited <info (at) inex.ie>
 * @author Barry O'Donovan <barryo (at) inex.ie>
 */
class PatchPanelPort extends BasePatchPanelPort
{

    ///////////////////////////////////////////////
    ////
    //// Cable Types
    ////

    const CABLE_TYPE_UTP     = 1;
    const CABLE_TYPE_UTP_5   = 2;
    const CABLE_TYPE_UTP_5e  = 3;
    const CABLE_TYPE_UTP_6   = 4;

    const CABLE_TYPE_SM      = 20;

    const CABLE_TYPE_MM      = 40;
    const CABLE_TYPE_MM_OM1  = 41; // 62.5/125 µm
    const CABLE_TYPE_MM_OM2  = 42; // 50/125 µm

    public static $CABLES_TYPES = array(
        PatchPanelPort::CABLE_TYPE_UTP     => 'UTP',
        PatchPanelPort::CABLE_TYPE_UTP_5   => 'UTP Cat5',
        PatchPanelPort::CABLE_TYPE_UTP_5e  => 'UTP Cat5e',
        PatchPanelPort::CABLE_TYPE_UTP_6   => 'UTP Cat6',
        PatchPanelPort::CABLE_TYPE_SM      => 'SM (Single Mode)',
        PatchPanelPort::CABLE_TYPE_MM      => 'MM (Multi Mode)',
        PatchPanelPort::CABLE_TYPE_MM_OM1  => 'MM OM1 (Multi Mode 62.5/125 µm)',
        PatchPanelPort::CABLE_TYPE_MM_OM2  => 'MM OM2 (Multi Mode 50/125 µm)'
    );


    ///////////////////////////////////////////////
    ////
    //// Interface Types
    ////

    const INTERFACE_TYPE_RJ45     = 1;

    const INTERFACE_TYPE_SC       = 10;
    const INTERFACE_TYPE_LC       = 11;
    const INTERFACE_TYPE_MU       = 12;

    public static $INTERFACE_TYPES = array(
        PatchPanelPort::INTERFACE_TYPE_RJ45  => 'RJ45',
        PatchPanelPort::INTERFACE_TYPE_SC    => 'SC',
        PatchPanelPort::INTERFACE_TYPE_LC    => 'LC',
        PatchPanelPort::INTERFACE_TYPE_MU    => 'MU'
    );



    ///////////////////////////////////////////////////////////////////
    ////
    //// Patch Panels can have two sides: INNER and OUTER
    ////
    //// If in doubt, inner has more internal cabinet than outer has.

    const SIDE_INNER = 1;
    const SIDE_OUTER = 2;

    public static $SIDES = array(
        PatchPanelPort::SIDE_INNER => 'Inner (back)',
        PatchPanelPort::SIDE_OUTER => 'Outer (front)'
    );

}