<?php

/*
 * Copyright (C) 2009-2011 Internet Neutral Exchange Association Limited.
 * All Rights Reserved.
 * 
 * This file is part of IXP Manager.
 * 
 * IXP Manager is free software: you can redistribute it and/or modify it
 * under the terms of the GNU General Public License as published by the Free
 * Software Foundation, version v2.0 of the License.
 * 
 * IXP Manager is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
 * FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License for
 * more details.
 * 
 * You should have received a copy of the GNU General Public License v2.0
 * along with IXP Manager.  If not, see:
 * 
 * http://www.gnu.org/licenses/gpl-2.0.html
 */


/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
/**
 *
 * Auto-generated Doctrine ORM File
 *
 * @category ORM
 * @package IXP_ORM_Models
 * @copyright Copyright 2008 - 2010 Internet Neutral Exchange Association Limited <info (at) inex.ie>
 * @author Barry O'Donovan <barryo (at) inex.ie>
 */
class Switchport extends BaseSwitchport
{

    const TYPE_UNSET          = 0;
    const TYPE_PEERING        = 1;
    const TYPE_MONITOR        = 2;
    const TYPE_CORE           = 3;
    const TYPE_OTHER          = 4;
    const TYPE_MANAGEMENT     = 5;

    public static $TYPE_TEXT = array(
        Switchport::TYPE_UNSET      => 'Unset / Unknown',
        Switchport::TYPE_PEERING    => 'Peering',
        Switchport::TYPE_MONITOR    => 'Monitor',
        Switchport::TYPE_CORE       => 'Core',
        Switchport::TYPE_OTHER      => 'Other',
        Switchport::TYPE_MANAGEMENT => 'Management'
    );


    public function setUp()
    {
        parent::setUp();

        $this->hasOne( 'SwitchTable',       array( 'local' => 'switchid', 'foreign' => 'id') );
        $this->hasOne( 'Physicalinterface', array( 'local' => 'id',       'foreign' => 'switchportid') );
    }

}
