<div class="row-fluid">
{*
    <div class="span6">
    
        <h3>Recents Changes and Updates to IXP Manager</h3>
        <br />

        <ul>
            <li>
                <strong>Peer to peer (member to member) traffic graphs are now available.</strong>. 
                All feed back greatly appreciated.
                <a href="{genUrl controller="dashboard" action="p2p"}">Check yours out here</a>.
            </li>
            <li>
                <strong>New Peering Manager now available</strong>. 
                <a href="{genUrl controller="peering-manager"}">Check it out here</a>.
            </li>
            <li>
                Peering matrices are now working again - with added IPv6 support - and lots
                of new bells and whistles.
                <a href="{genUrl controller="peering-matrix"}">Check them out here</a>.
            </li>
            <li>
                You can now manage your mailing list subscriptions via
                your <a href="{genUrl controller="profile"}">profile page</a>.
            </li>
            <li> Redesigned <a href="{genUrl controller="dashboard" action="statistics"}">statistics pages</a> making them clearer and more intuitive. </li>
            <li>
                Added weather maps for peering <a href="{genUrl controller="dashboard" action="weathermap" id=1}">LAN 1</a>
                and <a href="{genUrl controller="dashboard" action="weathermap" id=2}">LAN 2</a> showing inter-PoP
                trunk untilisation and other information based on feedback from members.
            </li>
            
        </ul>
        
    </div>
    
    <div class="span6">
        &nbsp;
    </div>
*}
</div>

