{tmplinclude file="header.phtml" pageTitle="IXP Manager :: Member Dashboard"}

<div class="page-content">

{OSS_Message}

{if not $user->getCustomer()->isTypeAssociate()}

    <ul class="nav nav-tabs">
        <li class="active">
            <a href="#tab1" data-toggle="tab">Overview</a></li>
            {if $multiIXP}
                <li><a href="#tab-ixps" data-toggle="tab">IXPs</a></li>
            {/if}
            <li><a href="#tab-details" data-toggle="tab">My Details</a></li>
            <li><a href="#tab3" data-toggle="tab">Ports</a></li>

            {if $resellerMode && $cust->isReseller()}
                <li>
                    <a href="#tab-resold-customers" data-toggle="tab">Resold Customers</a>
                </li>
            {/if}

            {if count( $custNotes )}
                <li>
                    <a href="#tab-content-notes" id="tab-notes" data-toggle="tab">
                        Notes {if isset( $unreadNotes ) and $unreadNotes}
                            <span id="notes-unread-indicator" class="badge badge-success">{$unreadNotes}</span>
                        {/if}
                    </a>
                </li>
            {/if}
            <li>
                <a href="#tab-cross-connects" data-toggle="tab">Cross Connects</a>
            </li>
            {if !config( 'ixp_fe.frontend.disabled.rs-prefixes', false ) and $user->getCustomer()->isRouteServerClient()}
                <li>
                    <a href="{route('rs-prefixes@view', [ 'cid' => $user->getCustomer()->getId() ])}">
                        Prefixes
                        {if $rsRoutes.adv_nacc.total gt 0}
                            <span class="badge badge-important">{$rsRoutes.adv_nacc.total}</span>
                        {/if}
                        &raquo;
                    </a>
                </li>
            {/if}

            {if !isset( $options['frontend']['disabled']['peering-manager'] ) or !$options['frontend']['disabled']['peering-manager'] }
                <li><a href="{genUrl controller="peering-manager"}">Peering Manager &raquo;</a></li>
            {/if}

            <li><a href="{genUrl controller="statistics" action="member"}">Statistics &raquo;</a></li>

            {if config('grapher.backends.sflow.enabled')}
                <li><a href="{route( "statistics@p2p", [ 'cid' => $user->getCustomer()->getId() ] )}">Peer to Peer Traffic &raquo;</a></li>
            {/if}
    </ul>

    <div class="tab-content">

        <div class="tab-pane active" id="tab1">
            <!-- Overview Tab -->
            {tmplinclude file="dashboard/index-tabs/overview.phtml"}
        </div>

        {if $multiIXP}
            <div class="tab-pane" id="tab-ixps">
                {tmplinclude file="dashboard/index-tabs/ixps.phtml"}

            </div>
        {/if}

        <div class="tab-pane" id="tab-details">
            <!-- Details Tab -->
            {tmplinclude file="dashboard/index-tabs/details.phtml"}

        </div>

        <div class="tab-pane" id="tab3">
            <!-- Connections -->
            {tmplinclude file="dashboard/index-tabs/connections.phtml"}

        </div>

        {if $resellerMode && $cust->isReseller()}
            <div class="tab-pane" id="tab-resold-customers">
                {tmplinclude file="customer/overview-tabs/resold-customers.phtml"}
            </div>
        {/if}

        {if count( $custNotes )}
            <div class="tab-pane" id="tab-content-notes">
                {tmplinclude file="customer/overview-tabs/notes.phtml"}

            </div>
        {/if}

        <div class="tab-pane" id="tab-cross-connects">
            {tmplinclude file="customer/overview-tabs/cross-connects.phtml"}
        </div>
    </div>

{else}

    {tmplinclude file="dashboard/index-tabs/associate.phtml"}

{/if}

</div>

{tmplinclude file="footer.phtml"}
