<div class="btn-group" id="vlan-btn-group">
    <a class="btn btn-mini dropdown-toggle" data-toggle="dropdown" id="vlan-dd">
        <span id="vlan-dd-text">{if isset( $vid ) and $vid}{$vlans.$vid}{else}Limit to VLAN...{/if}</span>
        <span class="caret"></span>
    </a>
    <ul id="vlan-dd-ul" class="dropdown-menu">
        {foreach $vlans as $vid => $vname}
            <li> <a id="vlan-{$vid}" href="{genUrl controller=$controller action='list' vlan=$vid}">{$vname}</a> </li>
        {/foreach}
    </ul>
</div>
