<html>
<head>
    <title>Billing Details Change Notification</title>
</head>

<body>

<h3>Dear Accounts,</h3>

<p>
Billing details have been updated for <em>{$customer->getName()}</em>.
</p>

<table style="border-collapse:collapse; border: 1px solid black;">
    <tr>
        <th style="border: 1px solid black;"></th>
        <th style="border: 1px solid black;">Old Details</th>
        <th style="border: 1px solid black;">New Details</th>
    </tr>
    <tr>
        <th style="border: 1px solid black;">Name</th>
        <td style="border: 1px solid black;">{$oldDetails->getBillingContactName()}</td>
        <td style="border: 1px solid black;">{$customer->getBillingDetails()->getBillingContactName()}</td>
    </tr>
    <tr>
        <th style="border: 1px solid black;">Address</th>
        <td style="border: 1px solid black;">
            {$oldDetails->getBillingAddress1()}<br/>
            {$oldDetails->getBillingAddress2()}<br/>
            {$oldDetails->getBillingAddress3()}<br/>
            {$oldDetails->getBillingTownCity()}<br/>
            {$oldDetails->getBillingPostcode()}<br/>
            {$oldDetails->getBillingCountry()}
        </td>
        <td style="border: 1px solid black;">
            {$customer->getBillingDetails()->getBillingAddress1()}<br/>
            {$customer->getBillingDetails()->getBillingAddress2()}<br/>
            {$customer->getBillingDetails()->getBillingAddress3()}<br/>
            {$customer->getBillingDetails()->getBillingTownCity()}<br/>
            {$customer->getBillingDetails()->getBillingPostcode()}<br/>
            {$customer->getBillingDetails()->getBillingCountry()}
        </td style="border: 1px solid black;">
    </tr>
    <tr>
        <th style="border: 1px solid black;">Email</th>
        <td style="border: 1px solid black;">{$oldDetails->getBillingEmail()}</td>
        <td style="border: 1px solid black;">{$customer->getBillingDetails()->getBillingEmail()}</td>
    </tr>
    <tr>
        <th style="border: 1px solid black;">Phone</th>
        <td style="border: 1px solid black;">{$oldDetails->getBillingTelephone()}</td>
        <td style="border: 1px solid black;">{$customer->getBillingDetails()->getBillingTelephone()}</td>
    </tr>
    <tr>
        <th style="border: 1px solid black;">VAT Number</th>
        <td style="border: 1px solid black;">{$oldDetails->getVatNumber()}</td>
        <td style="border: 1px solid black;">{$customer->getBillingDetails()->getVatNumber()}</td>
    </tr>
    <tr>
        <th style="border: 1px solid black;">VAT Rate</th>
        <td style="border: 1px solid black;">{$oldDetails->getVatRate()}</td>
        <td style="border: 1px solid black;">{$customer->getBillingDetails()->getVatRate()}</td>
    </tr>
    <tr>
        <th style="border: 1px solid black;">Required Purchase Order</th>
        <td style="border: 1px solid black;">{if $oldDetails->getPurchaseOrderRequired()}Yes{else}No{/if}</td>
        <td style="border: 1px solid black;">{if $customer->getBillingDetails()->getPurchaseOrderRequired()}Yes{else}No{/if}</td>
    </tr>
    <tr>
        <th style="border: 1px solid black;">Invoice Method</th>
        <td style="border: 1px solid black;">{$oldDetails->getInvoiceMethod()}</td>
        <td style="border: 1px solid black;">{$customer->getBillingDetails()->getInvoiceMethod()}</td>
    </tr>
    <tr>
        <th style="border: 1px solid black;">Invoice Email</th>
        <td style="border: 1px solid black;">{$oldDetails->getInvoiceEmail()}</td>
        <td style="border: 1px solid black;">{$customer->getBillingDetails()->getInvoiceEmail()}</td>
    </tr>
    <tr>
        <th style="border: 1px solid black;">Billing Frequency</th>
        <td style="border: 1px solid black;">{$oldDetails->getBillingFrequency()}</td>
        <td style="border: 1px solid black;">{$customer->getBillingDetails()->getBillingFrequency()}</td>
    </tr>
</table>


<p>
Kind regards,
</p>

<p>
{$options.identity.name}<br />
<a href="mailto:{$options.identity.email}">{$options.identity.email}</a>
</p>

</body>
</html>
