

<h2>{$cust->getName()}</h2>

{if $dIn gt $threasholdIn}
<p>
<strong>INBOUND:</strong>

	{if $percentIn neq 'NONE'}
		There has been a <strong>{$percentIn}% {$sIn}</strong> is this
		member's traffic as recorded yesterday ({mrtgScale value=$in})
		compared to the average over the past {$days} days
		({mrtgScale value=$meanIn}). (Standard deviation: {mrtgScale value=$stddevIn}).
	{else}
		No previous records - possibly a new connection brought live?
	{/if}

</p>
{/if}

{if $dOut gt $threasholdOut}
<p>
<strong>OUTBOUND:</strong>

	{if $percentIn neq 'NONE'}
		There has been a <strong>{$percentOut}% {$sOut}</strong> is this member's
		traffic as recorded yesterday ({mrtgScale value=$out}) compared to the
		average over the past {$days} days ({mrtgScale value=$meanOut}). (Standard
		deviation: {mrtgScale value=$stddevOut}).
	{else}
		No previous records - possibly a new connection brought live?
	{/if}
</p>
{/if}

<p>
<a href="{$options.identity.url}statistics/member/shortname/{$cust->getShortname()}">
	<img src="cid:{$cust->getShortname()}" alt="[{$cust->getShortname()}]" />
</a>
</p>

