

<h2>{$cust->getName()} :: {$switchport}</h2>

{if $utilIn gt $threshold}
<p>
<strong>INBOUND:</strong> Traffic inbound on this port reached a maximum of {$utilIn*100|string_format:"%.2f"}%.
</p>
{/if}

{if $utilOut gt $threshold}
<p>
<strong>OUTBOUND:</strong> Traffic outbound on this port reached a maximum of {$utilOut*100|string_format:"%.2f"}%.
</p>
{/if}

<p>
<a href="{genUrl controller="statistics" action="member" shortname=$cust->getShortname()}">
    <img src="cid:{$cust->getShortname()}" alt="[{$cust->getShortname()}]" />
</a>
</p>

