
Dear New Member,

Firstly, welcome to {$options.identity.orgname}! This is your {$options.identity.name} welcome e-mail.

Please take some time to read this email -- it contains important information concerning your {$options.identity.orgname} membership.

Several sections of this email require your input; these are all clearly marked by the heading "Your Input".  We would appreciate if you could provide us with all the details requested as this will allow us to provide you and other {$options.identity.orgname} members with a better quality of service.


---- COMPLETE YOURSELF VIA SKIN ----


Welcome to {$options.identity.orgname}.




