{tmplinclude file="header.phtml"}

{if $user->getPrivs() eq 3}
    <ul class="breadcrumb">
        <li>
            <a href="{genUrl}">Home</a> <span class="divider">/</span>
        </li>
        <li class="active">
            About IXP Manager
        </li>
    </ul>
{else}
    <div class="page-content">
        <div class="page-header">
            <h1>About IXP Manager</h1>
        </div>
{/if}

<p>
	<strong>IXP Manager</strong> is primarily a web application with associated
	scripts and utilities which allows Internet Exchange Points (IXPs) to
	manage new members (or customers), provision new connections and services and
	monitor traffic usage. It also has a self contained customer portal allowing
	IXP members to view their IXP traffic statistics and a unique tool called
	<em>Peering Manager</em> enabling IXP members to request, manage and track
	peerings with other members.
</p>

<p>
	IXP Manager was built entirely in house by the INEX operations team
	to support the running of the exchange. <a href="https://www.inex.ie/">INEX</a>
	(Internet Neutral Exchange Association) is Ireland's IP peering hub.
</p>

<p>
	INEX are pleased to to be able to release IXP Manager under an open source license
	(the <a href="http://www.gnu.org/licenses/gpl-2.0.html">GNU Public License V2)</a>
	which we hope will benefit the wider IXP community, and especially new and small
	IXPs looking to expand.
</p>

<p>
	IXP Manager is written in PHP using the Zend Framework, the Doctrine ORM, the
	Smarty templating engine, <a href="http://www.opensolutions.ie/">Open Solutions</a>'
	extensions to Zend - <a href="https://github.com/opensolutions/OSS-Framework/wiki">the
	OSS Framework</a>, JQuery and many other smaller components. The project website
	and source code can be viewed at
	<a href="https://github.com/inex/IXP-Manager/wiki">https://github.com/inex/IXP-Manager</a>.
</p>

<p>
	There is a mailing / discussion list for IXP Manager. You can join and view the
	archives at: <a href="https://www.inex.ie/mailman/listinfo/ixpmanager">https://www.inex.ie/mailman/listinfo/ixpmanager</a>.
</p>

<h3>Software License</h3>

<p>
	<strong>
		Copyright (C) 2009 - {$smarty.now|date_format:"%Y"} Internet Neutral Exchange Association Limited.<br />
		All Rights Reserved.
	</strong>
</p>

<pre>
IXP Manager is free software: you can redistribute it and/or modify it
under the terms of the GNU General Public License as published by the Free
Software Foundation, version v2.0 of the License.

IXP Manager is distributed in the hope that it will be useful, but WITHOUT
ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License for
more details.
</pre>

</div>

{tmplinclude file="footer.phtml"}
