</div>

{if $isEdit}

<div class="row-fluid">

    <h3>
        Physical Interfaces
        <a class="btn btn-mini"
            href="{genUrl controller='physical-interface' action='add' vintid=$object->getId()}"><i class="icon-plus"></i></a>
    </h3>

</div>

<div class="row-fluid">

    <div class="span9">
        {if count( $physInts )}
            <table class="table">

            <thead>
                <tr>
                    <th>Location</th>
                    <th>Peering Port</th>
                    <th>Fanout Port</th>
                    <th>Speed/Duplex</th>
                    <th></th>
                </tr>
            </thead>

            <tbody>
            {foreach $physInts as $int}

                <tr>
                    <td>
                        {if $int->getSwitchPort()->getSwitcher()->getCabinet()}{$int->getSwitchPort()->getSwitcher()->getCabinet()->getLocation()->getName()}{/if}
                    </td>
                    <td>
                        {if $int->getSwitchPort()->getType() != SWITCHPORT::TYPE_FANOUT}
                            {$int->getSwitchPort()->getSwitcher()->getName()}::{$int->getSwitchPort()->getIfName()}
                        {else if $int->getPeeringPhysicalInterface()}
                            <a href="{genUrl controller=$controller action=$action id=$int->getPeeringPhysicalInterface()->getVirtualInterface()->getId()}">
                                {$int->getPeeringPhysicalInterface()->getSwitchPort()->getSwitcher()->getName()}::{$int->getPeeringPhysicalInterface()->getSwitchPort()->getIfName()}
                            </a>
                        {/if}
                    </td>
                    <td>
                        {if $int->getSwitchPort()->getType() == SWITCHPORT::TYPE_FANOUT}
                            {$int->getSwitchPort()->getSwitcher()->getName()}::{$int->getSwitchPort()->getIfName()}
                        {else if $int->getFanoutPhysicalInterface()}
                            <a href="{genUrl controller=$controller action=$action id=$int->getFanoutPhysicalInterface()->getVirtualInterface()->getId()}">
                                {$int->getFanoutPhysicalInterface()->getSwitchPort()->getSwitcher()->getName()}::{$int->getFanoutPhysicalInterface()->getSwitchPort()->getIfName()}
                            </a>
                        {/if}
                    </td>
                    <td>
                        {$int->getSpeed()}/{$int->getDuplex()}
                        {if $int->getAutoneg()}
                            <span class="badge phys-int-autoneg-state" data-toggle="tooltip" title="Auto-Negotiation Enabled">AN</span>
                        {else}
                            <span class="badge phys-int-autoneg-state" data-toggle="tooltip" title="Hard-Coded - Auto-Negotiation DISABLED">HC</span>
                        {/if}
                    </td>
                    <td>
                        <div class="btn-group">
                            <a class="btn btn-mini" href="{genUrl controller='physical-interface' action='edit' id=$int->getId() vintid=$object->getId()}"><i class="icon-pencil"></i></a>
                            <a data-url="{genUrl controller='physical-interface' action='delete' id=$int->getId() vintid=$object->getId()}"
                                class="btn btn-mini" id="object-delete-physint-{$int->getId()}"><i class="icon-trash"></i></a>
                        </div>
                    </td>
                </tr>

            {/foreach}

            </tbody>

            </table>

        {else}

            <p>
                There are no physical interfaces defined for this virtual interface.
                <a href="{genUrl controller="physical-interface" action="add" vintid=$object->getId()}">Add one now...</a>
            </p>

        {/if}

    </div>
    <br />
</div>


<div class="row-fluid">

    <h3>
        VLAN Interfaces
        <a class="btn btn-mini"
            href="{genUrl controller='vlan-interface' action='add' vintid=$object->getId()}"><i class="icon-plus"></i></a>
    </h3>
</div>

<div class="row-fluid">
    <div class="span9">
    {if count( $vlanInts )}

        <table class="table">

            <thead>
                <tr>
                    <th>VLAN Name</th>
                    <th>VLAN Tag</th>
                    <th>Layer2 Address</th>
                    <th>IPv4 Address</th>
                    <th>IPv6 Address</th>
                    <th></th>
                </tr>
            </thead>

            <tbody>
            {foreach $vlanInts as $int}

                <tr>
                    <td>
                        {$int->getVlan()->getName()}
                    </td>
                    <td>
                        {$int->getVlan()->getNumber()}
                    </td>
                    <td>
                        <a href="{genUrl controller='layer-2-address'}/vlan-interface/{$int->getId()}">
                            {if !count( $int->getLayer2Addresses() )}
                                <span class="label label-warning">(none)</span>
                            {elseif count( $int->getLayer2Addresses() ) > 1}
                               <span class="label label-warning">(multiple)</span>
                            {else}
                                {assign var="l2a" value=$int->getLayer2Addresses()}
                                {$l2a[0]->getMacFormattedWithColons()}
                            {/if}
                        </a>
                    </td>
                    <td>
                        {if $int->getIPv4Enabled() and $int->getIPv4Address()}
                            {$int->getIPv4Address()->getAddress()}
                        {/if}
                    </td>
                    <td>
                        {if $int->getIPv6Enabled() and $int->getIPv6Address()}
                            {$int->getIPv6Address()->getAddress()}
                        {/if}
                    </td>
                    <td>
                        <div class="btn-group">
                            <a class="btn btn-mini" href="{genUrl controller='vlan-interface' action='edit' id=$int->getId() vintid=$object->getId()}"><i class="icon-pencil"></i></a>
                            <a data-url="{genUrl controller='vlan-interface' action='delete' id=$int->getId() vintid=$object->getId()}"
                                class="btn btn-mini" id="object-delete-vlanint-{$int->getId()}"><i class="icon-trash"></i></a>
                        </div>
                    </td>
                </tr>

            {/foreach}

            </tbody>

        </table>

    {else}

        <p>
            There are no VLAN interfaces defined for this virtual interface.
            <a href="{genUrl controller='vlan-interface' action='add' vintid=$object->getId()}">Add one now...</a>
        </p>

    {/if}
    </div>
</div>


{if config('grapher.backends.sflow.enabled')}

<div class="row-fluid">

    <h3>
        Sflow Receivers
        <a class="btn btn-mini"
            href="{genUrl controller='sflow-receiver' action='add' vintid=$object->getId()}"><i class="icon-plus"></i></a>
    </h3>
</div>

<div class="row-fluid">
    <div class="span9">
    {if count( $sflowReceivers )}

        <table class="table">

            <thead>
                <tr>
                    <th>Target IP</th>
                    <th>Target Port</th>
                    <th></th>
                </tr>
            </thead>

            <tbody>
            {foreach $sflowReceivers as $r}

                <tr>
                    <td>
                        {$r->getDstIp()}
                    </td>
                    <td>
                        {$r->getDstPort()}
                    </td>
                    <td>
                        <div class="btn-group">
                            <a class="btn btn-mini" href="{genUrl controller='sflow-receiver' action='edit' id=$r->getId() vintid=$object->getId()}"><i class="icon-pencil"></i></a>
                            <a data-url="{genUrl controller='sflow-receiver' action='delete' id=$r->getId() vintid=$object->getId()}"
                                class="btn btn-mini" id="object-delete-receiver-{$r->getId()}"><i class="icon-trash"></i></a>
                        </div>
                    </td>
                </tr>

            {/foreach}

            </tbody>

        </table>

    {else}

        <p>
            There are no Sflow receivers defined for this virtual interface.
            <a href="{genUrl controller='sflow-receiver' action='add' vintid=$object->getId()}">Add one now...</a>
        </p>

    {/if}
    </div>
</div>

{/if} {* end sflow *}

{/if}
