<li class="pull-right"> 
    <div class="btn-group">
        <a class="btn btn-mini dropdown-toggle" data-toggle="dropdown" href="#"><i class="icon-plus"></i>&nbsp;<span class="caret"></span></a>
        <ul class="dropdown-menu pull-right">
            <li>
                <a href="{genUrl controller='virtual-interface' action='quick-add'}">Add Interface Wizard...</a>
            </li>
            <li>
                <a href="{genUrl controller=$controller action="add"}">Virtual Interface Only...</a>
            </li>
        </ul>
    </div>
</li>

