{tmplinclude file="header.phtml" pageTitle="IXP Manager :: Drupal Login"}

{OSS_Message}

<div class="row">

    <div class="span6 offset3">

    <h2>Drupal Login</h2>
    
    <p>Use this form to login to the INEX's Drupal content management system.</p>
    
    <p>For security reasons, we require you to re-enter your password.</p>
    
    <form action="https://www.inex.ie/user" method="post" name="loginForm" id="loginForm" class="horizontal-form">

        <fieldset class="control-group" id="div-form-name">
            <label for="name" class="control-label">Username</label>
            <div id="div-controls-name" class="controls">
                <input id="name" name="name" type="text" value="{$user->getUsername()}" />
            </div>
        </fieldset>

        <fieldset class="control-group" id="div-form-pass">
            <label for="pass" class="control-label">Password</label>
            <div id="div-controls-pass" class="controls">
                <input id="pass" name="pass" type="password" value="" />
            </div>
        </fieldset>

        <fieldset class="form-actions">
            <input type="hidden" name="form_id" id="edit-user-login" value="user_login" />
            <input type="submit" name="op" class="btn btn-success" value="Log in" />
        </fieldset>
        
        </form>
    </div>
</div>


{tmplinclude file="footer.phtml"}
