{tmplinclude file="header.phtml"}

<div class="page-content">

    <div class="page-header">
        <h1>Login to IXP Manager</h1>
    </div>

{OSS_Message}

<div class="row">

    {if !isset( $options.identity.ixp.biglogo )}
        <div class="span12">
            <h2 align="center">[Your Logo Here]</h2>
            <p align="center">
                Configure <code>identity.ixp.biglogo</code> in <code>application.ini</code>.
                <br /><br /><br /><br />
            </p>
    {else}
        <div class="span6 offset4">
            <p align="center">
                <img src="{genUrl}{$options.identity.ixp.biglogo}" />
            </p>
    {/if}
    </div>
    
</div>

<div class="row">
    <div class="span6 offset3">
        {$form}
    </div>
</div>

<div class="row">

    <div class="span6 offset3">
        <fieldset class="form-actions">
            <a class="btn" href="{genUrl controller="auth" action="forgotten-password"}">Forgotten Password?</a>
            <a class="btn" href="{genUrl controller="auth" action="forgotten-username"}">Forgotten Username?</a>
        </fieldset>
    </div>

</div>

<p align="center">
    For help, please contact {mailto address=$options.identity.email encode='javascript' text=$options.identity.name}.
</p>

</div>

{tmplinclude file="footer.phtml"}
