{tmplinclude file="header.phtml"}

<div class="page-content">

    <div class="page-header">
        <h1>Login to IXP Manager</h1>
    </div>

{OSS_Message}

<div class="row">

    {if !isset( $options.identity.biglogo )}
        <div class="span12">
            <h2 align="center">[Your Logo Here]</h2>
            <p align="center">
                Configure <code>identity.ixp.biglogo</code> in <code>application.ini</code>.
                <br /><br /><br /><br />
            </p>
    {else}
        <div class="span12">
            <p align="center">
                <img src="{$options.identity.biglogo}" />
            </p>
    {/if}
        </div>
    
</div>

<div class="row">
    <div class="span6 offset3">
        {$form}
    </div>
</div>

<p align="center">
    For help, please contact {mailto address=$options.identity.email encode='javascript' text=$options.identity.name}.
</p>

</div>

<script type="text/javascript">
    $( document ).ready( function(){
        $('#username').focus();
    });
</script>

{tmplinclude file="footer.phtml"}
