{tmplinclude file="header.phtml"}

<div class="page-content">

    <div class="page-header">
        <h1>Lost Username</h1>
    </div>


{OSS_Message}


<div class="row">

    <div class="span12">
        <p align="center">
            <img src="{$options.identity.biglogo}" />
        </p>
    </div>
    
</div>

<div class="row">

    <div class="span6 offset3">
    
        <p align="center">
            <br />
            Please enter your email address and we will send you any related username(s) by email.
        </p>
        
        {$form}
        
    </div>
</div>

<p align="center">
    For help please contact {mailto address=$options.identity.email encode='javascript' text=$options.identity.name}.
</p>

</div>

{tmplinclude file="footer.phtml"}
