{tmplinclude file="header.phtml"}

<div class="page-content">

    <div class="page-header">
        <h1>Lost Password</h1>
    </div>

{OSS_Message}

<div class="row">

    <div class="span6 offset4">
        <img src="{$options.identity.biglogo}" />
    </div>
    
</div>

<div class="row">

    <div class="span6 offset3">
    
        <p align="center">
            Please enter your username and we will send you a password reset token by email.
        </p>

        {$form}
    </div>
</div>

<p align="center">
    For help please contact {mailto address=$options.identity.email encode='javascript' text=$options.identity.name}.
</p>

</div>

{tmplinclude file="footer.phtml"}
