{tmplinclude file="header.phtml"}

<div class="page-content">

    <div class="page-header">
        <h1>Password Reset</h1>
    </div>

{OSS_Message}

<div class="row">

    <div class="span6 {if isset( $options.identity.biglogoconf.offset )}{$options.identity.biglogoconf.offset}{/if}">
        <img src="{$options.identity.biglogo}" />
    </div>
    
</div>

<div class="row">

    <div class="span6 offset3">
    
        <p align="center">
            <br />
            Please enter your username, the token that was emailed to you and a new password:
            {if isset( $options.resources.auth.oss.pwhash ) and $options.resources.auth.oss.pwhash eq 'plaintext'}
                <div class="alert alert-info">
                    Please note that your passwords are not hashed in the backend database. Choose a unique password for IXP Manager.
                    Please <a href="https://github.com/inex/IXP-Manager/wiki/Password-Hashing" target="_blank">read this page</a>
                    to understand why we do this.
                </div>
            {/if}
        </p>

        {$form}
        
    </div>
</div>

<p align="center">
    For help please contact {mailto address=$options.identity.email encode='javascript' text=$options.identity.name}.
</p>

</div>

{tmplinclude file="footer.phtml"}
