<div class="btn-group">
    <a class="btn btn-mini have-tooltip-below" href="{genUrl module=$module controller=$controller action='view' id=$row.id}" title="Preview"><i class="icon-eye-open"></i></a>
    <a class="btn btn-mini have-tooltip-below" href="{genUrl module=$module controller='contact' action='list' cgid=$row.id}" title="List Contacts"><i class="icon-user"></i></a>
    {if !isset( $feParams->readonly ) or !$feParams->readonly}
	<a class="btn btn-mini have-tooltip-below" href="{genUrl module=$module controller=$controller action='edit' id=$row.id}" title="Edit"><i class="icon-pencil"></i></a>
	<a class="btn btn-mini have-tooltip-below" id='list-delete-{$row.id}' href="{genUrl module=$module controller=$controller action='delete' id=$row.id}" title="Delete"><i class="icon-trash"></i></a>
    {/if}
</div>