<form class="form-horizontal" enctype="application/x-www-form-urlencoded"
        accept-charset="UTF-8" method="post" horizontal="1"
        {if $isEdit}
            action="{genUrl controller=$controller action=$action id=$object->getId()}"
        {else}
            action="{genUrl controller=$controller action=$action}"
        {/if}>

    <div class="row" >
        <div class="span6">
            {$element->name}
            {$element->position}
            {$element->custid}
            {$element->email}
            {$element->phone}
            {$element->mobile}
            
            {if $user->getPrivs() eq 3}
                {tmplinclude file='contact/forms/edit-loginblock.phtml'}
            {/if}
        </div>
        <div class="span6">
            {$element->facilityaccess}
            {$element->mayauthorize}
            
            {if isset( $groups ) && isset( $groups['ROLE'] ) && isset( $options.contact.group.types.ROLE ) }
                {assign var=role_line value=4}
                <div class="control-group">
                    <label class="control-label" for="role">Role</label>
                    <div class="controls">
                        {foreach $groups['ROLE'] as $role }
                            {if $role@index % $role_line == 0 && $role@index != 0 }
                                <br />
                            {/if}
                            <label class="checkbox inline" style="width: 55px;" >
                                <input type="checkbox" name="role[{$role@index}]" {if isset( $contactGroups ) && isset( $contactGroups['ROLE'][$role.id] ) }checked="checked"{/if}
                                    id="role[{$role@index}]" value="{$role.id}"> {$role.name}
                            </label>
                        {/foreach}
                    </div>
                </div>
            {/if}
            
            {if $user->getPrivs() eq 2}
                {tmplinclude file='contact/forms/edit-loginblock.phtml'}
            {/if}
            
            {$element->notes}
            
            {if $user->getPrivs() eq 3}
            {if isset( $groups ) && ( count( $groups ) > 1 || ( count( $groups ) == 1 && !isset( $groups['ROLE'] ) ) ) }
                <div class="control-group">
                    <label class="control-label" for="group">Groups</label>
                    <div class="controls">
                        <table id="groups-table">
                            {assign var=row_idx value=0}
                            {if isset( $contactGroups ) && ( count( $contactGroups ) > 1 || ( count( $contactGroups ) == 1 && !isset( $contactGroups['ROLE'] ) ) ) }
                                {foreach $contactGroups as $cname => $cvalue}
                                   {if $cname != "ROLE" && isset( $options['contact']['group']['types'][$cname] )}
                                   {foreach $cvalue as $cgroup}
                                    <tr id="groups-row-{$row_idx}">
                                        <td>
                                            <select id="group-type-{$row_idx}" class="chzn-select" chzn-fix-width="1" style="width: 150px;">
                                                <option value="{$row_idx}"></option>
                                                {foreach $groups as $name => $value}
                                                    {if $name != "ROLE" && isset( $options['contact']['group']['types'][$name] ) }
                                                        <option value="{$name}" data-placeholder="Type..." {if $name == $cname}selected="selected"{/if}>{$options['contact']['group']['types'][$name]}</option>
                                                    {/if}
                                                {/foreach}
                                            </select>
                                        </td>
                                        <td>
                                            <select id="select-group-{$row_idx}" name="group[{$row_idx}]" data-placeholder="Group..." class="chzn-select" chzn-fix-width="1" style="width: 150px;">
                                            {foreach $groups[$cname] as $group}
                                                {if $name != "ROLE"}
                                                    <option value="{$group.id}" {if $group.id == $cgroup.id }selected="selected"{/if}>{$group.name}</option>
                                                {/if}
                                            {/foreach}
                                            </select>
                                        </td>
                                        <td><span class="btn btn-mini" id="remove-group-{$row_idx}"><i class="icon-remove"></i></span></td>
                                    </tr>
                                    
                                    {assign var=row_idx value=$row_idx+1}
                                    {/foreach}
                                    {/if}
                                {/foreach}
                            {/if}
                            <tr id="groups-row-{$row_idx}">
                                <td>
                                    <select id="group-type-{$row_idx}" class="chzn-select" chzn-fix-width="1" style="width: 150px;" data-placeholder="Type...">
                                        <option value="{$row_idx}"></option>
                                        {foreach $groups as $name => $value}
                                            {if $name != "ROLE"  && isset( $options['contact']['group']['types'][$name] )}
                                                <option value="{$name}">{$options['contact']['group']['types'][$name]}</option>
                                            {/if}
                                        {/foreach}
                                    </select>
                                </td>
                                <td><div class="hidden"><select id="select-group-{$row_idx}" name="group[{$row_idx}]" class="chzn-select" chzn-fix-width="1" style="width: 150px;" data-placeholder="group..."></select></div></td>
                                <td><div  id="remove-group-{$row_idx}" class="hidden btn btn-mini"><i class="icon-remove"></i></div></td>
                            </tr>
                        </table>
                    </div>
                </div>
            {/if} {* isset( $groups ) && ( count( $groups ) > 1 || ( count( $groups ) == 1 && !isset( $groups['ROLE'] ) ) ) *}
            {/if} {* $user->getPrivs() eq USER::AUTH_SUPERUSER *}
        </div>
    </div>
    
    <div class="form-actions">
        {$element->submit}
        {$element->cancel}

    </div>

    
</form>
<script>

{if isset( $groups ) && ( count( $groups ) > 1 || ( count( $groups ) == 1 && !isset( $groups['ROLE'] ) ) ) }
    {if $user->getPrivs() eq 3}
        {tmplinclude file="contact/js/groups.js" row_idx=$row_idx}
    {/if}
{/if}
    
$( document ).ready( function(){
    $( "#login" ).on( 'change', function(){
        if( $( this ).prop( "checked" ) )
            $( "#login-elements" ).show( "slow" );
        else
            $( "#login-elements" ).hide( "slow" );
    });
});

</script>
