# Copyright (C) 2009-2016 Internet Neutral Exchange Association Company Limited By Guarantee.
# All Rights Reserved.
#
# This file is part of IXP Manager.
#
# IXP Manager is free software: you can redistribute it and/or modify it
# under the terms of the GNU General Public License as published by the Free
# Software Foundation, version 2.0 of the License.
#
# IXP Manager is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
# FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License for
# more details.
#
# You should have received a copy of the GNU General Public License v2.0
# along with IXP Manager.  If not, see:
#
# IXPManager::Const
#
# Constants used by IXP Manager

package IXPManager::Const;

use warnings;
use Exporter;

our @ISA = 'Exporter';

our @EXPORT = qw(
	$status_desc
	$customer_desc
	$portstatus_desc
	$switchtype_desc
	$irrdb_config
	$switchport_type_desc

	AUTH_CUSTUSER AUTH_CUSTADMIN AUTH_SUPERUSER

	ERR_NOPRIVILEGES

	VIEW_NONE VIEW_READONLY VIEW_READWRITE

	CUST_STATUS_NORMAL CUST_STATUS_NOTCONNECTED CUST_STATUS_SUSPENDED

	CUST_TYPE_FULL CUST_TYPE_ASSOCIATE CUST_TYPE_INTERNAL CUST_TYPE_IXP
	CUST_TYPE_PROBONO

	PORTSTATUS_CONNECTED PORTSTATUS_DISABLED PORTSTATUS_NOTCONNECTED
	PORTSTATUS_XCONNECT PORTSTATUS_QUARANTINE

	SWITCHTYPE_SWITCH SWITCHTYPE_CONSOLESERVER

	IRRDB_RIPE IRRDB_RADB IRRDB_LACNIC IRRDB_APNIC IRRDB_LEVEL3
	IRRDB_ARIN
	
	SWITCHPORT_TYPE_PEERING SWITCHPORT_TYPE_MONITOR SWITCHPORT_TYPE_CORE
	SWITCHPORT_TYPE_OTHER SWITCHPORT_TYPE_MANAGEMENT SWITCHPORT_TYPE_FANOUT

	VENDORID_CISCO VENDORID_BROCADE VENDORID_EXTREME VENDORID_FORCE10
);

# These rights define the privilege system
use constant AUTH_CUSTUSER		=>	1;
use constant AUTH_CUSTADMIN		=>	2;
use constant AUTH_SUPERUSER		=>	3;

# These define the errors generated by the system
use constant ERR_NOPRIVILEGES		=>	1;

# These are used for table displays
use constant VIEW_NONE			=>	0;
use constant VIEW_READONLY		=>	1;
use constant VIEW_READWRITE		=>	2;

# Customer active flag
use constant CUST_STATUS_NORMAL		=>	1;
use constant CUST_STATUS_NOTCONNECTED	=>	2;
use constant CUST_STATUS_SUSPENDED	=>	3;

our $status_desc = {
	CUST_STATUS_NORMAL		=>	'Normal',
	CUST_STATUS_NOTCONNECTED	=>	'Not Connected',
	CUST_STATUS_SUSPENDED		=>	'Suspended',
};

# Customer 'type' flag
use constant CUST_TYPE_FULL		=>	1;
use constant CUST_TYPE_ASSOCIATE	=>	2;
use constant CUST_TYPE_INTERNAL		=>	3;
use constant CUST_TYPE_IXP		=>	3;
use constant CUST_TYPE_PROBONO		=>	4;

our $customer_desc = {
	CUST_TYPE_FULL			=>	'Full Member',
	CUST_TYPE_ASSOCIATE		=>	'Associate',
	CUST_TYPE_INTERNAL		=>	'IXP Infrastructure',
	CUST_TYPE_PROBONO		=>	'Pro Bono Connection',
};

# Port status
use constant PORTSTATUS_CONNECTED	=>	1;
use constant PORTSTATUS_DISABLED	=>	2;
use constant PORTSTATUS_NOTCONNECTED	=>	3;
use constant PORTSTATUS_XCONNECT	=>	4;
use constant PORTSTATUS_QUARANTINE	=>	5;

our $portstatus_desc = {
	PORTSTATUS_CONNECTED		=>	'Connected',
	PORTSTATUS_DISABLED		=>	'Disabled',
	PORTSTATUS_NOTCONNECTED		=>	'Not Connected',
	PORTSTATUS_XCONNECT		=>	'Awaiting X-Connect',
	PORTSTATUS_QUARANTINE		=>	'Quarantine',
};

# Switch types
use constant SWITCHTYPE_SWITCH		=>	1;
use constant SWITCHTYPE_CONSOLESERVER	=>	2;

our $switchtype_desc = {
	SWITCHTYPE_SWITCH		=> 'Switch',
	SWITCHTYPE_CONSOLESERVER	=> 'Console Server',
};

# Switch ports
use constant SWITCHPORT_TYPE_PEERING	=>	1;
use constant SWITCHPORT_TYPE_MONITOR	=>	2;
use constant SWITCHPORT_TYPE_CORE	=>	3;
use constant SWITCHPORT_TYPE_OTHER	=>	4;
use constant SWITCHPORT_TYPE_MANAGEMENT	=>	5;
use constant SWITCHPORT_TYPE_FANOUT	=>	6;
use constant SWITCHPORT_TYPE_RESELLER	=>	7;

our $switchport_type_desc = {
	SWITCHPORT_TYPE_PEERING		=>	'Peering port',
	SWITCHPORT_TYPE_MONITOR		=>	'Monitoring port',
	SWITCHPORT_TYPE_CORE		=>	'Core port',
	SWITCHPORT_TYPE_OTHER		=>	'Other port',
	SWITCHPORT_TYPE_MANAGEMENT	=>	'Management port',
  	SWITCHPORT_TYPE_FANOUT      	=>	'Reseller fanout port',
  	SWITCHPORT_TYPE_RESELLER      	=>	'Reseller uplink port',
};

# Vendor IDs
use constant VENDORID_CISCO		=>	4;
use constant VENDORID_BROCADE		=>	5;
use constant VENDORID_EXTREME		=>	6;
use constant VENDORID_FORCE10		=>	7;

1;
