<div class="btn-group">
    <a class="btn btn-mini have-tooltip-below" href="{genUrl controller='switch' action='list' infra=$row.id}"
        title="View switches in this infrastructure"><i class="icon-folder-open"></i></a>
    <a class="btn btn-mini have-tooltip-below" href="{genUrl controller='vlan' action='private' infra=$row.id}"
        title="View private VLANs in this infrastructure"><i class="icon-lock"></i></a>
    <a class="btn btn-mini have-tooltip-below" href="{genUrl controller=$controller action='view' id=$row.id}" title="Preview"><i class="icon-eye-open"></i></a>
    <a class="btn btn-mini have-tooltip-below" href="{genUrl controller=$controller action='edit' id=$row.id}" title="Edit"><i class="icon-pencil"></i></a>
    <a class="btn btn-mini have-tooltip-below" id='list-delete-{$row.id}' href="{genUrl controller=$controller action='delete' id=$row.id}" title="Delete"><i class="icon-trash"></i></a>
</div>
