
{if not $multiIXP}
<br /><br />
<div class="row-fluid">
    <div class="well">
        There is a database object representing your IXP. When running in single-IXP mode, as you are, the options to
        manage IXPs are hidden. However, there are points in the various installation and configuration documentation
        that require you to edit it. You can do that
        <a href="{genUrl controller='ixp' action='edit' id=1}">by clicking here</a>.
    </div>
</div>

{/if}
