
<form class="form-horizontal" enctype="application/x-www-form-urlencoded"
        accept-charset="UTF-8" method="post" horizontal="1"
        action="{genUrl controller="virtual-interface" action="add-wizard"}"
>

<div class="row-fluid">
    <div class="span4">

        <fieldset>
            <legend>General Interface Settings</legend>

            {$element->custid}
            {$element->vlanid}
            {$element->trunk}
            {$element->ipv4enabled}
            {$element->ipv6enabled}

        </fieldset>

    </div>
    <div class="span4">

        <fieldset>
            <legend>Physical Interface Settings</legend>
            {if $element->fanout}
                <div id="fanoutbox" class="hide">
                    {$element->fanout}
                </div>
            {/if}
            {$element->switchid}
            {$element->switchportid}
            {$element->status}
            {$element->speed}
            {$element->duplex}

        </fieldset>

    </div>

    <div class="span4">

        <fieldset>
            <legend>General VLAN Settings</legend>

            {$element->maxbgpprefix}
            {$element->irrdbfilter}
            {$element->mcastenabled}
            {$element->rsclient}
            {if $as112UiActive}
                {$element->as112client}
            {/if}

        </fieldset>

    </div>
</div>

<div class="row-fluid">

    <div class="span4">
        <div id="ipv4details" class="hide">
            {$element->ipv4DisplayGroup}
        </div>
    </div>

    <div class="span4">
        <div id="ipv6details" class="hide">
            {$element->ipv6DisplayGroup}
        </div>
    </div>

    <div class="span4">
         <div id="fanoutdetails" class="hide">
            {$element->fanoutDisplayGroup}
        </div>
    </div>

</div>


{$element->preselectIPv4Address}
{$element->preselectIPv6Address}
{$element->preselectVlanInterface}
{$element->preselectSwitchPort}
{$element->preselectPhysicalInterface}

<div class="form-actions">
    {$element->cancel}
    {$element->submit}
</div>


</form>
