
<form class="form-horizontal" enctype="application/x-www-form-urlencoded"
        accept-charset="UTF-8" method="post"
        >
            
<div class="row-fluid">

    <div class="span6">
    
        <fieldset>
            <legend>Virtual Interface Details</legend>
            
            {$element->custid}
            {$element->trunk}
            {if isset( $type ) && $type }
                <div class="control-group">
                    <label class="control-label">Type</label>
                    <div class="controls">
                        <span class="label {if $type == 1}label-success{else if $type == 6}label-inverse{/if}">{$ptypes[$type]|strtoupper}</span>
                        {if count( $physInts )}
                            {foreach $physInts as $int}
                                    {if $type == 1 && $int->getFanoutPhysicalInterface() }
                                        <span style="margin-left: 15px;">
                                            <a href="{genUrl controller=$controller action=$action id=$int->getFanoutPhysicalInterface()->getVirtualInterface()->getId()}">
                                                See {$ptypes[6]|strtolower} port
                                            </a>
                                        </span>
                                    {/if}
                                    {if $type == 6 && $int->getPeeringPhysicalInterface() }
                                        <span style="margin-left: 15px;">
                                            <a href="{genUrl controller=$controller action=$action id=$int->getPeeringPhysicalInterface()->getVirtualInterface()->getId()}">
                                                See {$ptypes[1]|strtolower} port
                                            </a>
                                        </span>
                                    {/if}
                            {/foreach}
                     
                        {/if}
                    </div>
                </div>
            {/if}
            
        </fieldset>
        
    </div>

    <div class="span6">
    
        <fieldset>
            <legend>&nbsp;</legend>
            
            <div id="advanced-options" class="hide">
            
                {$element->name}
                {$element->description}
                {$element->channelgroup}
                {$element->mtu}
                
            </div>
            
        </fieldset>
        
    </div>

    
</div>
        


<div class="form-actions">
    <input type="submit" name="commit" id="commit" value="{if $isEdit}Save Changes{else}Add{/if}" class="btn btn-primary">
    {if isset( $cust )}
        <a class="btn btn-success" href="{genUrl controller='customer' action='overview' tab='ports' id=$cust->getId()}">Return to Customer Overview</a>
    {else}
        <a class="btn btn-success" href="{genUrl controller='virtual-interface' action='add-wizard'}">Wizard Add</a>
        <a class="btn" href="{genUrl controller="virtual-interface" action="list"}">Return</a>
    {/if}

    <button class="btn" id="btn-advanced-options">Advanced Options</button>
</div>

    
</form>


<script type="text/javascript">

$(document).ready( function(){

	$( '#btn-advanced-options' ).on( 'click', function( event ){

		if( $( '#btn-advanced-options' ).hasClass( 'active' ) )
		    $( '#advanced-options' ).slideUp();
		else
			$( '#advanced-options' ).slideDown();
		
		$( '#btn-advanced-options' ).button( 'toggle' );
		return false;
	});
	
});

</script>

