
<form class="form-horizontal" enctype="application/x-www-form-urlencoded"
        accept-charset="UTF-8" method="post"
        >
            
<div class="row-fluid">

    <div class="span6">
    
        <fieldset>
            <legend>Virtual Interface Details</legend>
            
            {$element->custid}
            {$element->trunk}
            
        </fieldset>
        
    </div>

    <div class="span6">
    
        <fieldset>
            <legend>&nbsp;</legend>
            
            <div id="advanced-options" class="hide">
            
                {$element->name}
                {$element->description}
                {$element->channelgroup}
                {$element->mtu}
                
            </div>
            
        </fieldset>
        
    </div>

    
</div>
        


<div class="form-actions">
    <input type="submit" name="commit" id="commit" value="{if $isEdit}Save Changes{else}Add{/if}" class="btn btn-primary">
    {if isset( $cust )}
        <a class="btn btn-success" href="{genUrl controller='customer' action='overview' tab='ports' id=$cust->getId()}">Return to Customer Overview</a>
    {else}
        <a class="btn btn-success" href="{genUrl controller='virtual-interface' action='add-wizard'}">Wizard Add</a>
        <a class="btn" href="{genUrl controller="virtual-interface" action="list"}">Return</a>
    {/if}

    <button class="btn" id="btn-advanced-options">Advanced Options</button>
</div>

    
</form>


<script type="text/javascript">

$(document).ready( function(){

	$( '#btn-advanced-options' ).on( 'click', function( event ){

		if( $( '#btn-advanced-options' ).hasClass( 'active' ) )
		    $( '#advanced-options' ).slideUp();
		else
			$( '#advanced-options' ).slideDown();
		
		$( '#btn-advanced-options' ).button( 'toggle' );
		return false;
	});
	
});

</script>

