#
# Nagios configuration to check Bird daemons via the Bird's Eye API
#
# Generated by IXP Manager on <?= date('Y-m-d H:i:s') ?>
#
#
<?php $hosts = []; ?>

define command{
        command_name    check_birdseye_daemon
        command_line    /usr/local/nagios-plugins-other/nagios-check-birdseye.php -a $ARG1$
}

<?php foreach( $t->map as $n => $d ): ?>

define host     {
        use                     generic-host
        host_name               bird-<?= $n . "\n" ?>
        alias                   <?= $d['name'] . "\n" ?>
        address                 <?= $d['mgmt_ip'] . "\n" ?>
}

    <?php $hosts[] = "bird-{$n}"; ?>

<?php endforeach; ?>

define hostgroup {
    hostgroup_name          bird-daemons
    alias                   Individual Bird Daemons
    members                 <?= implode( ',', $hosts ) . "\n" ?>
}

<?php foreach( $t->map as $n => $d ): ?>

define service     {
        use                     inex-core-service
        host_name               bird-<?= $n . "\n" ?>
        service_description     Bird BGP Service
        check_command           check_birdseye_daemon!<?= $d['api'] . "\n" ?>
}

<?php endforeach; ?>



### END ###
