<?php

namespace Proxies\__CG__\Entities;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class ApiKey extends \Entities\ApiKey implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    /** @private */
    public function __load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;

            if (method_exists($this, "__wakeup")) {
                // call this after __isInitialized__to avoid infinite recursion
                // but before loading to emulate what ClassMetadata::newInstance()
                // provides.
                $this->__wakeup();
            }

            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister, $this->_identifier);
        }
    }

    /** @private */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    
    public function setApiKey($apiKey)
    {
        $this->__load();
        return parent::setApiKey($apiKey);
    }

    public function getApiKey()
    {
        $this->__load();
        return parent::getApiKey();
    }

    public function setExpires($expires)
    {
        $this->__load();
        return parent::setExpires($expires);
    }

    public function getExpires()
    {
        $this->__load();
        return parent::getExpires();
    }

    public function setAllowedIPs($allowedIPs)
    {
        $this->__load();
        return parent::setAllowedIPs($allowedIPs);
    }

    public function getAllowedIPs()
    {
        $this->__load();
        return parent::getAllowedIPs();
    }

    public function setCreated($created)
    {
        $this->__load();
        return parent::setCreated($created);
    }

    public function getCreated()
    {
        $this->__load();
        return parent::getCreated();
    }

    public function setLastseenAt($lastseenAt)
    {
        $this->__load();
        return parent::setLastseenAt($lastseenAt);
    }

    public function getLastseenAt()
    {
        $this->__load();
        return parent::getLastseenAt();
    }

    public function setLastseenFrom($lastseenFrom)
    {
        $this->__load();
        return parent::setLastseenFrom($lastseenFrom);
    }

    public function getLastseenFrom()
    {
        $this->__load();
        return parent::getLastseenFrom();
    }

    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return $this->_identifier["id"];
        }
        $this->__load();
        return parent::getId();
    }

    public function setUser(\Entities\User $user)
    {
        $this->__load();
        return parent::setUser($user);
    }

    public function getUser()
    {
        $this->__load();
        return parent::getUser();
    }


    public function __sleep()
    {
        return array('__isInitialized__', 'apiKey', 'expires', 'allowedIPs', 'created', 'lastseenAt', 'lastseenFrom', 'id', 'User');
    }

    public function __clone()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            $class = $this->_entityPersister->getClassMetadata();
            $original = $this->_entityPersister->load($this->_identifier);
            if ($original === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            foreach ($class->reflFields as $field => $reflProperty) {
                $reflProperty->setValue($this, $reflProperty->getValue($original));
            }
            unset($this->_entityPersister, $this->_identifier);
        }
        
    }
}