{tmplinclude file="header.phtml"}

<ul class="breadcrumb">
    <li>
        <a href="{genUrl}">Home</a> <span class="divider">/</span>
    </li>
    <li>
        <a href="{genUrl controller="customer" action="list"}">Customers</a> <span class="divider">/</span>
    </li>
    <li class="active">
        League Table ({foreach from=$categories key=cname item=cvalue}{if $category eq $cvalue}{$cname}{/if}{/foreach})
    </li>
</ul>

<div>

{OSS_Message}

<p>
<form action="{genUrl controller="statistics" action="league-table"}" method="post" class="form-horizontal">
<table>
<tr>
    {if $multiIXP}
        <td valign="middle"><strong>IXP:</strong></td>
        <td>
            &nbsp;
            <select name="ixp" style="width: 100px;" class="chzn-select" onchange="this.form.submit();">
                {foreach $ixps as $i}
                    <option value="{$i->getId()}" {if $ixp->getId() eq $i->getId()}selected="selected"{/if}>{$i->getShortname()}</option>
                {/foreach}
            </select>
        </td>
        <td width="20"></td>
    {/if}
    <td valign="middle"><strong>Metric:</strong></td>
    <td valign="middle">
        <select class="chzn-select" name="metric">
            {foreach from=$metrics key=cname item=cvalue}
                <option value="{$cvalue}" {if $metric eq $cvalue}selected{/if}>{$cname}</option>
            {/foreach}
        </select>
    </td>
    <td width="20"></td>
    <td valign="middle"><strong>Statistics Type:</strong></td>
    <td>
        <select class="chzn-select" name="category">
            {foreach from=$categories key=cname item=cvalue}
                <option value="{$cvalue}" {if $category eq $cvalue}selected{/if}>{$cname}</option>
            {/foreach}
        </select>
    </td>
    <td width="20"></td>
    <td valign="middle"><strong>Day:</strong></td>
    <td valign="middle"><input type="text" name="day" value="{$day->format( 'Y-m-d' )}" size="10" maxlength="10" /></td>
    <td width="20"></td>
    <td>
        <input type="submit" name="submit" class="btn" value="Submit" />
    </td>
</tr>
</table>
</form>
</p>

<table id="ixpDataTable" class="table table-striped table-bordered" cellspacing="0" cellpadding="0" border="0">

<thead>
    <tr>
        <th class="ui-state-default" ></th>
        <th class="ui-state-default" ></th>
        <th class="ui-state-default" colspan="3">Day</th>
        <th class="ui-state-default" colspan="3">Week</th>
        <th class="ui-state-default" colspan="3">Month</th>
        <th class="ui-state-default" colspan="3">Year</th>
    </tr>
    <tr>
        <th></th>
        <th>Member</th>
        <th>In</th>
        <th>Out</th>
        <th>Total</th>
        <th>In</th>
        <th>Out</th>
        <th>Total</th>
        <th>In</th>
        <th>Out</th>
        <th>Total</th>
        <th>In</th>
        <th>Out</th>
        <th>Total</th>
    </tr>
</thead>
<tbody>

{foreach from=$trafficDaily item=td}

	<tr>
        <td>{$td.Customer.shortname}</td>
        <td>{$td.Customer.name}</td>
        {if $metric eq 'max'}
            <td align="right">{$td.day_max_in}</td>
            <td align="right">{$td.day_max_out}</td>
            <td align="right">{$td.day_max_in+$td.day_max_out}</td>
            <td align="right">{$td.week_max_in}</td>
            <td align="right">{$td.week_max_out}</td>
            <td align="right">{$td.week_max_in+$td.week_max_out}</td>
            <td align="right">{$td.month_max_in}</td>
            <td align="right">{$td.month_max_out}</td>
            <td align="right">{$td.month_max_in+$td.month_max_out}</td>
            <td align="right">{$td.year_max_in}</td>
            <td align="right">{$td.year_max_out}</td>
            <td align="right">{$td.year_max_in+$td.year_max_out}</td>
        {elseif $metric eq 'average'}
            <td align="right">{$td.day_avg_in}</td>
            <td align="right">{$td.day_avg_out}</td>
            <td align="right">{$td.day_avg_in+$td.day_avg_out}</td>
            <td align="right">{$td.week_avg_in}</td>
            <td align="right">{$td.week_avg_out}</td>
            <td align="right">{$td.week_avg_in+$td.week_avg_out}</td>
            <td align="right">{$td.month_avg_in}</td>
            <td align="right">{$td.month_avg_out}</td>
            <td align="right">{$td.month_avg_in+$td.month_avg_out}</td>
            <td align="right">{$td.year_avg_in}</td>
            <td align="right">{$td.year_avg_out}</td>
            <td align="right">{$td.year_avg_in+$td.year_avg_out}</td>
        {else}
            <td align="right">{$td.day_tot_in}</td>
            <td align="right">{$td.day_tot_out}</td>
            <td align="right">{$td.day_tot_in+$td.day_tot_out}</td>
            <td align="right">{$td.week_tot_in}</td>
            <td align="right">{$td.week_tot_out}</td>
            <td align="right">{$td.week_tot_in+$td.week_tot_out}</td>
            <td align="right">{$td.month_tot_in}</td>
            <td align="right">{$td.month_tot_out}</td>
            <td align="right">{$td.month_tot_in+$td.month_tot_out}</td>
            <td align="right">{$td.year_tot_in}</td>
            <td align="right">{$td.year_tot_out}</td>
            <td align="right">{$td.year_tot_in+$td.year_tot_out}</td>
        {/if}
	</tr>

{/foreach}

</tbody>
</table>


</div>

{if $metric eq 'max'}
    {assign var='scalefn' value='myScale'}
{elseif $metric eq 'average'}
    {assign var='scalefn' value='myScale'}
{else}
    {assign var='scalefn' value='myScaleTotal'}
{/if}


<script>

//Define a custom format function for scale and type
var myScale = function( data )
{
	oData = data['aData'][data['iDataColumn']];

    switch( "{$category}" )
    {
        case 'bytes':
            var strFormat = new Array( "Bytes", "KBytes", "MBytes", "GBytes", "TBytes" );
            // According to http://oss.oetiker.ch/mrtg/doc/mrtg-logfile.en.html, data is stored in bytes
            // oData = oData / 8.0;
            break;
        case 'errs':
        case 'discs':
        case 'pkts':
            var strFormat = new Array( "pps", "Kpps", "Mpps", "Gpps", "Tpps" );
            break;
        default:
            // According to http://oss.oetiker.ch/mrtg/doc/mrtg-logfile.en.html, data is stored in bytes
            oData = oData * 8.0;
            var strFormat = new Array( "bps", "Kbps", "Mbps", "Gbps", "Tbps" );
            break;
    }

    var retString = "";

    for( var i = 0; i < strFormat.length; i++ )
    {
        if( ( oData / 1000 < 1 ) || ( strFormat.length == i + 1 ) )
        {
            retString =  number_format( oData, 0 ) + '&nbsp;' + strFormat[i];
            break;
        }
        else
        {
            oData = oData / 1000;
        }
    }

    return retString;
};

var myScaleTotal = function( data )
{
	oData = data['aData'][data['iDataColumn']];

	switch( "{$category}" )
    {
        case 'errs':
        case 'discs':
        case 'pkts':
            var strFormat = new Array( "p", "Kp", "Mp", "Gp", "Tp" );
            break;
        default:
            var strFormat = new Array( "B", "KB", "MB", "GB", "TB" );
            // According to http://oss.oetiker.ch/mrtg/doc/mrtg-logfile.en.html, data is stored in bytes
            // oData /= 8;
            break;
    }

    var retString = "";

    for( var i = 0; i < strFormat.length; i++ )
    {
        if( ( oData / 1000 < 1 ) || ( strFormat.length == i + 1 ) )
        {
            retString =  number_format( oData, 0 ) + strFormat[i];
            break;
        }
        else
        {
            oData = oData / 1000;
        }
    }

    return retString;
};

$(document).ready(function() {

    oTable = $('#ixpDataTable').dataTable({

        "sDom": "<'row-fluid'<'span6'l><'span6'f>r>t<'row-fluid'<'span6'i><'span6'p>>",
        "aaSorting": [[ 6, 'desc' ]],
		"sPaginationType": "bootstrap",
		"iDisplayLength": 100,
		"aoColumnDefs": [
            { "bVisible": false, "aTargets": [ 0 ] },
        	{ "fnRender": {$scalefn}, "aTargets": [ 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13 ] },
        	{ "sType": "numeric", "aTargets": [ 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13 ] },
        	{ "bUseRendered": false, "aTargets": [ 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13 ] }
        ],
        "fnRowCallback": function( nRow, aData, iDisplayIndex ) {
                $( nRow ).click( function(){
    	            $.fn.colorbox({
                        open: true,
                        iframe: true,
                        href: '{genUrl
                                   controller='dashboard'
                                   action='statistics-drilldown'
                                   monitorindex='aggregate'
                                   mini='1'
                                   category=$category
                               }/shortname/' + aData[0],
                        transition: 'elastic',
                        innerWidth: '650px',
                        height: '80%'
                    });
                });
                 
      			return nRow;
	  		}
	}).show();

});

</script>

{tmplinclude file="footer.phtml"}