{tmplinclude file="header.phtml"}


<ul class="breadcrumb">
    <li>
        <a href="{genUrl}">Home</a> <span class="divider">/</span>
    </li>
    <li>
        Statistics <span class="divider">/</span>
    </li>
    <li class="active">
        List
    </li>
    {if $multiIXP}
        <li class="pull-right"  style="margin-top: -6px;">
            <div class="btn-toolbar" style="display: inline;">    
                <div class="btn-group">
                    <a class="btn btn-mini dropdown-toggle" data-toggle="dropdown" href="#">
                        {if isset( $ixp ) }{$ixp->getName()}{else}Limit to IXP...{/if}
                        <span class="caret"></span>
                    </a>
                    <ul class="dropdown-menu pull-right">
                        {foreach $ixpNames as $xid => $xname}
                            <li> <a href="{genUrl controller=$controller action=$action ixp=$xid}">{$xname}</a> </li>
                        {/foreach}
                    </ul>
                </div>
            </div>
        </li>
    {/if}
</ul>


{OSS_Message}

<div class="row-fluid">

{assign var='count' value=0}

    <div class="span3">

        <ul>
        
        {foreach $custs as $cust}

            {if count( $custs ) > 12 and $count >= count( $custs )/4}
            
                </ul>
                </div>
                <div class="span3">
                {assign var='count' value=0}
            {/if}
            
        	<li>
        		<a href="{genUrl controller="dashboard" action="statistics" shortname=$cust.shortname}">
        			{$cust.name}
        		</a>
        	</li>

        	{assign var='count' value=$count+1}
        	
    	{/foreach}

    	</ul>

	</div>
</div>

{tmplinclude file="footer.phtml"}
