<!DOCTYPE html>
<html lang="en">
<head>
    <base href="{genUrl}">
    <meta http-equiv="Content-Type" content="text/html; charset="utf8" />
    {tmplinclude file="header-css.phtml"}
</head>

<body>

<center>
<h3>IXP Interface Statistics :: {$cust->getFormattedName()} :: {foreach from=$categories key=cname item=cvalue}{if $category eq $cvalue}{$cname}{/if}{/foreach}</h3>

{foreach from=$periods key=pname item=pvalue}

<h3>{$pname} Graph</h3>

<p align="center">
    {genMrtgGraphBox
            shortname=$cust->getShortname()
            category=$category
            monitorindex=$monitorindex
            period=$pvalue
            values=$stats.$pvalue
    }
</p>


{/foreach}

</center>

</body>
</html>
