{tmplinclude file="header.phtml" pageTitle="IXP Manager :: Member Dashboard"}

{if $user->getPrivs() eq 3}
    <ul class="breadcrumb">
        <li>
            <a href="{genUrl}">Home</a> <span class="divider">/</span>
        </li>
        <li>
            <a href="{genUrl controller='customer' action='list'}">Customers</a> <span class="divider">/</span>
        </li>
        <li>
            <a href="{genUrl controller='customer' action='overview' id=$cust->getId()}">{$cust->getName()}</a> <span class="divider">/</span>
        </li>
        <li class="active">
            Statistics
            ({foreach from=$categories key=cname item=cvalue}{if $category eq $cvalue}{$cname}{/if}{/foreach})
        </li>
    </ul>
    <div>
{else}
    <div class="page-content">
        <div class="page-header">
            <h1>
                IXP Interface Statistics
                
                {if $multiIXP}
                    @ {$ixp->getShortname()}
                {else}
                    :: {$cust->getName()}
                {/if}

                ({foreach from=$categories key=cname item=cvalue}{if $category eq $cvalue}{$cname}{/if}{/foreach})
            </h1>
        </div>
{/if}


{OSS_Message}

<div class="row-fluid">

    <div class="span6">

        {if $switchname eq ''}
            <h3>
                Aggregate Statistics for
                
                {if $multiIXP}
                    {$ixp->getShortname()}
                {else}
                    All Peering Ports
                {/if}
            </h3>
        {else}
            <h3>
                Port: {$switchname} / {$portname}
                
                {if $resellerMode and $cust->isReseller()}
                    <br /><small>
                    {if $pi->getSwitchPort()->getType() eq SWITCHPORT::TYPE_PEERING}
                        Peering Port
                    {elseif $pi->getSwitchPort()->getType() eq SWITCHPORT::TYPE_FANOUT}
                        Fanout Port for <a href="{genUrl controller='customer' action='overview' id=$pi->getRelatedInterface()->getVirtualInterface()->getCustomer()->getId()}">
                            {$pi->getRelatedInterface()->getVirtualInterface()->getCustomer()->getAbbreviatedName()}
                        </a>
                    {elseif $pi->getSwitchPort()->getType() eq SWITCHPORT::TYPE_RESELLER}
                        Reseller Uplink Port
                    {/if}
                    </small>
                {/if}
            </h3>
        {/if}

    </div>
    <div class="span6">
    
        <form action="{genUrl controller="statistics" action="member-drilldown" ixp=$ixp->getId() shortname=$cust->getShortname() monitorindex=$monitorindex}" method="post" class="form-horizontal">
            
            <strong>Graph Type:&nbsp;&nbsp;&nbsp;</strong>

            <select name="category" onchange="this.form.submit();" class="chzn-select">
                {foreach from=$categories key=cname item=cvalue}
                    <option value="{$cvalue}" {if $category eq $cvalue}selected{/if}>{$cname}</option>
                {/foreach}
            </select>
            &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
            <a class="btn btn-primary" href="{genUrl controller="statistics" action="member" ixp=$ixp->getId()}{if $user->getPrivs() eq 3}/shortname/{$cust->getShortname()}{/if}">
                Statistics Overview
            </a>
            {if $ixp->getSmokeping() and $switchname neq ''}
                {$canPing = 0}
                {foreach $pi->getVirtualInterface()->getVlanInterfaces() as $vli}
                    {if ( $vli->getIpv4enabled() and $vli->getIpv4canping() ) or ( $vli->getIpv6enabled() and $vli->getIpv6canping() )}
                        {$canPing = 1}
                        {break}
                    {/if}
                {/foreach}
                {if $canPing}
                    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                    <a class="btn btn-primary" href="{genUrl controller="smokeping" action="member-drilldown" ixp=$ixp->getId() vi=$pi->getVirtualInterface()->getId()}{if $user->getPrivs() eq 3}{/if}">
                        Smokeping
                    </a>
                {/if}
            {/if}
        </form>

    </div>
</div>
    
<div class="row-fluid">

{assign var='count' value=0}

    {foreach from=$periods key=pname item=pvalue}

    <div class="span6">

        <div class="well">

            <h3>{$pname} Graph</h3>

            <p>
                {genMrtgGraphBox
                        ixp=$ixp->getId()
                        shortname=$cust->getShortname()
                        category=$category
                        monitorindex=$monitorindex
                        period=$pvalue
                        values=$stats.$pvalue
                }
            </p>

        </div>
    </div>

    {assign var='count' value=$count+1}

    {if $count%2 eq 0}
        </div><br /><div class="row-fluid">
    {/if}


    {/foreach}

{if $count%2 neq 0}
    <div class="span3"></div>
{/if}

</div>
</div>

{tmplinclude file="footer.phtml"}

