{tmplinclude file="header.phtml" pageTitle="IXP Manager :: Member Dashboard"}

{if $user->getPrivs() eq 3}
    <ul class="breadcrumb">
        <li>
            <a href="{genUrl}">Home</a> <span class="divider">/</span>
        </li>
        <li>
            <a href="{genUrl controller='customer' action='list'}">Customers</a> <span class="divider">/</span>
        </li>
        <li>
             <a href="{genUrl controller='customer' action='overview' id=$cust->getId()}">{$cust->getName()}</a> <span class="divider">/</span>
        </li>
        <li class="active">
            Statistics
            (
             {foreach from=$categories key=cname item=cvalue}{if $category eq $cvalue}{$cname}{/if}{/foreach}
             {if isset( $period )}
                /
                 {foreach from=$periods key=cname item=cvalue}{if $period eq $cvalue}{$cname}{/if}{/foreach}
             {/if}
            )
        </li>
    </ul>
    
    <div>
{else}
    <div class="page-content">
        <div class="page-header">
            <h1>IXP Interface Statistics :: {$cust->getName()}</h1>
        </div>
{/if}

{OSS_Message}

<div class="row-fluid">

    <div class="span6">

        <div class="well">
            <h3>Aggregate Traffic Statistics</h3>

            <p>
                <br />
                <a href="{genUrl controller='statistics' action='member-drilldown' monitorindex='aggregate' category=$category shortname=$cust->getShortname()}">
                    {genMrtgImgUrlTag shortname=$cust->getShortname() category=$category monitorindex='aggregate'}
                </a>
            </p>
        </div>

    </div>

    <div class="span6">

        <p>
        <br /><br /><br />
        Click on a graphs for longer term statistics or change the graph time in the drop down below.
        </p>

        <form action="{genUrl controller="statistics" action="member"}" method="post" class="well form-inline">
            <input type="hidden" name="shortname" value="{$cust->getShortname()}" />
            <strong>Graph Type:</strong>&nbsp;&nbsp;&nbsp;&nbsp;
            <select name="category" onchange="this.form.submit();" class="chzn-select">
                {foreach from=$categories key=cname item=cvalue}
                    <option value="{$cvalue}" {if $category eq $cvalue}selected{/if}>{$cname}</option>
                {/foreach}
            </select>
        </form>

    </div>

</div>


<div class="row-fluid">

{assign var='count' value=0}

{foreach $cust->getVirtualInterfaces() as $vi}

    {foreach $vi->getPhysicalInterfaces() as $pi}

        <div class="span6">

            <div class="well">

                <h4>
                        {$pi->getSwitchPort()->getSwitcher()->getCabinet()->getLocation()->getName()}
                        / {$pi->getSwitchPort()->getSwitcher()->getName()}
                        / {$pi->getSwitchPort()->getName()} ({$pi->getSpeed()}Mbps)
                </h4>


                <p>
                    <br />
                    <a href="{genUrl controller='statistics' action='member-drilldown' monitorindex=$pi->getMonitorindex() category=$category shortname=$cust->getShortname()}">
                        {genMrtgImgUrlTag shortname=$cust->getShortname() category=$category monitorindex=$pi->getMonitorindex()}
                    </a>
                </p>

            </div>

        </div>

        {assign var='count' value=$count+1}

        {if $count%2 eq 0}
            </div><br /><div class="row-fluid">
        {/if}

    {/foreach}

{/foreach}

{if $count%2 neq 0}
    <div class="span6"></div>
{/if}

</div>
</div>

{tmplinclude file="footer.phtml"}

