{tmplinclude file="header.phtml"}

<ul class="breadcrumb">
    <li>
        <a href="{genUrl}">Home</a> <span class="divider">/</span>
    </li>
    <li>
        Statistics <span class="divider">/</span>
    </li>
    <li class="active">
        Graphs
        (
         {foreach from=$categories key=cname item=cvalue}{if $category eq $cvalue}{$cname}{/if}{/foreach}
        /
         {foreach from=$periods key=cname item=cvalue}{if $period eq $cvalue}{$cname}{/if}{/foreach}
        )
    </li>
    <li class="pull-right"  style="margin-top: -6px;">
        <div class="btn-toolbar" style="display: inline;">
            {if $multiIXP}
                <div class="btn-group">
                    <a class="btn btn-mini dropdown-toggle" data-toggle="dropdown" href="#">
                        {if isset( $ixp ) }{$ixp->getName()}{else}Limit to IXP...{/if}
                        <span class="caret"></span>
                    </a>
                    <ul class="dropdown-menu pull-right">
                        {foreach $ixpNames as $xid => $xname}
                            <li> <a href="{genUrl controller=$controller action=$action ixp=$xid}">{$xname}</a> </li>
                        {/foreach}
                    </ul>
                </div>
            {/if}

            <div class="btn-group" id="vlan-btn-group">
                <a class="btn btn-mini dropdown-toggle" data-toggle="dropdown" id="vlan-dd">
                    <span id="vlan-dd-text">
                        {if $infra == 'aggregate'}
                            Aggregate Traffic
                        {else}
                            {$infras.$infra}
                        {/if}
                    </span>
                    <span class="caret"></span>
                </a>
                <ul id="vlan-dd-ul" class="dropdown-menu pull-right">
                    <li> <a id="vlan-aggregate" href="{genUrl controller='statistics' action='members'}">Aggregate Traffic</a> </li>
                    <li class="divider"></li>
                    {foreach $infras as $iid => $iname}
                        <li> <a id="vlan-{$iid}" href="{genUrl controller='statistics' action='members' infra=$iid}">{$iname}</a> </li>
                    {/foreach}
                </ul>
            </div>            
        </div>
    </li>

</ul>

{OSS_Message}

<div class="row-fluid">
    <div class="span12">
        <form action="{genUrl controller="statistics" action="members" infra=$infra}{if isset( $ixp )}/ixp/{$ixp->getId()}{/if}" method="post" class="form-horizontal">
            <strong>Graph Type:</strong>
            <select name="category" class="chzn-select" onchange="this.form.submit();">
                {foreach from=$categories key=cname item=cvalue}
                    <option value="{$cvalue}" {if $category eq $cvalue}selected{/if}>{$cname}</option>
                {/foreach}
            </select>
            <strong>Period:</strong>
            <select name="period" class="chzn-select" onchange="this.form.submit();">
                {foreach from=$periods key=cname item=cvalue}
                    <option value="{$cvalue}" {if $period eq $cvalue}selected{/if}>{$cname}</option>
                {/foreach}
            </select>
        </form>
    </div>
</div>


<div class="row-fluid">

{assign var='count' value=0}
{foreach from=$custs item=cust}

    {* identify if this customer has an interface on the selected peering LAN *}

    {$monindexes = []}
    {$portdetails = []}
    {if $infra eq 'aggregate'}
    
        {$monindexes[] = 'aggregate'}
        
    {else}
        
        {* does this customer have interfaces on the requested LAN *}
        
        {foreach $cust->getVirtualInterfaces() as $vi}

            {foreach $vi->getPhysicalInterfaces() as $pi}
            
                {if $pi->getSwitchPort()->getSwitcher()->getInfrastructure()->getId() == $infra}
                
                    {$monindexes[] = $pi->getMonitorindex()}
                    {$mi = $pi->getMonitorindex()}
                    
                    {$portdetails.$mi.switch = $pi->getSwitchPort()->getSwitcher()->getName()}
                    {$portdetails.$mi.switchport = $pi->getSwitchPort()->getName()}
                    
                {/if}
            
            {/foreach}
        
        
        {/foreach}
        
    {/if}

    {foreach $monindexes as $monindex}
    
        <div class="span3">
    
            <div class="well">
                <h4 style="vertical-align: middle">
                    {$cust->getName()}
                    {if ( isset( $options.sflow.enabled ) and $options.sflow.enabled ) and ( $category eq 'bits' or $category eq 'pkts' )} 
                        <span class="btn btn-mini" style="float: right">
                            <a href="{genUrl controller="statistics" action="p2p" shortname=$cust->getShortname() category=$category period=$period}"><i class="icon-random"></i></a>
                        </span>
                    {/if}
                </h4>
                
                {if $infra neq 'aggregate'}
                    <h5>{$portdetails.$monindex.switch} / {$portdetails.$monindex.switchport}</h5>
                {/if}
    
                <p>
                    <br />
                    <a href="{genUrl controller="statistics" action="member" shortname=$cust->getShortname() monitorindex=aggregate category=$category}">
                        <img
                            src="{genMrtgImgUrl shortname=$cust->getShortname() category=$category period=$period monitorindex=$monindex}"
                            width="300"
                        />
                    </a>
                </p>
            </div>
    
        </div>
    
        {assign var='count' value=$count+1}
    
        {if $count%4 eq 0}
            </div><br /><div class="row-fluid">
        {/if}
        
    {/foreach}

{/foreach}

{if $count%4 neq 0}
    <div class="span3"></div>
    {assign var='count' value=$count+1}
    {if $count%4 neq 0}
        <div class="span3"></div>
        {assign var='count' value=$count+1}
        {if $count%4 neq 0}
            <div class="span3"></div>
            {assign var='count' value=$count+1}
        {/if}
    {/if}
{/if}

</div>


{tmplinclude file="footer.phtml"}