{tmplinclude file="header.phtml"}

<ul class="breadcrumb">
    <li>
        <a href="{genUrl}">Home</a> <span class="divider">/</span>
    </li>
    <li>
        Statistics <span class="divider">/</span>
    </li>
    <li class="active">
        Graphs
        (
         {foreach from=$categories key=cvalue item=cname}{if $category eq $cvalue}{$cname}{/if}{/foreach}
        /
         {foreach from=$periods key=pvalue item=pname}{if $period eq $pvalue}{$pname}{/if}{/foreach}
        )
    </li>
    <li class="pull-right"  style="margin-top: -6px;">
        <div class="btn-toolbar" style="display: inline;">
            {if $multiIXP}
                {include file='statistics/snippets/menu-ixp-dropdown.phtml'}
            {/if}

            {include file='statistics/snippets/menu-infra-dropdown.phtml'}
        </div>
    </li>

</ul>

{OSS_Message}

<div class="row-fluid">
    <div class="span12">
        <form action="{genUrl controller="statistics" action="members"}" method="post" class="form-horizontal">
{*
            {if $multiIXP}
                <strong>IXP:</strong>
                <select name="ixp" class="chzn-select" onchange="this.form.submit();">
                    {foreach $ixps as $i}
                        <option value="{$i->getId()}" {if $ixp->getId() eq $i->getId()}selected{/if}>{$i->getName()}</option>
                    {/foreach}
                </select>
            {else}
                <input type="hidden" name="ixp" value="{$ixp->getId()}" />
            {/if}

            <strong>Infrastructure:</strong>
            <select name="infra" class="chzn-select" onchange="this.form.submit();">
                <option value="aggregate" {if $infraid eq 'aggregate'}selected{/if}>Aggregate Traffic</option>
                {foreach $ixp->getInfrastructures() as $i}
                    <option value="{$i->getId()}" {if $infraid eq $i->getId()}selected{/if}>{$i->getName()}</option>
                {/foreach}
            </select>
*}

            <strong>Graph Type:</strong>
            <select name="category" class="chzn-select" onchange="this.form.submit();">
                {foreach from=$categories key=cvalue item=cname}
                    <option value="{$cvalue}" {if $category eq $cvalue}selected{/if}>{$cname}</option>
                {/foreach}
            </select>
            <strong>Period:</strong>
            <select name="period" class="chzn-select" onchange="this.form.submit();">
                {foreach from=$periods key=pvalue item=pname}
                    <option value="{$pvalue}" {if $period eq $pvalue}selected{/if}>{$pname}</option>
                {/foreach}
            </select>
        </form>
    </div>
</div>


<div class="row-fluid">

{assign var='count' value=0}
{foreach from=$graphs item=graph}

    <div class="span6">

        <div class="well">
            <h4 style="vertical-align: middle">
                {$graph->customer()->getFormattedName()}
                {if config('grapher.backends.sflow.enabled') and ( $category eq 'bits' or $category eq 'pkts' )}
                    <span class="btn btn-mini" style="float: right">
                        <a href="{genUrl controller="statistics" action="p2p" shortname=$graph->customer()->getShortname() category=$category period=$period}"><i class="icon-random"></i></a>
                    </span>
                {/if}
            </h4>

            <p>
                <br />
                {$graph->renderer()->boxLegacy()}
            </p>
        </div>

    </div>

    {assign var='count' value=$count+1}

    {if $count%2 eq 0}
        </div><br /><div class="row-fluid">
    {/if}

{/foreach}


{if $count%2 neq 0}
    <div class="span6"></div>
    {assign var='count' value=$count+1}
{/if}

</div>


{tmplinclude file="footer.phtml"}
