{tmplinclude file="header.phtml" pageTitle="IXP Manager :: Member Dashboard"}

{if $user->getPrivs() eq 3}
    <ul class="breadcrumb">
        <li>
            <a href="{genUrl}">Home</a> <span class="divider">/</span>
        </li>
        <li>
            <a href="{genUrl controller='customer' action='list'}">Customers</a> <span class="divider">/</span>
        </li>
        <li>
             <a href="{genUrl controller='customer' action='overview' id=$cust->getId()}">{$cust->getName()}</a> <span class="divider">/</span>
        </li>
        <li class="active">
            Statistics
            (
             {foreach from=$categories key=cname item=cvalue}{if $category eq $cvalue}{$cname}{/if}{/foreach}
             {if isset( $period )}
                /
                 {foreach from=$periods key=cname item=cvalue}{if $period eq $cvalue}{$cname}{/if}{/foreach}
             {/if}
            )
        </li>
    </ul>

    <div>
{else}
    <div class="page-content">
        <div class="page-header">
            <h1>
                IXP Interface Statistics
                {if $multiIXP}
                    @ {$ixp->getShortname()}
                {else}
                    :: {$cust->getName()}
                {/if}
            </h1>
        </div>
{/if}

{OSS_Message}

<div class="row-fluid">

    <div class="span6">

        <div class="well">
            <h3>
                {if $multiIXP}{$ixp->getShortname()} :: {/if} Aggregate Peering Traffic
                {if $resellerMode and $cust->isReseller()}
                    {* let's be explicit that this is peering traffic only *}
                    <small><em>(Peering ports only)</em></small>
                {/if}
            </h3>

            <p>
                <br />
                <a href="{genUrl controller='statistics' action='member-drilldown' ixp=$ixp->getId() monitorindex='aggregate' category=$category shortname=$cust->getShortname()}">
                    {genMrtgImgUrlTag ixp=$ixp->getId() shortname=$cust->getShortname() category=$category monitorindex='aggregate'}
                </a>
            </p>
        </div>

    </div>

    <div class="span6 well">

        <h3>
            {if $multiIXP}
                Graphs for {$ixp->getName()}
            {else}
                Graph Options
            {/if}

            {if isset( $options.sflow.enabled ) and $options.sflow.enabled}
                <a class="btn btn-primary pull-right" href="{genUrl controller="statistics" action="p2p" ixp=$ixp->getId() shortname=$cust->getShortname()}">
                    See Peer to Peer Graphs
                </a>
            {/if}
        </h3>

        <p>
            Click on a graph for longer term statistics (daily, weekly, monthly and yearly).
            Change the graph type in the drop down below.
        </p>

        <form action="{genUrl controller="statistics" action="member"}" method="post" class="form-inline">
            <input type="hidden" name="shortname" value="{$cust->getShortname()}" />

            {if $multiIXP}
                <strong>IXP:</strong>
                <select name="ixp" class="chzn-select span3" onchange="this.form.submit();">
                    {foreach $ixps as $i}
                        <option value="{$i->getId()}" {if $ixp->getId() eq $i->getId()}selected{/if}>{$i->getShortname()}</option>
                    {/foreach}
                </select>
            {else}
                <input type="hidden" name="ixp" value="{$ixp->getId()}" />
            {/if}

            <strong>Graph Type:</strong>&nbsp;&nbsp;&nbsp;&nbsp;
            <select name="category" onchange="this.form.submit();" class="chzn-select span3">
                {foreach from=$categories key=cname item=cvalue}
                    <option value="{$cvalue}" {if $category eq $cvalue}selected{/if}>{$cname}</option>
                {/foreach}
            </select>
        </form>
    </div>

</div>


<div class="row-fluid">

{assign var='count' value=0}

{foreach $cust->getVirtualInterfaces() as $vi}

    {* ensure we're looking at a graph on the correct IXP *}
    {$pi = $vi->getPhysicalInterfaces()}
    {$pi = $pi.0}
    {if $pi->getSwitchport()->getSwitcher()->getInfrastructure()->getIXP() neq $ixp }
        {continue}
    {/if}

    {if count( $vi->getPhysicalInterfaces() ) > 1}

        <div class="span6">

            <div class="well">

                <h4>
                    LAG on {$pi->getSwitchPort()->getSwitcher()->getCabinet()->getLocation()->getName()}
                        / {$pi->getSwitchPort()->getSwitcher()->getName()}
                    <small>
                        <br />
                        Ports:
                        {foreach $vi->getPhysicalInterfaces() as $pi}
                            {$pi->getSwitchPort()->getName()}
                        {/foreach}
                    </small>
                </h4>

                <p>
                    <br />
                    <a href="{genUrl controller='statistics' action='member-drilldown' ixp=$ixp->getId() monitorindex="lag-viid-`$vi->getId()`" category=$category shortname=$cust->getShortname()}">
                        {genMrtgImgUrlTag ixp=$ixp->getId() shortname=$cust->getShortname() category=$category monitorindex="lag-viid-`$vi->getId()`"}
                    </a>
                </p>

            </div>

        </div>

        {assign var='count' value=$count+1}

        {if $count%2 eq 0}
            </div><br /><div class="row-fluid">
        {/if}

    {/if}

    {foreach $vi->getPhysicalInterfaces() as $pi}

        <div class="span6">

            <div class="well">

                <h4>
                    {$pi->getSwitchPort()->getSwitcher()->getCabinet()->getLocation()->getName()}
                        / {$pi->getSwitchPort()->getSwitcher()->getName()}
                        / {$pi->getSwitchPort()->getName()} ({$pi->getSpeed()}Mbps)

                    {if $resellerMode and $cust->isReseller()}
                        <br /><small>
                        {if $pi->getSwitchPort()->getType() eq SWITCHPORT::TYPE_PEERING}
                            Peering Port
                        {elseif $pi->getSwitchPort()->getType() eq SWITCHPORT::TYPE_FANOUT}
                            Fanout Port for <a href="{genUrl controller='customer' action='overview' id=$pi->getRelatedInterface()->getVirtualInterface()->getCustomer()->getId()}">
                                {$pi->getRelatedInterface()->getVirtualInterface()->getCustomer()->getAbbreviatedName()}
                            </a>
                        {elseif $pi->getSwitchPort()->getType() eq SWITCHPORT::TYPE_RESELLER}
                            Reseller Uplink Port
                        {/if}
                        </small>
                    {/if}

                </h4>

                <p>
                    <br />
                    <a href="{genUrl controller='statistics' action='member-drilldown' ixp=$ixp->getId() monitorindex=$pi->getMonitorindex() category=$category shortname=$cust->getShortname()}">
                        {genMrtgImgUrlTag ixp=$ixp->getId() shortname=$cust->getShortname() category=$category monitorindex=$pi->getMonitorindex()}
                    </a>
                </p>

            </div>

        </div>

        {assign var='count' value=$count+1}

        {if $count%2 eq 0}
            </div><br /><div class="row-fluid">
        {/if}

    {/foreach}

{/foreach}

{if $count%2 neq 0}
    <div class="span6"></div>
{/if}

</div>
</div>

{tmplinclude file="footer.phtml"}
