{tmplinclude file="header.phtml"}

{if $user->getPrivs() eq USER::AUTH_SUPERUSER}
    <ul class="breadcrumb">
        <li>
            <a href="{genUrl}">Home</a> <span class="divider">/</span>
        </li>
        <li>
            <a href="{genUrl controller='statistics' action='members'}">Statistics</a> <span class="divider">/</span>
        </li>
        <li>
             <a href="{genUrl controller="customer" action="overview" id=$cust->getId()}">{$cust->getFormattedName()}</a> <span class="divider">/</span>
        </li>
        <li class="active">
            <a href="{genUrl controller="statistics" action="p2p" shortname=$cust->getShortname()}">Peer to Peer Statistics</a>
            with <a href="{genUrl controller="statistics" action="p2p" shortname=$dstVli->getVirtualInterface()->getCustomer()->getShortname()}">
                {$dstVli->getVirtualInterface()->getCustomer()->getFormattedName()}
            </a>
            (
             {foreach from=$categories key=cvalue item=cname}{if $category eq $cvalue}{$cname}{/if}{/foreach}
             {if isset( $period )}
                /
                 {foreach from=$periods key=pvalue item=pname}{if $period eq $cvalue}{$cname}{/if}{/foreach}
             {/if}
            )
        </li>
    </ul>
{else}
    <div class="page-content">
        <div class="page-header">
            <h1>IXP Peer to Peer Statistics :: {$cust->getFormattedName()} {if isset( $dcust ) and $dcust}&lt;=&gt; {$dcust.cname}{/if}</h1>
        </div>
{/if}

{OSS_Message}

<h3>
    {if isset( $dstVli ) and $dstVli}
        Traffic exchanged with: {$dstVli->getVirtualInterface()->getCustomer()->getFormattedName()}
    {/if}
    <div class="pull-right">
        <a href="{genUrl controller="statistics" action="p2p"}" class="btn btn-default">Return</a>
    </div>
</h3>

<p>
<form action="{genUrl controller="statistics" action="p2p"}{if $user->getPrivs() eq USER::AUTH_SUPERUSER}/shortname/{$cust->getShortname()}{/if}" method="post">
<table>
<tr>
    <td width="20"></td>
    <td valign="middle"><strong>LAN:</strong></td>
    <td>
        &nbsp;
        <select name="svli" style="width: 200px;">
            {foreach $srcVlis as $id => $vli}
                <option value="{$id}" {if $srcVli eq $vli}selected="selected"{/if}>
                    {$vli->getVlan()->getName()}
                </option>
            {/foreach}
        </select>
    </td>
    <td width="20"></td>
    <td valign="middle"><strong>Graph Type:</strong></td>
    <td>
        &nbsp;
        <select name="category" style="width: 100px;">
            {foreach from=$categories key=cvalue item=cname}
                {if $cname neq 'Errors' and $cname neq 'Discards'}
                    <option value="{$cvalue}" {if $category eq $cvalue}selected{/if}>{$cname}</option>
                {/if}
            {/foreach}
        </select>
    </td>
    <td width="20"></td>
    <td valign="middle"><strong>Protocol:</strong></td>
    <td>
        &nbsp;
        <select name="proto" style="width: 100px;">
            {foreach from=$protocols key=pvalue item=pname}
                <option value="{$pvalue}" {if $proto eq $pvalue}selected="selected"{/if}>{$pname}</option>
            {/foreach}
        </select>
    </td>
    <td width="20"></td>
    <td valign="middle">
        {if isset( $dstVli )}<input type="hidden" name="dvli" value="{$dstVli->getId()}" />{/if}
        <input class="btn" type="submit" value="Submit &raquo;" />
    </td>
    </tr>
</table>
</form>
</p>


{if isset( $dstVli ) and $dstVli}
    <div class="row-fluid">

    {assign var='count' value=0}
    {foreach from=$periods key=pvalue item=pname}

        <div class="span6">

            <div class="well">
                <h4 style="vertical-align: middle">
                    {$pname}
                </h4>

                <p>
                    <br />
                    <img
                        src="{$grapher->p2p( $srcVli, $dstVli )->setCategory($category)->setProtocol($proto)->setPeriod($pvalue)->setType('png')->url()}"
                        width="600"
                    />
                </p>
            </div>

        </div>

        {assign var='count' value=$count+1}

        {if $count%2 eq 0}
            </div><br /><div class="row-fluid">
        {/if}

    {/foreach}

    {if $count%2 neq 0}
        <div class="span6"></div>
        {assign var='count' value=$count+1}
    {/if}

    </div>

{else} {* customer has an interface for given infra and proto *}

    <div class="alert alert-info">
        <h4 class="alert-heading">Uh oh! You or your peer do not have any ports for the selected infrastructure and / or protocol.</h4>
        If you'd like to talk to us about enabling IPv6 or getting a port on the secondary infrastructure, please
        <a href="{genUrl controller="static" action="support"}">contact us</a>.
    </div>

{/if} {* customer has an interface for given infra and proto *}

{if $user->getPrivs() neq USER::AUTH_SUPERUSER}
</div>
{/if}

{tmplinclude file="footer.phtml"}
