{tmplinclude file="header.phtml"}

{if $user->getPrivs() eq USER::AUTH_SUPERUSER}
    <ul class="breadcrumb">
        <li>
            <a href="{genUrl}">Home</a> <span class="divider">/</span>
        </li>
        <li>
            <a href="{genUrl controller='statistics' action='members'}">Statistics</a> <span class="divider">/</span>
        </li>
        <li>
             <a href="{genUrl controller="customer" action="overview" id=$cust->getId()}">{$cust->getName()}</a> <span class="divider">/</span>
        </li>
        <li class="active">
            Peer to Peer Statistics
            (
             {foreach from=$categories key=cname item=cvalue}{if $category eq $cvalue}{$cname}{/if}{/foreach}
             {if isset( $period )}
                /
                 {foreach from=$periods key=cname item=cvalue}{if $period eq $cvalue}{$cname}{/if}{/foreach}
             {/if}
            )
        </li>
        <li class="pull-right"  style="margin-top: -6px;">
            <div class="btn-toolbar" style="display: inline;">
                <a class="btn btn-small" href="{genUrl controller="statistics" action="member" shortname=$cust->getShortname()}">
                    Statistics Overview
                </a>
            </div>
        </li>
        
    </ul>
    <div>
{else}
    <div class="page-content">
        <div class="page-header">
            <h1>IXP Peer to Peer Statistics :: {$cust->getName()}</h1>
        </div>
{/if}

{OSS_Message}

<p>
<form action="{genUrl controller="statistics" action="p2p"}" method="post">
<table>
<tr>
    {if $multiIXP}
        <td valign="middle"><strong>IXP:</strong></td>
        <td>
            &nbsp;
            <select name="ixp" style="width: 100px;" class="chzn-select" onchange="this.form.submit();">
                {foreach $ixps as $i}
                    <option value="{$i->getId()}" {if $ixp->getId() eq $i->getId()}selected="selected"{/if}>{$i->getShortname()}</option>
                {/foreach}
            </select>
        </td>
        <td width="20"></td>
    {else}
        <input type="hidden" name="ixp" value="{$ixp->getId()}" />
    {/if}
    <td valign="middle"><strong>Infrastructure:</strong></td>
    <td>
        &nbsp;
        <select name="infra" style="width: 50px;" class="chzn-select">
            {foreach $ixp->getInfrastructures() as $inf}
                <option value="{$inf->getId()}" {if $infra->getId() eq $inf->getId()}selected="selected"{/if}>{$inf->getShortname()}</option>
            {/foreach}
        </select>
    </td>
    <td width="20"></td>
    <td valign="middle"><strong>Graph Type:</strong></td>
    <td>
        &nbsp;
        <select name="category" style="width: 100px;" class="chzn-select">
            {foreach from=$categories key=cname item=cvalue}
                <option value="{$cvalue}" {if $category eq $cvalue}selected{/if}>{$cname}</option>
            {/foreach}
        </select>
    </td>
    <td width="20"></td>
    <td valign="middle"><strong>Period:</strong></td>
    <td>
        &nbsp;
        <select name="period" style="width: 100px;" class="chzn-select">
            {foreach from=$periods key=cname item=cvalue}
                <option value="{$cvalue}" {if $period eq $cvalue}selected{/if}>{$cname}</option>
            {/foreach}
        </select>
    </td>
    <td width="20"></td>
    <td valign="middle"><strong>Protocol:</strong></td>
    <td>
        &nbsp;
        <select name="proto" style="width: 100px;" class="chzn-select">
            {foreach from=$protocols key=pname item=pvalue}
                <option value="{$pvalue}" {if $proto eq $pvalue}selected="selected"{/if}>{$pname}</option>
            {/foreach}
        </select>
    </td>
    {if count( $vints ) > 1}
        <td width="20"></td>
        <td valign="middle"><strong>Interface:</strong></td>
        <td>
            &nbsp;
            <select name="interface" style="width: 100px;" class="chzn-select">
                {foreach $vints as $id => $vi}
                    <option value="{$id}" {if isset( $interface ) and $interface eq $id}selected="selected"{/if}>{$id}</option>
                {/foreach}
            </select>
        </td>
    {/if}
    <td width="20"></td>
    <td valign="middle">
        <input type="hidden" name="shortname" value="{$cust->getShortname()}" />
        <input class="btn" type="submit" value="Submit &raquo;" />
    </td>
    </tr>
</table>
</form>
</p>


{if count( $vints ) > 1}
    <div class="alert alert-info">
        <h4 class="alert-heading">Multiple Interfaces on this Infrastructure Found</h4>
        We've detected that you have multiple interfaces on this infrastructure. You can view your other
        interface(s) by changing the interface index above.
    </div>
{/if}

{if isset( $vints ) and is_array( $vints ) and count( $vints )}
    <div class="row-fluid">
    
    {assign var='count' value=0}
    {if $user->getPrivs() eq USER::AUTH_SUPERUSER}
    
    
        {foreach $customersWithVirtualInterfaces as $vcust}
            <div class="span3">
        
                <div class="well">
                    <h4 style="vertical-align: middle">
                        {$vcust.cname}
                    </h4>
        
                    <p>
                        <br />
                        <a href="{genUrl controller="statistics" action="p2p" ixp=$ixp->getId() shortname=$cust->getShortname() svid=$svid dvid=$vcust.id category=$category period=$period proto=$proto infra=$infra->getId()}">
                            <img
                                src="{genMrtgP2pImgUrl ixp=$ixp->getId() shortname=$cust->getShortname() svid=$svid dvid=$vcust.id category=$category proto=$proto period=$period infra=$infra->getId()}"
                                width="300"
                            />
                        </a>
                    </p>
                </div>
        
            </div>
        
            {assign var='count' value=$count+1}
        
            {if $count%4 eq 0}
                </div><br /><div class="row-fluid">
            {/if}
        {/foreach}
        
        {if $count%4 neq 0}
            <div class="span3"></div>
            {assign var='count' value=$count+1}
            {if $count%4 neq 0}
                <div class="span3"></div>
                {assign var='count' value=$count+1}
                {if $count%4 neq 0}
                    <div class="span3"></div>
                    {assign var='count' value=$count+1}
                {/if}
            {/if}
        {/if}
        
        
    {else}
    
    
        {foreach $customersWithVirtualInterfaces as $vcust}
        
            <div class="span6">
        
                <div class="well">
                    <h4 style="vertical-align: middle">
                        {$vcust.cname}
                    </h4>
        
                    <p>
                        <br />
                        <a href="{genUrl controller="statistics" action="p2p" shortname=$cust->getShortname() svid=$svid dvid=$vcust.id category=$category period=$period proto=$proto infra=$infra->getId()}">
                            <img
                                src="{genMrtgP2pImgUrl shortname=$cust->getShortname() svid=$svid dvid=$vcust.id category=$category proto=$proto period=$period infra=$infra->getId()}"
                                width="600"
                            />
                        </a>
                    </p>
                </div>
        
            </div>
        
            {assign var='count' value=$count+1}
        
            {if $count%2 eq 0}
                </div><br /><div class="row-fluid">
            {/if}
    
        {/foreach}
        
        {if $count%2 neq 0}
            <div class="span6"></div>
            {assign var='count' value=$count+1}
        {/if}
        
        
    {/if}
    
    </div>

{else} {* customer has an interface for given infra and proto *}

    <div class="alert alert-info">
        <h4 class="alert-heading">Uh oh! You (or your peer(s)) do not have any ports for the selected infrastructure and / or protocol.</h4>
        If you'd like to talk to us about enabling IPv6 or getting a port on the secondary infrastructure, please
        <a href="{genUrl controller="static" action="support"}">contact us</a>.
    </div>

{/if} {* customer has an interface for given infra and proto *}

</div>

{tmplinclude file="footer.phtml"}