{tmplinclude file="header.phtml"}


{if $user->getPrivs() eq 3}
    <ul class="breadcrumb">
        <li>
            <a href="{genUrl}">Home</a> <span class="divider">/</span>
        </li>
        <li>
            Switch Aggregate Graphs <span class="divider">/</span>
        </li>
        <li class="active">
            {$switches.$switch.name} ({foreach from=$categories key=cname item=cvalue}{if $category eq $cvalue}{$cname}{/if}{/foreach})
        </li>
    </ul>
{else}
    <div class="page-content">
        <div class="page-header">
            <h1>Switch Aggregate Graphs - {$switches.$switch.name} ({foreach from=$categories key=cname item=cvalue}{if $category eq $cvalue}{$cname}{/if}{/foreach})</h1>
        </div>
{/if}


{OSS_Message}

<div class="row-fluid">
    <div class="span12">
        <form action="{genUrl controller="statistics" action="switches"}" method="post" class="form-horizontal">
            <strong>Select Switch:</strong>
            <select name="switch" onchange="this.form.submit();" class="chzn-select">
                {foreach $switches as $id => $data}
                    <option value="{$id}" {if $switch eq $id}selected="selected"{/if}>{$data.name}</option>
                {/foreach}
            </select>
            <strong>Category:</strong>
            <select name="category" onchange="this.form.submit();" class="chzn-select">
                {foreach from=$categories key=cname item=cval}
                    <option value="{$cval}" {if $category eq $cval}selected{/if}>{$cname}</option>
                {/foreach}
            </select>
        </form>
    </div>
</div>


<div class="row-fluid">

{assign var='count' value=0}

{foreach from=$periods key=pname item=pvalue}


    <div class="span6">

        <div class="well">

        <h3>{$pname} Graph</h3>

        <p>
            {genMrtgGraphBox
                    shortname='X_SwitchAggregate'
                    period=$pvalue
                    category=$category
                    values=$stats.$pvalue
                    graph=$switches.$switch.name
            }
        </p>
        </div>
    </div>

    {assign var='count' value=$count+1}

    {if $count%2 eq 0}
        </div><br /><div class="row-fluid">
    {/if}


{/foreach}

{if $count%2 neq 0}
    <div class="span3"></div>
{/if}

</div>

{tmplinclude file="footer.phtml"}
