{tmplinclude file="header.phtml"}

{if $user->getPrivs() eq 3}
    <ul class="breadcrumb">
        <li>
            <a href="{genUrl}">Home</a> <span class="divider">/</span>
        </li>
        <li>
            Trunk Graphs <span class="divider">/</span>
        </li>
        <li class="active">
            {$graph->title()}
        </li>
    </ul>
{else}
    <div class="page-content">
        <div class="page-header">
            Trunk Graphs :: {$graph->title()}
        </div>
{/if}

{OSS_Message}

<div class="row-fluid">
    <div class="span12">
        <form action="{genUrl controller="statistics" action="trunks"}" method="post" class="form-horizontal">
            <strong>Select Trunk:&nbsp;&nbsp;</strong>
            <select name="trunk" onchange="this.form.submit();" class="chzn-select span4">
                {foreach from=$graphs key=image item=name}
                    <option value="{$image}" {if $namereq eq $image}selected{/if}>{$name}</option>
                {/foreach}
            </select>
        </form>
    </div>
</div>

<div class="row-fluid">

{assign var='count' value=0}


    {foreach from=$periods key=pvalue item=pname}

    <div class="span6">

        <div class="well">

            <h3>{$pname} Graph</h3>

            <p>
                {$graph->setPeriod( $pvalue )->renderer()->boxLegacy()}
            </p>
        </div>
    </div>

    {assign var='count' value=$count+1}

    {if $count%2 eq 0}
        </div><br /><div class="row-fluid">
    {/if}

{/foreach}

{if $count%2 neq 0}
    <div class="span3"></div>
{/if}

</div>

{tmplinclude file="footer.phtml"}
